// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"nl": {
    "lang": "Dutch",
    "obj": lang_nl(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_es(id, data) {
    const translation = {
        "payoff": "Acepta cripto en cualquier lugar",

        // PAGES
        "home": "inicio",
        "currencies": "criptomonedas",
        "requests": "solicitudes",
        "settings": "ajustes",
        "coinsettings": "ajustes de moneda",
        "addresses": "direcciones",

        // INTRO
        "enteryourname": "Introduce tu nombre",
        "more": "Más",
        "restorefrombackup": "Restaurar desde copia de seguridad",

        // CORE
        // notifications
        "datasaved": "Datos guardados",
        "pinmatch": "El código PIN no coincide",
        "xratesx": "No se pudo obtener el tipo de cambio",
        "entercoinaddress": "Introduce una dirección " + data.currency + ".",
        "label": "etiqueta (opcional)",
        "errorvk": "Error al verificar el Viewkey",
        "invalidvk": "Viewkey no válido",
        "continuevk": "¿Seguro que deseas continuar sin viewkey? Sin el viewkey las transacciones no pueden ser monitoreadas.",
        "novalidaddress": "NO es una dirección " + data.currency + " válida.",
        "pickacurrency": "Elige una moneda",
        "invalidlabel": "Etiqueta no válida",
        "noactivecurrencies": "No hay criptomonedas activas",
        "addressremoved": "Dirección eliminada",
        "movedtoarchive": "Movido al archivo",
        "requestrestored": "Solicitud restaurada",
        "requestdeleted": "Solicitud eliminada",
        "requestsaved": "Solicitud guardada",
        "requiredfields": "Completa los campos obligatorios",
        "requiredfield": "es un campo obligatorio",
        "nofetchincoice": "No se pudo obtener la factura.",
        "copy": "Copiar",
        "copied": "copiado al portapapeles",
        "xcopy": "No se pudo copiar",
        "cashiernotallowed": "No permitido en modo cajero",
        "decodeqr": "No se pudo decodificar el QR",
        "invalidformat": "Formato no válido",
        "invalidmacaroon": "Formato de macaroon no válido",
        "recentrequests": "Solicitudes recientes",
        "encodeyoraddress": "Codifica tu dirección en bitrequest.io/qr",
        // confirm
        "openurl": "¿Abrir " + data.url + "?",
        "showrequestsfor": "¿Mostrar solicitudes de " + data.address + "?",
        "areyousure": "¿Estás seguro?",
        "openinvoice": "¿Abrir factura: " + data.hash + "?",
        "sharefile": "¿Compartir " + data.filename + "?",
        // dialog
        "nofetchtokeninfo": "No se pudo obtener la info del token.",
        "archiverequest": "¿Archivar solicitud?",
        "unarchiverequest": "¿Desarchivar solicitud?",
        "failedtofetchrequest": "Error al obtener la solicitud",
        "downloadwallet": "Descargar monedero " + data.currency,

        // ADD ADDRESS
        "alreadyexists": "La dirección ya existe",
        "addaddress": "Añadir dirección",
        "adderc20token": "Añadir token ERC20",
        "erc20placeholder": "Elige token ERC20",
        "enteraddress": "Introduce dirección",
        "noaddressyet": "Aún no tengo una dirección " + data.currency,

        // ADDRESS INFO
        "showrequests": "Mostrar solicitudes",
        "newrequest": "Nueva solicitud",
        "addressinfo": "Info de dirección",
        "editlabel": "Editar etiqueta",
        "removeaddress": "Eliminar dirección",
        "recentpayments": "Pagos recientes",
        "privatekey": "Clave privada",
        "secretviewkey": "Clave secreta de visualización",
        "secretspendkey": "Clave secreta de gasto",

        // REQUEST INFO
        "currency": "Moneda",
        "from": "De",
        "title": "Descripción",
        "amount": "Monto",
        "status": "Estado",
        "Waiting for payment": "Esperando pago",
        "paid": "Pagado",
        "received": "Recibido",
        "insufficient": "Insuficiente",
        "new": "Nuevo",
        "pending": "Pendiente",
        "canceled": "Cancelado",
        "expired": "expirado",
        "type": "Tipo",
        "created": "Creado",
        "firstviewed": "Primera consulta",
        "sendon": "Enviado el",
        "paidon": "Pagado el",
        "amountreceived": "Monto recibido",
        "amountpaid": "Monto pagado",
        "fiatvalue": "Valor fiat",
        "fiatvalueon": "Valor fiat el",
        "receivingaddress": "Dirección de recepción",
        "fallbackaddress": "Dirección alternativa",
        "paymentid": "ID de pago",
        "integratedaddress": "Dirección integrada",
        "network": "Red",
        "incoming": "Entrante",
        "outgoing": "Saliente",
        "point of sale": "Punto de venta",
        "online purchase": "Compra en línea",
        "transactions": "Transacciones",
        "viewon": "Ver en",
        "source": "Origen",
        "deleterequest": "Eliminar solicitud",

        // REQUEST PANEL
        "sharerequest": "Compartir solicitud",
        "openwallet": "Abrir monedero",
        "whatsyourname": "¿Cuál es tu nombre?",
        "whatsitfor": "¿Para qué es?",
        "forexample": "ej",
        "send": "Enviar",
        "to": "a",
        "nodetection": "No se detectó ningún pago",
        "lookuppayment": "Buscar pagos " + data.currency + " recientes en " + data.blockexplorer,
        "dontshowagain": "No mostrar de nuevo",
        "dismiss": "descartar",
        "activateintegrated": "Activar direcciones integradas",
        "pendingrequest": "Solicitud pendiente",
        "paymentsent": "Pago enviado",
        "paymentreceived": "Pago recibido",
        "txbroadcasted": "Transacción transmitida",
        "insufficientamount": "Monto insuficiente",
        "txexpired": "Solicitud expirada",
        "viewdetails": "Ver detalles",
        "showqr": "Mostrar código QR",
        "waitingfor": "Esperando",
        "unconfirmedtx": "Transacción sin confirmar",
        "amountshort": "faltante",
        "sharelocktitle": "No se puede compartir la solicitud temporalmente.",
        "sharelockttext": "Esta dirección tiene una <span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>solicitud compartida pendiente</span>.",
        "waitforconfirm": "Espera a que la transacción se confirme antes de reutilizar la dirección.",
        "pickanotheraddress": "Elige otra dirección:",
        // ** request suggestion placeholders ** //
        "lunch": "Almuerzo",
        "festivaltickets": "Entradas de festival",
        "coffee": "Café",
        "present": "Regalo",
        "snowboarding": "Snowboard",
        "movietheater": "Cine",
        "shopping": "Compras",
        "videogame": "Videojuego",
        "drinks": "Bebidas",
        "concerttickets": "Entradas de concierto",
        "camping": "Camping",
        "taxi": "Taxi",
        "zoo": "Zoo",
        // notifications
        "failedhistoric": "Error al obtener datos históricos de precio de " + data.ccsymbol,
        "closingsockets": "Cerrando conexiones...",
        "nowriteaccess": "Acceso denegado al proxy LNurl, verifica los permisos de carpeta",
        "notmonitored": "Esta dirección no está siendo monitoreada",
        "lnoffline": "El nodo Lightning está desconectado",
        "addlightningnode": "Añadir nodo Lightning",
        "addressinuse": "Dirección en uso",
        "minimal2": "La descripción debe tener al menos 2 caracteres",
        "minimal3": "El nombre debe tener al menos 3 caracteres",
        "checkyourform": "Revisa tu formulario",
        "entertitle": "Introduce una descripción",
        "successshare": "¡Compartido con éxito!",
        // confirm
        "opencoinsettings": "¿Abrir ajustes de " + data.currency + "?",
        "viewpendingrequest": "¿Ver solicitud pendiente?",
        "useinstead": "¿Usar '" + data.thisinputvalue + "' en su lugar?",
        "generatenewaddress": "¿Seguro que deseas generar una nueva dirección " + data.currency + "? Puede que no aparezca en algunos monederos",
        // dialog
        "undefinedaddress": "Dirección no definida, solicita un nuevo pago",
        "invalidaddress": "Dirección " + data.payment + " no válida",

        // SHARE REQUEST
        "share": "compartir",
        "sharetitlename": (data.requestname === "Bitrequest") ? "Hola, he creado una solicitud " + data.pagenameccparam + " en bitrequest de " + data.amount + " " + data.uoa + " por '" + data.requesttitle + "'" : data.requestname + " ha enviado una solicitud de pago " + data.pagenameccparam + " de " + data.amount + " " + data.uoa + " por '" + data.requesttitle + "'",
        "sharetitle": "Solicitud de pago " + data.pagenameccparam + " de " + data.amount + " " + data.uoa,
        "sharetitlechange": "Solicitud de pago " + data.payment + " de " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "Tu nombre",
        "currencysettings": "Moneda fiat local",
        "entercurrency": "Introduce moneda",
        "setasdefault": "Establecer como predeterminado",
        "langsettings": "idioma",
        "chooselanguage": "Elige idioma",
        "themesettings": "Tema",
        "choosetheme": "Elige un tema",
        "security": "Seguridad",
        "pinsettings": "Bloqueo con código",
        "bip39_passphrase": "Frase secreta",
        "backupsecretphrase": "Respaldar frase secreta",
        "missingkeywarning": data.seedstrtitle + " para '<span class='adspan'>" + data.address + "</span>' no se encuentra.<br/>¿Seguro que deseas usar esta dirección?",
        "emptyphrase": "Introduce tu frase secreta",
        "notinwordlist": data.missing_word + " no está en la lista de palabras",
        "notbip39compatible": "Frase secreta no compatible con BIP39",
        "mustbe12characters": "La frase secreta debe tener 12 palabras",
        "cannotsendfunds": "¡Bitrequest no puede enviar fondos!",
        "importtosend": "Para enviar fondos necesitas restaurar tu <span class='show_bip39 ref'>frase secreta de 12 palabras</span> en un monedero compatible con BIP39:",
        "backup": "Copia de seguridad",
        "backupwithgd": "Copia de seguridad con Google Drive:",
        "nrchanges": "Tienes " + data.nr_changes + " cambios en tu app. Haz una copia de seguridad de tus datos.",
        "changein": "cambio en",
        "changesin": "cambios en",
        "systembackup": "Copia de seguridad del sistema",
        "downloadbu": "descargar copia de seguridad",
        "installlbu": "instalar copia de seguridad",
        "restore": "Restaurar datos de la app",
        "restorewithgd": "Restaurar desde Google Drive:",
        "lastrestore": "Última restauración:",
        "lastbackup": "Última copia de seguridad:",
        "restorefromfile": "Restaurar desde archivo",
        "differentsecretphrase": "Aviso. La copia de seguridad contiene una frase secreta diferente.",
        "secretphrasefrombackup": "Frase secreta de la copia de seguridad",
        "currentsecretphrase": "Frase secreta actual",
        "usesecretphrasefrombackup": "Usar frase secreta de la copia de seguridad",
        "keepcurrentsecretphrase": "Mantener frase secreta actual",
        "comparesecretphrases": "Comparar frases secretas",
        "csvexport": "Exportar CSV",
        "includearchive": "Incluir archivo",
        "includereceipt": "Incluir recibo",
        "receipt": "Recibo",
        "advanced": "Avanzado",
        "url_shorten_settings": "Acortador de URL",
        "shorturlnotfound": "Solicitud no encontrada",
        "cmcapisettings": "Datos de precios de criptomonedas",
        "fiatapisettings": "Datos de precios FIAT",
        "api_proxy": "Proxy API",
        "updateproxy": "Actualiza tu servidor proxy " + data.version + " > " + data.proxy_version,
        "addapiproxy": "Añadir proxy API",
        "controlyourkeys": "Controla tus propias claves y límites de solicitudes:",
        "proxystep1": "Aloja la <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>carpeta proxy API</a> en tu servidor (requiere PHP).",
        "proxystep2": "Introduce tus claves API en 'config.php'.",
        "proxystep3": "Introduce la dirección de tu servidor abajo.",
        "addrpcproxy": "Añadir proxy RPC",
        "tryotherproxy": "Probar otro proxy",
        "apikeys": "Claves API",
        "apicallfailed": "Llamada API fallida",
        "apididnotrespond": "La API no respondió",
        "contactform": "Formulario de contacto",
        "shipping": "envío",
        "yourdetails": "Tus datos para compras en línea.",
        "permissions": "Permisos",
        "teaminvite": "Invitación de equipo",
        "inviteteammembers": "Invita a miembros del equipo (personal, empleados, etc.) para hacer solicitudes en tu nombre.",
        "teaminviteexplainer": "Esto instalará Bitrequest en el dispositivo de tu miembro de equipo, preinstalado con tus claves públicas y acceso restringido (cajero).",
        "teaminviteaccess": "Los miembros de tu equipo no pueden acceder a los fondos ni hacer cambios.",
        "teaminviteharetitle": "Invitación de equipo Bitrequest de " + data.accountname,
        "teamupdate": "Actualización de equipo",
        "invitationexpiresin": "La invitación expira en",
        "installcompleted": "¡Instalación ya completada!",
        "teamup": "¡" + data.account + " quiere formar equipo y hacer solicitudes contigo!",
        "teamupdata": data.account + " quiere que actualices bitrequest con sus últimas claves públicas",
        "clickinstall": "Al hacer clic en instalar, bitrequest se instalará en tu dispositivo con las claves públicas de " + data.account + " y acceso restringido.",
        // notifications
        "nameisrequired": "El nombre es obligatorio",
        "currencysaved": "Moneda guardada",
        "currencynotsupported": "La moneda '" + data.currency + "' no está soportada",
        "noiosbu": "Descargas para la app de iOS no disponibles en este momento",
        "downloaded": data.file + " descargado",
        "filesize": "Archivo demasiado grande",
        "filetype": "Tipo de archivo '" + data.filetype + "' no soportado",
        "selectbackup": "Selecciona un archivo de respaldo",
        "unauthorized": "No autorizado",
        "maxattempts": "Intentos máximos superados",
        "fourdigitpin": "Introduce tu PIN de 4 dígitos",
        "wrongpin": "PIN incorrecto",
        "nocsvexports": "No hay solicitudes para exportar",
        "validateapikey": "Introduce una clave API válida",
        "unabletopost": "No se pudo enviar solicitud Post desde " + data.fixed_url,
        "invalidapikey": "Clave API no válida",
        "apicallerror": "Error en llamada API",
        "invalidapikeyname": "Clave API " + data.thisref + " no válida",
        "addapikey": "Añadir clave API de " + data.apisrc,
        "phname": "Nombre",
        "phaddress": "Dirección",
        "phzipcode": "Código postal",
        "phcity": "Ciudad",
        "phcountry": "País",
        "phemail": "correo electrónico",
        "invalidchars": "contiene caracteres no válidos",
        "pleaseverify": "Verifica tu frase secreta.",
        "owndevice": "No se puede instalar la invitación en tu propio dispositivo",
        "installcomplete": "¡Instalación completada!",
        // confirm
        "includesecretphrase": "¿Incluir frase secreta cifrada en la copia de seguridad? ¡Asegúrate de llevar un registro de tus archivos de respaldo!",
        "sharebu": "¿Compartir copia de seguridad del sistema?",
        "installsb": "¿INSTALAR COPIA DE SEGURIDAD DEL SISTEMA? TODOS TUS DATOS ACTUALES SERÁN REEMPLAZADOS",
        "downloadfile": "¿Descargar: " + data.file + "?",
        "restorefile": "¿Restaurar: " + data.file + "?",
        "restorefromdevice": "¿Restaurar " + data.file + " del dispositivo " + data.device + "?",
        "restorewithoutsecretphrase": "¿Restaurar sin frase secreta?",
        "keepexistingsecretphrase": "¿Seguro que deseas mantener tu frase secreta actual?",
        "sharecsvexport": "¿Compartir exportación CSV?",
        "disableshorturls": "¿Seguro que deseas desactivar el acortamiento de URL? Esto puede afectar el funcionamiento de la app",
        "sendinvite": "Enviar invitación",
        "updatealert": "¿Actualizar? Todas tus claves públicas actuales serán actualizadas.",
        "installalert": "¿Instalar? Todas tus claves públicas actuales serán reemplazadas.",

        // COIN SETTINGS
        "confirmations": "Confirmaciones",
        "showsatoshis": "Mostrar satoshis",
        "Use random address": "Usar dirección aleatoria",
        "Share viewkey": "Compartir viewkey",
        "Integrated addresses": "Direcciones integradas",
        "Reuse address": "Reutilizar dirección",
        "blockexplorers": "Blockexplorers",
        "chooseblockexplorer": "Elegir Blockexplorer",
        "apis": "APIs",
        "addapi": "Añadir " + data.h_hint + " RPC:",
        "websockets": "Websockets",
        "addwebsocket": "Añadir " + data.h_hint + " websocket:",
        "layer2": "Capa 2",
        "Xpub": "Xpub",
        "bip32xpub": "Clave pública extendida BIP32",
        "addxpub": "Añadir clave Xpub de " + data.currency,
        "xpubmatch": "Las direcciones anteriores coinciden con las de mi monedero " + data.currency + ".",
        "xpubkeys": "Poseo la frase secreta / clave Xpriv",
        "Key derivations": "Derivación de claves",
        "derivationpath": "Ruta de derivación",
        "soundbytes": "Efectos de sonido",
        "choosesoundbytes": "Elegir efecto de sonido",
        "resetbutton": "restablecer",
        // notifications
        "unabletoconnect": "No se pudo conectar",
        "nodealreadyadded": "Nodo ya añadido",
        "removedefaultnode": "No se puede eliminar el nodo predeterminado",
        "rpcnoderemoved": "Nodo RPC eliminado",
        "confirmmatch": "Confirma que las direcciones coinciden",
        "confirmpkownership": "Confirma la propiedad de la clave privada",
        "invalidxpub": "NO es una clave Xpub " + data.currency + " válida / soportada",
        "xpubsaved": "Xpub guardado",
        "resetnotify": "Ajustes de " + data.currency + " restablecidos a valores predeterminados",
        // confirm
        "reusewarningalert": "¿Seguro que deseas generar nuevas direcciones " + data.thiscurrency + "? Puede que no aparezcan en algunos monederos.",
        "reusealert": "¿Seguro que deseas reutilizar direcciones " + data.thiscurrency + "?",
        "confirmremovenode": "¿Seguro que deseas eliminar '" + data.thisval + "'?",
        "disablexpub": "¿Desactivar derivación de direcciones Xpub?",
        "replacexpub": "¿Reemplazar Xpub?",
        "uselegacy": "¿Usar direcciones " + data.thiscurrency + " Legacy?",
        "usesegwit": "¿Usar direcciones " + data.thiscurrency + " SegWit?",
        "resetconfirm": "¿Seguro que deseas restablecer los ajustes de " + data.currency + "?",
        // dialog
        "resetdialog": "¿Restablecer ajustes de " + data.currency + "?",

        // LIGHTNING
        "Lightning network": "Lightning Network",
        "lightningnode": "nodo Lightning",
        "addnode": "Añadir nodo",
        "implementation": "Implementación",
        "tabyourboldcard": "Acerca tu Boltcard a la parte trasera de este dispositivo",
        "controlyourlnkeys": "Controla tu propio nodo Lightning y tus claves:",
        "lnnodestep1": "Aloja la <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>carpeta proxy</a> en tu servidor web.",
        "lnnodestep2": "Introduce el host REST y las claves de tu nodo Lightning en 'config.php'.",
        "lnnodestep3": "Introduce la dirección de tu servidor abajo.",
        "enterlnapikey": "Introduce la clave API del proxy para desbloquear '" + data.proxy + "'",
        "viewinvoice": "Ver factura",
        "noinvoicesfound": "No se encontraron facturas.",
        "invoiceslocked": "Proxy del nodo bloqueado, no se pueden obtener facturas.<br/>Introduce tu <span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>clave API</span> del proxy.",
        "invoiceoffline": "Nodo desconectado, no se pueden obtener facturas.",
        // notifications
        "nodenotfound": "Nodo no encontrado",
        "proxynotfound": "Proxy no encontrado",
        "enterserver": "Introduce la dirección del servidor",
        "defaultproxy": data.fixed_url + " es un proxy predeterminado",
        "proxyexists": "Proxy ya añadido",
        "invalidurl": "URL no válida",
        "selectimplementation": "Selecciona implementación",
        "selectlnhost": "Selecciona host " + data.imp,
        "selectkeyname": "Selecciona " + data.impkeyname,
        "entermacaroon": "Introduce el macaroon 'invoice'",
        "invalidkeyformat": "Formato de clave no válido",
        "proxylocked": "El proxy del nodo actual está bloqueado, introduce tu clave API",
        "proxyoffline": "El nodo actual está desconectado, prueba el proxy " + data.proxy_message,
        "folderpermissions": "No se puede escribir en caché, verifica los permisos de carpeta.",
        "proxyadded": "Proxy añadido",
        "unabletoconnectto": "No se pudo conectar a " + data.value,
        "proxynameexists": "Nodo " + data.imp + " ya añadido",
        "proxyinuse": data.imp + ": '" + data.name + "' usa este proxy, elimínalo primero",
        "proxyremoved": "Proxy eliminado",
        "serviceremoved": "Servicio eliminado",
        "unknownproxy": "Servidor proxy desconocido",
        "proxyunlocked": "¡Proxy desbloqueado!",
        "proxydatamissing": "Faltan datos del proxy",
        "invoicecanceled": "Factura cancelada",
        // confirm
        "enablelightning": "¿Activar pagos Lightning?",
        "disablelightning": "¿Desactivar pagos Lightning?",
        "disableproxy": "¿Desactivar proxy " + data.set_proxy_val + "?",
        "enableproxy": "¿Activar proxy " + data.set_proxy_val + "?",
        // dialog
        "unabletoconnectln": "No se pudo conectar con el nodo Lightning",

        // BIP39
        "disclaimer": "¡Aviso legal!",
        "cannotbespend": "Los fondos recibidos en direcciones generadas desde tu frase secreta no pueden ser gastados por Bitrequest.<br/>Para gastar tus fondos necesitarás restaurar tu frase secreta en un <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>monedero compatible.</a>",
        "compatiblewallets": "Monederos compatibles",
        "important": "¡Importante!",
        "abouttobecome": "Estás a punto de ser tu propio banco.",
        "inthenextscreen": "En la siguiente pantalla, verás tu frase secreta.",
        "makesure": "¡Asegúrate de anotarla y guardarla en un lugar seguro!",
        "understandandok": "Lo entiendo y estoy de acuerdo.",
        "entersecretphrase": "Introduce tu frase secreta:",
        "writedownsecretphrase": "Anota tu frase secreta y guárdala en un lugar seguro.",
        "ifyouloseyourphrase": "Si pierdes tu frase,<br/>¡perderás tu dinero!",
        "understand": "¡Lo entiendo!",
        "verifycurrent": "Verificar frase secreta actual:",
        "verifybackup": "Verificar respaldo:",
        "withgreatpower": "Un gran poder conlleva una gran responsabilidad.",
        "remember": "Recuerda respaldar tu <span id='toseed'>frase secreta</span>.",
        "overwritten": "Asegúrate de respaldar tu <span id='toseed'>frase secreta</span> actual. Será sobrescrita",
        "word": "palabra",
        "idothislater": "Lo haré después",
        "ivebackeditup": "¡Ya la respaldé!",
        "next": "siguiente",
        "prev": "anterior",
        "findmorewallets": "Encontrar más monederos",
        // notifications
        "alreadyhavesecretphrase": "Ya tienes una frase secreta",
        "wrongsecretphrase": "Frase secreta incorrecta",
        "consent": "Acepta para continuar.",
        "secretphrasedeleted": "Frase secreta eliminada",
        "congratulations": "¡Felicidades! Ahora eres tu propio banco.",
        "passphraseverified": "Frase secreta verificada",
        "backupasap": "Respalda tu frase secreta lo antes posible",
        // confirm
        "resoresecretphrase": "Restaurar frase secreta",
        "areyousuredfp": "¿Seguro que deseas eliminar tu frase secreta?",
        "restoresecretphrasefrombackup": "¿Seguro que deseas restaurar tu frase secreta desde un respaldo? Tu frase secreta actual será borrada.",
        // dialog
        "continueatownrisk": "¡Advertencia! Continúa bajo tu propio riesgo.",
        "ifyouloseyourdevice": "Si pierdes tu dispositivo, desinstalas la aplicación o borras los datos del navegador, ¡necesitarás tu frase secreta para recuperar tus fondos!",
        "deletingyoursecretphrase": "¡Advertencia! Eliminar tu frase secreta puede resultar en pérdida de fondos.",
        "continuewithbackup": "Continúa solo si tienes un respaldo de tu frase secreta.",

        // SOCKETS
        // notifications
        "youareoffline": "Actualmente estás sin conexión",
        "networks": "redes",
        "acceptthepayment": "Acepta el pago en tu app Lightning...",
        "ndeftablimit": "Toque demasiado rápido",
        "enteramount": "Introduce el monto",
        "cardmax": "La solicitud supera el máximo de la tarjeta",
        "minamount": "El monto mínimo de solicitud es " + data.min,
        "waitingforpayment": "Esperando pago",
        "websocketoffline": "nodo desconectado",

        // PIN PANEL
        "pleaseenter": "Introduce tu PIN",
        "createpin": "Crea un PIN de 4 dígitos",
        "locktime": "Tiempo de bloqueo",
        "resetpin": "Restablecer PIN",
        "enternewpin": "Introduce nuevo PIN",
        "minute": "minuto",
        "minutes": "minutos",
        "never": "nunca",
        "pincodeactivated": "Código PIN activado",
        "pincodedisabled": "Código PIN desactivado",
        "confirmyourpin": "Confirma tu código PIN",

        // LOCKSCREEN
        "unlockwithsecretphrase": "Desbloquear con frase secreta",
        "tomanyunlocks": "Demasiados intentos de desbloqueo",
        "enter12words": "Introduce tu frase secreta<br/>de 12 palabras:",
        "tryagainin": "Inténtalo de nuevo en",
        "unlock": "Desbloquear",

        // BUTTONS AND PANELS
        "cancelbttn": "cancelar",
        "okbttn": "aceptar",
        "show": "Mostrar",
        "hide": "Ocultar",
        "delete": "eliminar",
        "restorebttn": "restaurar",
        "showtransactions": "Mostrar transacciones",
        "sharerequestbutton": "Compartir solicitud",
        "addcoinaddress": "Añadir dirección " + data.currency,
        "generatewallet": "Crear monedero desde frase secreta.",
        "pkownership": "Soy propietario de la clave privada de esta dirección.",
        "nopub": "Dirección / Xpub",
        "update": "actualizar",
        "install": "instalar",
        "pay": "pagar",

        //DIALOGS
        "totalchanges": "Tienes " + data.total_changes + " cambios en tu app",
        "nochanges": "Tienes 0 cambios en tu app",
        "havewallet": "¿Tienes un monedero " + data.lnd_ref + " en este dispositivo?",

        // DATES
        "sunday": "Domingo",
        "monday": "Lunes",
        "tuesday": "Martes",
        "wednesday": "Miércoles",
        "thursday": "Jueves",
        "friday": "Viernes",
        "saturday": "Sábado",
        "year": "año",
        "years": "años",
        "month": "mes",
        "months": "meses",
        "week": "semana",
        "weeks": "semanas",
        "day": "día",
        "days": "días",
        "hour": "hora",
        "hours": "horas",
        "minute": "minuto",
        "minutes": "minutos",
        "seconds": "segundos",
        "and": "y",
        "expiresin": "Expira en ",
        "fileexpired": "Archivo expirado",

        // LOADERTEXT
        "generatereceipt": "Generando recibo",
        "connecttolnur": "Conectando a " + data.url,
        "loadurl": "Cargando " + data.url,
        "loading": "cargando...",
        "gettokeninfo": "obteniendo info del token",
        "checklightningstatus": "Verificando estado Lightning de " + data.imp,
        "readingfromcache": "Leyendo tasa de " + data.ccsymbol + " desde caché",
        "getccrates": "Obteniendo tasas de " + data.ccsymbol + " de " + data.api,
        "getfiatrates": "Obteniendo tasas fiat",
        "readingfiatratesfromcache": "Leyendo tasas fiat desde caché",
        "fetchingfiatrates": "Obteniendo tasas fiat de " + data.fiatapi,
        "generatelink": "Generando enlace",
        "loadingcamera": "Cargando cámara",
        "generatebu": "Generar copia de seguridad del sistema",
        "installationpackage": "Generar paquete de instalación",

        // RANDOM TERMS
        "address": "dirección",
        "choose": "Elegir",
        "enable": "Activar",
        "disable": "Desactivar",
        "apikey": "Clave API",
        "yes": "sí",
        "no": "no",
        "none": "ninguno",
        "verified": "verificado",
        "error": "Error",
        "apierror": "error de API",
        "success": "Éxito",
        "warning": "¡Advertencia!",
        "edit": "Editar",
        "enter": "Introducir",

        // CHECK INTENTS
        "proto": data.proto + ": conexión no disponible en este momento",
        "invalidurlscheme": "Esquema de URL no válido",
        "usnotsupported": "El esquema de URL '" + data.proto + ":' no está soportado",

        // GOOGLE AUTH
        "stopgauth": "Dejar de usar Google Drive Backup.",
        "gauthsafely": "Respalda tus datos de forma segura.",
        "gauthsync": "Sincroniza tus datos de forma segura con Google Drive.",
        "signin": "Iniciar sesión",
        "backuptogd": "Respaldar en Google Drive",
        // notifications
        "ganot": "GoogleAuth no disponible",
        "gdsignedin": "Sesión iniciada correctamente",
        "gdsignedout": "Sesión cerrada correctamente",
        "filedeleted": "Archivo eliminado",
        "filenotfound": "Archivo no encontrado",
        // confirm
        "stopgdalert": "¿Seguro que deseas dejar de usar Google Drive Backup?",
        "deletefile": "¿Eliminar " + data.file + "?"
    }
    return translation[id];
}
