// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"nl": {
    "lang": "Dutch",
    "obj": lang_nl(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_fr(id, data) {
    const translation = {
        "payoff": "Votre terminal de paiement crypto facile",

        // PAGES
        "home": "home",
        "currencies": "crypto",
        "requests": "paiements",
        "settings": "paramètres",
        "coinsettings": "paramètres de crypto",
        "addresses": "adresses",

        // INTRO
        "enteryourname": "Veuillez entrer votre nom",
        "iwouldliketogetpaid": "Je voudrais être payé en:",
        "more": "Plus",
        "restorefrombackup": "Restaurer depuis une sauvergarde",

        // CORE
        // notifications
        "datasaved": "Données sauvegardées",
        "pinmatch": "code PIN incorrect",
        "xratesx": "Impossible d'obtenir les taux d'échange",
        "entercoinaddress": "Entrez une " + data.currency + " adresse.",
        "errorvk": "Erreur lors de la vérification du Viewkey",
        "invalidvk": "Viewkey invalide",
        "novalidaddress": "N'est pas une " + data.currency + " adresse valide.",
        "pickacurrency": "Choisissez une monnaie",
        "invalidlabel": "Étiquette invalide",
        "noactivecurrencies": "pas de devises actives",
        "addressremoved": "Adresse supprimée",
        "movedtoarchive": "Déplacé vers les archives",
        "requestrestored": "Paiement restaurée",
        "requestdeleted": "Paiement supprimée",
        "requestsaved": "Paiement sauvegardées",
        "requiredfields": "Remplissez les champs demandés, s'il vous plaît",
        "requiredfield": "est un champ obligatoire",
        "nofetchincoice": "Impossible de récupérer invoice.",
        "copy": "Copie",
        "copied": "copié dans le clipboard",
        "xcopy": "Impossible de copier",
        "cashiernotallowed": "Non autorisé en mode cashier",
        "decodeqr": "incapable de décoder qr",
        "invalidformat": "Format invalide",
        "invalidmacaroon": "Format macaron invalide",
        "recentrequests": "Paiements récentes",
        "encodeyoraddress": "Encode your address on bitrequest.io/qr",
        // confirm
        "openurl": "Ouvrez " + data.url + "?",
        "showrequestsfor": "Afficher les paiements de " + data.address + "?",
        "areyousure": "Es-tu sûr?",
        "openinvoice": "Ouvrez invoice: " + data.hash + "?",
        "sharefile": "Partager " + data.filename + "?",
        // dialog
        "nofetchtokeninfo": "Impossible d'obtenir le tokeninfo.",
        "archiverequest": "Archiver paiement?",
        "unarchiverequest": "Désarchiver paiement?",
        "failedtofetchrequest": "Impossible d'obtenir paiement",
        "downloadwallet": "Télécharger le portefeuille " + data.currency,

        // ADD ADDRESS
        "alreadyexists": "adresse existe déjà",
        "addaddress": "Ajoutez l'adresse",
        "adderc20token": "Ajoutez erc20 token",
        "erc20placeholder": "Choisir erc20 token",
        "enteraddress": "Entrer l'adresse",
        "noaddressyet": "Je n'ai pas encore d'adresse " + data.currency,

        // ADDRESS INFO
        "showrequests": "Afficher paiements",
        "newrequest": "Nouvelle paiement",
        "addressinfo": "Infos sur l'adresse",
        "editlabel": "Modifier l'étiquette",
        "removeaddress": "Retirer l'adresse",
        "recentpayments": "Paiements récents",
        "privatekey": "Clé privée",
        "secretviewkey": "Clé secrète d'audit",
        "secretspendkey": "Clé secrète dépense",

        // REQUEST INFO
        "currency": "Devise",
        "from": "De",
        "title": "Description",
        "amount": "Montant",
        "status": "Statut",
        "Waiting for payment": "En attente de paiement",
        "paid": "Payé",
        "insufficient": "Insuffisant",
        "new": "Nouveau",
        "pending": "En attente",
        "expired": "expiré",
        "type": "Genre",
        "created": "Créé",
        "firstviewed": "Première consultation",
        "sendon": "Envoyé sur",
        "paidon": "Payé",
        "amountreceived": "Montant reçu",
        "fiatvalue": "Valeur Fiat",
        "fiatvalueon": "Valeur Fiat sur",
        "receivingaddress": "Adresse de réception",
        "fallbackaddress": "Adresse de secours",
        "paymentid": "Identifiant de paiement",
        "integratedaddress": "Adresse intégrée",
        "network": "Réseau",
        "incoming": "Entrant",
        "outgoing": "Sortant",
        "point of sale": "Point de vente",
        "online purchase": "Achat en ligne",
        "transactions": "Transactions",
        "viewon": "Voir sur",
        "source": "Source",
        "deleterequest": "Supprimer paiement",

        // REQUEST PANEL
        "sharerequest": "Envoyer la note",
        "openwallet": "Ouvrir portefeuille",
        "whatsyourname": "Votre nom",
        "whatsitfor": "C'est pour quoi?",
        "forexample": "ex",
        "send": "Envoyer",
        "to": "à",
        "nodetection": "Aucun paiement détecté",
        "lookuppayment": "Vérifiez pour des paiements " + data.currency + " récents sur " + data.blockexplorer,
        "dontshowagain": "Ne plus afficher",
        "dismiss": "rejeter",
        "activateintegrated": "Activer les adresses intégrées",
        "pendingrequest": "Paiement en attente",
        "paymentsent": "Paiement envoyé",
        "paymentreceived": "Paiement reçu",
        "txbroadcasted": "Transaction diffusée",
        "insufficientamount": "Montant insuffisant",
        "txexpired": "Paiement expirée",
        "viewdetails": "Voir les détails",
        "showqr": "Afficher code QR",
        "waitingfor": "En attendant de",
        "unconfirmedtx": "Transaction non confirmée",
        "amountshort": "court",
        "sharelocktitle": "Temporairement impossible de partager paiement.",
        "sharelockttext": "Cette adresse a un <span id='view_pending_tx' data-requestid='" + data.pending_requestid + "'>paiement partagée en attente</span>.",
        "waitforconfirm": "Veuillez attendre la confirmation de la transaction avant de réutiliser l'adresse.",
        "pickanotheraddress": "Choisissez une autre adresse:",
        // ** request suggestion placeholders ** //
        "lunch": "Déjeuner",
        "festivaltickets": "Billet de festival",
        "coffee": "Café",
        "present": "Cadeau",
        "snowboarding": "Planche a neige",
        "movietheater": "Cinéma",
        "shopping": "Achats",
        "videogame": "Jeu vidéo",
        "drinks": "Boissons",
        "concerttickets": "Billet de concert",
        "camping": "Camping",
        "taxi": "Taxi",
        "zoo": "Zoo",
        // notifications
        "failedhistoric": "Échec de l'obtention des données historiques sur les prix du " + data.ccsymbol,
        "closingsockets": "Fermeture des connexions...",
        "nowriteaccess": "Accès à LNurl proxy refusé, vérifiez les autorisations",
        "notmonitored": "cette adresse n'est pas surveillée",
        "lnoffline": "Lightning node est hors ligne",
        "addlightningnode": "Ajouter lightning node",
        "addressinuse": "Adresse utilisée",
        "minimal2": "Description doit comporter au minimum 2 caractères",
        "minimal3": "Nom doit comporter au minimum 3 caractères",
        "checkyourform": "Veuillez vérifier votre formulaire",
        "entertitle": "Veuillez saisir une description",
        "successshare": "Partage réussi!",
        // confirm
        "opencoinsettings": "ouvrir les paramètres " + data.currency + "?",
        "viewpendingrequest": "Afficher paiement en attente?",
        "useinstead": "Utilisez plutôt '" + data.thisinputvalue + "'?",
        "generatenewaddress": "Êtes-vous sûr de vouloir générer une nouvelle adresse " + data.currency + "? Il se peut qu'il n'apparaisse pas dans certains portefeuilles",
        // dialog
        "undefinedaddress": "Adresse non définie, merci de demander une nouveau paiement",
        "invalidaddress": "Adresse " + data.payment + " invalide",

        // SHARE REQUEST
        "share": "partager",
        "sharetitlename": data.requestname + " a envoyé une demande de paiement " + data.pagenameccparam + " de " + data.amount + " " + data.uoa + " pour '" + data.requesttitle + "'",
        "sharetitle": "Demande de paiement " + data.pagenameccparam + " de " + data.amount + " " + data.uoa,
        "sharetitlechange": "Demande de paiement " + data.payment + " de " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "Nom",
        "currencysettings": "Monnaie Fiat locale",
        "entercurrency": "Entrez une devise",
        "setasdefault": "Définir par défaut",
        "langsettings": "langue",
        "chooselanguage": "Choisissez la langue",
        "security": "Sécurité",
        "pinsettings": "Verrouillage par code PIN",
        "bip39_passphrase": "Phrase secrète",
        "backupsecretphrase": "sauvegardez votre phrase secrète",
        "missingkeywarning": data.seedstrtitle + " pour '<span class='adspan'>" + data.address + "</span>' est manquante.<br/>Êtes vous sûrs de vouloir utiliser cette addresse?",
        "emptyphrase": "Veuillez entrer votre phrase secrète",
        "notinwordlist": data.missing_word + " n'est pas dans la liste de mots",
        "notbip39compatible": "Phrase secrète non compatible avec Bip39",
        "mustbe12characters": "La phrase secrète doit comporter 12 caractères",
        "cannotsendfunds": "Bitrequest ne peut pas envoyer de crypto-monnaie!",
        "importtosend": "Pour envoyer de la crypto-monnaie, vous devez restaurer votre <span class='show_bip39 ref'>phrase secrète de 12 mots</span> dans un portefeuille compatible bip39:",
        "backup": "Sauvegarder les données de l'application",
        "backupwithgd": "Sauvegarde avec Google Drive:",
        "nrchanges": "Vous avez " + data.nr_changes + " modifications dans votre application. Veuillez sauvegarder vos données.",
        "changein": "modification dans",
        "changesin": "modifications dans",
        "systembackup": "Sauvegarde du système",
        "downloadbu": "télécharger la sauvegarde",
        "installlbu": "installer la sauvegarde",
        "restore": "Restaurer les données de l'application",
        "restorewithgd": "Restaurer depuis Google Drive:",
        "lastrestore": "Dernière restauration:",
        "lastbackup": "Dernière sauvegarde:",
        "restorefromfile": "Restaurer à partir d'un fichier",
        "differentsecretphrase": "Attention. La sauvegarde contient une phrase secrète différente.",
        "secretphrasefrombackup": "Phrase secrète de la sauvegarde",
        "currentsecretphrase": "Phrase secrète actuelle",
        "usesecretphrasefrombackup": "Utiliser la phrase secrète de la sauvegarde",
        "keepcurrentsecretphrase": "Conserver la phrase secrète actuelle",
        "comparesecretphrases": "comparer des phrases secrètes",
        "csvexport": "Exporter au format CSV",
        "includearchive": "Inclure les archives",
        "includereceipt": "Inclure le reçu",
        "receipt": "Reçu",
        "advanced": "Avancé",
        "url_shorten_settings": "Raccourcisseur d'URL",
        "shorturlnotfound": "Paiement introuvable",
        "cmcapisettings": "Données sur les prix des cryptomonnaies",
        "fiatapisettings": "Données sur les prix de FIAT",
        "api_proxy": "API Proxy",
        "updateproxy": "Veuillez mettre à jour votre serveur proxy " + data.version + " > " + data.proxy_version,
        "addapiproxy": "Ajouter un API proxy",
        "controlyourkeys": "Contrôlez vos propres clés et demandez des limites:",
        "proxystep1": "Hébergez le <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>dossier API proxy</a> sur votre serveur (php requis).",
        "proxystep2": "Entrez vos clés API dans 'config.php'.",
        "proxystep3": "Entrez l'adresse de votre serveur ci-dessous.",
        "addrpcproxy": "Ajouter un proxy RPC",
        "tryotherproxy": "Essayez un autre proxy",
        "apikeys": "Clés API",
        "apicallfailed": "L'appel API a échoué",
        "apididnotrespond": "API n'a pas répondu",
        "contactform": "Formulaire de contact",
        "shipping": "expédition",
        "yourdetails": "Vos coordonnées pour les achats en ligne.",
        "permissions": "Autorisations",
        "teaminvite": "Invitation d'équipe",
        "inviteteammembers": "Invitez les membres de l’équipe (personnel, employés, etc.) à faire des paiements en votre nom.",
        "teaminviteexplainer": "Cela installera Bitrequest sur l'appareil du membre de votre équipe, préinstallé avec vos clés publiques et un accès restreint (cashier).",
        "teaminviteaccess": "Les membres de votre équipe ne peuvent pas accéder aux fonds ou apporter des modifications.",
        "teaminviteharetitle": "Bitrequest Invitation de l'équipe de " + data.accountname,
        "teamupdate": "Update l'équipe",
        "invitationexpiresin": "L'invitation expire dans",
        "installcompleted": "Installation déjà terminée!",
        "teamup": data.account + " souhaite faire équipe et faire des paiements avec vous!",
        "teamupdata": data.account + " veut que vous mettiez à jour bitrequest avec ses dernières clés publiques.",
        "clickinstall": "En cliquant sur installer, bitrequest sera installé sur votre appareil avec les clés publiques de " + data.account + ", et set un accès restreint (cashier).",
        // notifications
        "nameisrequired": "Nom est requis",
        "currencysaved": "Devise enregistrée",
        "currencynotsupported": "la devise '" + data.currency + "' n'est pas prise en charge.",
        "noiosbu": "Les téléchargements pour l’application IOS ne sont pas disponibles pour le moment",
        "downloaded": data.file + " téléchargé",
        "filesize": "Taille du fichier trop grande",
        "filetype": "Le type de fichier '" + data.filetype + "' n'est pas pris en charge",
        "selectbackup": "Sélectionnez un fichier de sauvegarde",
        "unauthorized": "Unauthorized",
        "maxattempts": "Nombre maximal de tentatives dépassé",
        "fourdigitpin": "Entrez votre code PIN à 4 chiffres",
        "wrongpin": "Mauvais code PIN",
        "nocsvexports": "Aucune paiements d'exportation",
        "validateapikey": "Saisissez une clé API valide",
        "unabletopost": "Impossible d'envoyer une Post request depuis " + data.fixed_url,
        "invalidapikey": "Clé API invalide",
        "apicallerror": "Erreur d'appel API",
        "invalidapikeyname": "Clé API " + data.thisref + " invalide",
        "addapikey": "Ajouter la clé API " + data.apisrc,
        "phname": "Nom",
        "phaddress": "Adresse",
        "phzipcode": "Code Postal",
        "phcity": "Résidence",
        "phcountry": "Pays",
        "phemail": "e-mail",
        "invalidchars": "contient des caractères non valides",
        "pleaseverify": "Veuillez vérifier votre phrase secrète.",
        "owndevice": "Impossible d'installer l'invitation sur son propre appareil.",
        "installcomplete": "Installation complète!",
        // confirm
        "includesecretphrase": "Inclure votre phrase secrète cryptée dans la sauvegarde? Assurez-vous de garder une trace de vos fichiers de sauvegarde!",
        "sharebu": "Partager la sauvegarde du système?",
        "installsb": "INSTALLER LA SAUVEGARDE DU SYSTÈME ? TOUTES LES DONNÉES DE VOTRE APPLICATION ACTUELLES SERONT REMPLACÉES",
        "downloadfile": "Télécharger: " + data.file + "?",
        "restorefile": "Restaurer: " + data.file + "?",
        "restorefromdevice": "Restaurer " + data.file + " de appareil " + data.device + "?",
        "restorewithoutsecretphrase": "Restaurer sans phrase secrète?",
        "keepexistingsecretphrase": "Êtes-vous sûr de vouloir conserver votre phrase secrète existante?",
        "sharecsvexport": "Partager l'exportation CSV?",
        "disableshorturls": "Êtes-vous sûr de vouloir désactiver le raccourcissement d'URL ? Cela peut affecter le flux de travail de cette application",
        "sendinvite": "Envoyer invitation",
        "updatealert": "Mise à jour? Toutes vos clés publiques actuelles seront mises à jour.",
        "installalert": "Installer? Toutes vos clés publiques actuelles seront remplacées.",

        // COIN SETTINGS
        "confirmations": "Confirmation",
        "showsatoshis": "Afficher satoshis",
        "Use random address": "Utiliser une adresse au hasard",
        "Share viewkey": "Partager la clé secrète d'audit",
        "Integrated addresses": "Adresses intégrées",
        "Reuse address": "Réutiliser l'adresse",
        "blockexplorers": "Blockexplorers",
        "chooseblockexplorer": "Choisir Blockexplorer",
        "apis": "APIs",
        "addapi": "Ajoutez " + data.h_hint + " RPC:",
        "websockets": "Websockets",
        "addwebsocket": "Ajoutez " + data.h_hint + " websocket:",
        "layer2": "Couche 2",
        "Xpub": "Xpub",
        "bip32xpub": "Clé publique étendue BIP32",
        "addxpub": "Ajoutez " + data.currency + " clé Xpub",
        "xpubmatch": "Les adresses ci-dessus correspondent à mon portefeuille " + data.currency,
        "xpubkeys": "Je possède la phrase secrète / la clé Xpriv",
        "Key derivations": "Clés dérivations",
        "derivationpath": "Itinéraire de dérivation",
        "resetbutton": "réinitialiser",
        // notifications
        "unabletoconnect": "Unable to connect",
        "nodealreadyadded": "Node déjà ajouté",
        "removedefaultnode": "Impossible de supprimer le node par défaut",
        "rpcnoderemoved": "Node RPC supprimé",
        "confirmmatch": "Confirmer que les adresses correspondent",
        "confirmpkownership": "Confirmer la propriété de la clé privée",
        "invalidxpub": "PAS une clé " + data.currency + " Xpub valide / prise en charge.",
        "xpubsaved": "XPub enregistré",
        "resetnotify": "les paramètres " + data.currency + "sont réinitialisés par défaut.",
        // confirm
        "reusewarningalert": "Êtes-vous sûr de vouloir générer de nouvelles adresses " + data.thiscurrency + "? ils peuvent ne pas apparaître dans certains portefeuilles.",
        "reusealert": "Êtes-vous sûr de vouloir réutiliser les adresses " + data.thiscurrency + "?",
        "confirmremovenode": "Etes-vous sûr de vouloir supprimer '" + data.thisval + "'?",
        "disablexpub": "Désactiver la dérivation d'adresse Xpub?",
        "replacexpub": "Remplacer Xpub?",
        "uselegacy": "Utiliser des adresses " + data.thiscurrency + " Legacy?",
        "usesegwit": "Utiliser des adresses " + data.thiscurrency + " SegWit?",
        "resetconfirm": "Êtes-vous sûr de vouloir réinitialiser les paramètres " + data.currency + "?",
        // dialog
        "resetdialog": "Réinitialiser les paramètres " + data.currency + "?",

        // LIGHTNING
        "Lightning network": "Réseau Lightning",
        "lightningnode": "Node lightning",
        "addnode": "Ajouter node",
        "implementation": "Implémentation",
        "tabyourboldcard": "Veuillez placer votre Boltcard à l'arrière de cet appareil.",
        "controlyourlnkeys": "Contrôlez votre propre node Lightning et vos clés:",
        "lnnodestep1": "Hébergez le <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>dossier proxy</a> sur votre serveur Web.",
        "lnnodestep2": "Entrez l'hôte REST et les clés de votre node Lightning dans 'config.php'.",
        "lnnodestep3": "Entrez l'adresse de votre serveur ci-dessous.",
        "enterlnapikey": "Entrez la clé API proxy pour déverrouiller '" + data.proxy + "'",
        "viewinvoice": "Voir la facture Lightning",
        "noinvoicesfound": "Aucune facture Lightning trouvée.",
        "invoiceslocked": "Node proxy verrouillé, impossible de récupérer les factures.<br/>Veuillez saisir votre <span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>clé API</span> proxy.",
        "invoiceoffline": "Node hors ligne, impossible de récupérer les factures Lightning.",
        // notifications
        "nodenotfound": "Node introuvable",
        "proxynotfound": "Proxy introuvable",
        "enterserver": "Veuillez entrer l'adresse du serveur",
        "defaultproxy": data.fixed_url + " est un proxy par défaut",
        "proxyexists": "Proxy déjà ajouté",
        "invalidurl": "URL invalide",
        "selectimplementation": "Sélectionnez implémentation",
        "selectlnhost": "sélectionnez l'hôte " + data.imp,
        "selectkeyname": "sélectionnez " + data.impkeyname,
        "entermacaroon": "Veuillez saisir 'invoice' macaroon",
        "invalidkeyformat": "Format de clé invalide",
        "proxylocked": "Node proxy actuel est verrouillé, veuillez saisir votre clé API",
        "proxyoffline": "Node actuel est hors ligne, essayez le proxy " + data.proxy_message,
        "folderpermissions": "Impossible d'écrire dans le cache, veuillez vérifier les autorisations de votre dossier.",
        "proxyadded": "Proxy ajouté",
        "unabletoconnectto": "Impossible de se connecter à " + data.value,
        "proxynameexists": "Node '" + data.imp + "' déjà été ajouté",
        "proxyinuse": data.imp + ": '" + data.name + "' utilise ce proxy, supprimez-le d'abord",
        "proxyremoved": "Proxy supprimé",
        "serviceremoved": "Service supprimé",
        "unknownproxy": "Serveur proxy inconnu",
        "proxyunlocked": "Proxy débloqué!",
        "proxydatamissing": "Données proxy manquantes",
        "invoicecanceled": "Facture Lightning annulée",
        // confirm
        "enablelightning": "Activer les paiements Lightning?",
        "disablelightning": "Désactiver les paiements Lightning?",
        "disableproxy": "Désactiver proxy " + data.set_proxy_val + "?",
        "enableproxy": "Activer proxy " + data.set_proxy_val + "?",
        // dialog
        "unabletoconnectln": "Impossible de se connecter au node Lightning",

        // BIP39
        "disclaimer": "Clause de non-responsabilité!",
        "cannotbespend": "Les fonds reçus par les adresses générées à partir de votre phrase secrète ne peuvent pas être dépensés par Bitrequest.<br/>Pour dépenser vos fonds, vous devrez restaurer votre phrase secrète dans un <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>portefeuille compatible.</a>",
        "compatiblewallets": "Portefeuilles compatibles",
        "important": "Important!",
        "abouttobecome": "Vous êtes sur le point de devenir votre propre banque.",
        "inthenextscreen": "Dans l'écran suivant, vous verrez votre phrase secrète.",
        "makesure": "Assurez-vous de l’écrire et de le mettre dans un endroit sûr!",
        "understandandok": "Je comprends et je suis d'accord avec ça.",
        "entersecretphrase": "Entrez votre phrase secrète:",
        "writedownsecretphrase": "Notez votre phrase secrète et placez-la dans un endroit sûr.",
        "ifyouloseyourphrase": "Si vous perdez votre phrase secrète, vous perdrez votre argent!",
        "understand": "Je comprends!",
        "verifycurrent": "Vérifier la phrase secrète actuelle:",
        "verifybackup": "Vérifier la sauvegarde:",
        "withgreatpower": "Un grand pouvoir implique de grandes responsabilités.",
        "remember": "N'oubliez pas de sauvegarder votre <span id='toseed'>phrase secrète</span>.",
        "overwritten": "Assurez-vous de sauvegarder votre <span id='toseed'>phrase secrète</span> actuelle. Il sera écrasé",
        "word": "mot",
        "idothislater": "je fais ça plus tard",
        "ivebackeditup": "Je l'ai sauvegardé!",
        "next": "suivant",
        "prev": "précédent",
        "findmorewallets": "Trouver plus de portefeuilles",
        // notifications
        "alreadyhavesecretphrase": "Vous avez déjà une phrase secrète",
        "wrongsecretphrase": "mauvaise phrase secrète",
        "consent": "Veuillez consentir à continuer.",
        "secretphrasedeleted": "Phrase secrète supprimée",
        "congratulations": "Toutes nos félicitations. Vous êtes désormais votre propre banque!",
        "passphraseverified": "Phrase secrète vérifiée",
        "backupasap": "Veuillez sauvegarder votre phrase secrète dès que possible",
        // confirm
        "resoresecretphrase": "Restaurer phrase secrète",
        "areyousuredfp": "Êtes-vous sûr de vouloir supprimer votre phrase secrète?",
        "restoresecretphrasefrombackup": "Êtes-vous sûr de vouloir restaurer votre phrase secrète à partir d'une sauvegarde ? Votre phrase secrète actuelle sera effacée.",
        // dialog
        "continueatownrisk": "Avertissement! Continuez à vos propres risques.",
        "ifyouloseyourdevice": "Si vous perdez votre appareil, désinstallez votre application ou effacez les données de votre navigateur, vous aurez besoin de votre phrase secrète pour récupérer vos fonds!",
        "deletingyoursecretphrase": "Avertissement! La suppression de votre phrase secrète peut entraîner une perte de fonds.",
        "continuewithbackup": "Continuez uniquement si vous disposez d’une sauvegarde de votre phrase secrète.",

        // SOCKETS
        // notifications
        "youareoffline": "Vous êtes actuellement hors ligne",
        "networks": "réseaux",
        "acceptthepayment": "Acceptez le paiement dans votre application Lightning...",
        "ndeftablimit": "Tapé trop vite",
        "enteramount": "Veuillez entrer le montant",
        "cardmax": "La demande dépasse le maximum de la carte",
        "minamount": "Le montant minimum de la demande est de " + data.min,
        "waitingforpayment": "En attente de paiement",
        "websocketoffline": "websocket hors ligne",

        // PIN PANEL
        "pleaseenter": "Veuillez entrer votre code PIN",
        "createpin": "Créer un code PIN à 4 chiffres",
        "locktime": "Temps de verrouillage",
        "resetpin": "Réinitialiser le code PIN",
        "enternewpin": "Entrez un nouveau code PIN",
        "minute": "minute",
        "minutes": "minutes",
        "never": "jamais",
        "pincodeactivated": "Code PIN activé",
        "pincodedisabled": "Code PIN désactivé",
        "confirmyourpin": "Confirmez votre code PIN",

        // LOCKSCREEN
        "unlockwithsecretphrase": "Débloquez avec votre phrase secrète",
        "tomanyunlocks": "Trop de tentatives de déverrouillage",
        "enter12words": "Entrez votre phrase secrète de 12 mots:",
        "tryagainin": "Veuillez réessayer dans",
        "unlock": "Ouvrir",

        // BUTTONS AND PANELS
        "cancelbttn": "Annuler",
        "okbttn": "d'accord",
        "show": "Montrer",
        "hide": "Cacher",
        "delete": "supprimer",
        "restorebttn": "restaurer",
        "showtransactions": "Afficher les transactions",
        "sharerequestbutton": "Envoyer la note",
        "addcoinaddress": "Ajouter une adresse " + data.currency,
        "generatewallet": "Générer un portefeuille ainsi qu'une phrase secrète.",
        "pkownership": "Je suis propriétaire la clé privée de cette addresse.",
        "nopub": "Adresse / Xpub",
        "update": "mise à jour",
        "install": "installer",
        "pay": "payer",

        //DIALOGS
        "totalchanges": "Vous avez " + data.total_changes + " modifications dans votre application",
        "nochanges": "Vous avez 0 modifications dans votre application",
        "havewallet": "Avez-vous un portefeuille " + data.lnd_ref + " sur cet appareil?",

        // DATES
        "sunday": "Dimanche",
        "monday": "Lundi",
        "tuesday": "Mardi",
        "wednesday": "Wednesday",
        "thursday": "Jeudi",
        "friday": "Vendredi",
        "saturday": "Samedi",
        "year": "année",
        "years": "ans",
        "month": "mois",
        "months": "mois",
        "week": "semaine",
        "weeks": "semaines",
        "day": "jour",
        "days": "jours",
        "hour": "heure",
        "hours": "heures",
        "minute": "minute",
        "minutes": "minutes",
        "seconds": "seconds",
        "and": "et",
        "expiresin": "Expire dans ",
        "fileexpired": "Fichier expiré",

        // LOADERTEXT
        "generatereceipt": "Générer un reçu",
        "connecttolnur": "Connexion à " + data.url,
        "loadurl": "Chargement " + data.url,
        "loading": "Chargement...",
        "gettokeninfo": "obtenir des informations sur le jeton",
        "checklightningstatus": "Vérifier " + data.imp + " statut",
        "readingfromcache": "Lecture du taux de change " + data.ccsymbol + " depuis le cache",
        "getccrates": "Récupération du taux de change " + data.ccsymbol + " de " + data.api,
        "getfiatrates": "Récupération du taux de change FIAT",
        "readingfiatratesfromcache": "Lire du taux de change FIAT à partir du cache",
        "fetchingfiatrates": "Récupération du taux de change FIAT à partir de " + data.fiatapi,
        "generatelink": "Création du lien",
        "loadingcamera": "Caméra à ouvrir",
        "generatebu": "Générer une sauvegarde du système",
        "installationpackage": "Générer le package d'installation",
        "closingrequest": "Paiement de clôture",
        "scanningforincoming": "analyse des transactions entrantes",

        // RANDOM TERMS
        "address": "adresse",
        "choose": "Choisir",
        "enable": "Activer",
        "disable": "Désactiver",
        "apikey": "Clé API",
        "yes": "oui",
        "no": "non",
        "verified": "vérifié",
        "error": "Erreur",
        "apierror": "erreur API",
        "success": "Succès",
        "warning": "Attention!",
        "edit": "Modifier",
        "enter": "Entrer",

        // CHECK INTENTS
        "proto": data.proto + ": connect pas disponible pour le moment",
        "invalidurlscheme": "Schéma d'URL invalide",
        "usnotsupported": "Schéma d'URL '" + data.proto + ":' n'est pas pris en charge",

        // GOOGLE AUTH
        "stopgauth": "Arrêtez d'utiliser la sauvegarde Google Drive.",
        "gauthsafely": "Sauvegardez en toute sécurité vos données d'application.",
        "gauthsync": "Synchronisez vos données en toute sécurité avec Google Drive.",
        "signin": "Se connecter",
        "backuptogd": "Sauvegarder sur Google Drive",
        // notifications
        "ganot": "GoogleAuth non disponible",
        "gdsignedin": "Connexion réussie",
        "gdsignedout": "Déconnexion réussie",
        "filedeleted": "Fichier supprimé",
        "filenotfound": "Fichier introuvable",
        // confirm
        "stopgdalert": "Êtes-vous sûr de vouloir arrêter d'utiliser Google Drive Backup?",
        "deletefile": "Supprimer" + " " + data.file + "?"
    }
    return translation[id];
}