// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"hi": {
    "lang": "Hindi",
    "obj": lang_hi(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_hi(id, data) {
    const translation = {
        "payoff": "कहीं भी क्रिप्टो स्वीकारें",

        // PAGES
        "home": "होम",
        "currencies": "मुद्राएँ",
        "requests": "अनुरोध",
        "settings": "सेटिंग्स",
        "coinsettings": "कॉइन सेटिंग्स",
        "addresses": "पते",

        // INTRO
        "enteryourname": "कृपया अपना नाम दर्ज करें",
        "more": "और",
        "restorefrombackup": "बैकअप से पुनर्स्थापित करें",

        // CORE
        // notifications
        "datasaved": "डेटा सहेजा गया",
        "pinmatch": "पिन कोड मेल नहीं खाता",
        "xratesx": "विनिमय दर प्राप्त नहीं हो सकी",
        "entercoinaddress": "एक " + data.currency + " पता दर्ज करें।",
        "label": "लेबल (वैकल्पिक)",
        "errorvk": "Viewkey सत्यापन में त्रुटि",
        "invalidvk": "अमान्य Viewkey",
        "continuevk": "क्या आप बिना viewkey के जारी रखना चाहते हैं? Viewkey के बिना लेनदेन की निगरानी नहीं हो सकती।",
        "novalidaddress": "एक मान्य " + data.currency + " पता नहीं है।",
        "pickacurrency": "मुद्रा चुनें",
        "invalidlabel": "अमान्य लेबल",
        "noactivecurrencies": "कोई सक्रिय मुद्रा नहीं",
        "addressremoved": "पता हटाया गया",
        "movedtoarchive": "आर्काइव में ले जाया गया",
        "requestrestored": "अनुरोध पुनर्स्थापित",
        "requestdeleted": "अनुरोध हटाया गया",
        "requestsaved": "अनुरोध सहेजा गया",
        "requiredfields": "कृपया आवश्यक फ़ील्ड भरें",
        "requiredfield": "एक आवश्यक फ़ील्ड है",
        "requestinginvoice": "Invoice का अनुरोध हो रहा है...",
        "nofetchincoice": "Invoice प्राप्त नहीं हो सका।",
        "copy": "कॉपी",
        "copied": "क्लिपबोर्ड पर कॉपी किया गया",
        "xcopy": "कॉपी नहीं हो सका",
        "cashiernotallowed": "कैशियर मोड में अनुमति नहीं है",
        "decodeqr": "QR डिकोड नहीं हो सका",
        "invalidformat": "अमान्य फ़ॉर्मेट",
        "invalidmacaroon": "अमान्य Macaroon फ़ॉर्मेट",
        "recentrequests": "हाल के अनुरोध",
        "encodeyoraddress": "अपना पता bitrequest.io/qr पर एनकोड करें",
        // confirm
        "openurl": data.url + " खोलें?",
        "showrequestsfor": data.address + " के लिए अनुरोध दिखाएँ?",
        "areyousure": "क्या आप निश्चित हैं?",
        "openinvoice": "Invoice खोलें: " + data.hash + "?",
        "sharefile": data.filename + " साझा करें?",
        // dialog
        "nofetchtokeninfo": "टोकन डेटा प्राप्त नहीं हो सका।",
        "archiverequest": "अनुरोध आर्काइव करें?",
        "unarchiverequest": "अनुरोध अनआर्काइव करें?",
        "failedtofetchrequest": "अनुरोध प्राप्त करने में विफल",
        "downloadwallet": data.currency + " वॉलेट डाउनलोड करें",

        // ADD ADDRESS
        "alreadyexists": "पता पहले से मौजूद है",
        "addaddress": "पता जोड़ें",
        "adderc20token": "ERC20 टोकन जोड़ें",
        "erc20placeholder": "ERC20 टोकन चुनें",
        "enteraddress": "पता दर्ज करें",
        "noaddressyet": "मेरे पास अभी " + data.currency + " पता नहीं है",

        // ADDRESS INFO
        "showrequests": "अनुरोध दिखाएँ",
        "newrequest": "नया अनुरोध",
        "addressinfo": "पता जानकारी",
        "editlabel": "लेबल संपादित करें",
        "removeaddress": "पता हटाएँ",
        "recentpayments": "हाल के भुगतान",
        "privatekey": "निजी कुंजी",
        "secretviewkey": "गोपनीय व्यू कुंजी",
        "secretspendkey": "गोपनीय स्पेंड कुंजी",

        // REQUEST INFO
        "currency": "मुद्रा",
        "from": "प्रेषक",
        "title": "विवरण",
        "amount": "राशि",
        "status": "स्थिति",
        "Waiting for payment": "भुगतान की प्रतीक्षा",
        "paid": "भुगतान हुआ",
        "received": "प्राप्त हुआ",
        "insufficient": "अपर्याप्त",
        "new": "नया",
        "pending": "लंबित",
        "canceled": "रद्द",
        "expired": "समाप्त",
        "type": "प्रकार",
        "created": "बनाया गया",
        "firstviewed": "पहली बार देखा गया",
        "sendon": "अनुरोध भेजा गया",
        "paidon": "भुगतान हुआ",
        "amountreceived": "प्राप्त राशि",
        "amountpaid": "भुगतान राशि",
        "fiatvalue": "फ़िएट मूल्य",
        "fiatvalueon": "फ़िएट मूल्य दिनांक",
        "receivingaddress": "प्राप्तकर्ता पता",
        "fallbackaddress": "फ़ॉलबैक पता",
        "paymentid": "Payment ID",
        "integratedaddress": "इंटीग्रेटेड पता",
        "network": "नेटवर्क",
        "incoming": "आने वाला",
        "outgoing": "जाने वाला",
        "point of sale": "पॉइंट ऑफ़ सेल",
        "online purchase": "ऑनलाइन खरीद",
        "transactions": "लेनदेन",
        "viewon": "देखें",
        "source": "स्रोत",
        "deleterequest": "अनुरोध हटाएँ",

        // REQUEST PANEL
        "sharerequest": "अनुरोध साझा करें",
        "openwallet": "वॉलेट खोलें",
        "whatsyourname": "आपका नाम क्या है?",
        "whatsitfor": "यह किसलिए है?",
        "forexample": "उदा.",
        "send": "भेजें",
        "to": "को",
        "nodetection": "कोई भुगतान नहीं मिला",
        "lookuppayment": data.blockexplorer + " पर हाल के " + data.currency + " भुगतान खोजें",
        "dontshowagain": "दोबारा न दिखाएँ",
        "dismiss": "बंद करें",
        "activateintegrated": "इंटीग्रेटेड पते सक्रिय करें",
        "pendingrequest": "लंबित अनुरोध",
        "paymentsent": "भुगतान भेजा गया",
        "paymentreceived": "भुगतान प्राप्त हुआ",
        "txbroadcasted": "लेनदेन प्रसारित",
        "insufficientamount": "अपर्याप्त राशि",
        "txexpired": "अनुरोध समाप्त",
        "viewdetails": "विवरण देखें",
        "showqr": "QR कोड दिखाएँ",
        "waitingfor": "प्रतीक्षा",
        "unconfirmedtx": "अपुष्ट लेनदेन",
        "amountshort": "कम",
        "sharelocktitle": "अनुरोध अस्थायी रूप से साझा नहीं किया जा सकता।",
        "sharelockttext": "इस पते पर एक <span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>लंबित साझा अनुरोध</span> है।",
        "waitforconfirm": "कृपया पता दोबारा उपयोग करने से पहले लेनदेन की पुष्टि की प्रतीक्षा करें।",
        "pickanotheraddress": "दूसरा पता चुनें:",
        // ** request suggestion placeholders ** //
        "lunch": "दोपहर का खाना",
        "festivaltickets": "फेस्टिवल टिकट",
        "coffee": "कॉफ़ी",
        "present": "उपहार",
        "snowboarding": "स्नोबोर्डिंग",
        "movietheater": "सिनेमा",
        "shopping": "शॉपिंग",
        "videogame": "वीडियो गेम",
        "drinks": "ड्रिंक्स",
        "concerttickets": "कॉन्सर्ट टिकट",
        "camping": "कैम्पिंग",
        "taxi": "टैक्सी",
        "zoo": "चिड़ियाघर",
        // notifications
        "failedhistoric": "ऐतिहासिक " + data.ccsymbol + " मूल्य डेटा प्राप्त नहीं हो सका",
        "closingsockets": "कनेक्शन बंद हो रहे हैं...",
        "nowriteaccess": "LNurl प्रॉक्सी पहुँच अस्वीकृत, फ़ोल्डर अनुमतियाँ जाँचें",
        "notmonitored": "इस पते की निगरानी नहीं हो रही",
        "lnoffline": "Lightning नोड ऑफ़लाइन है",
        "addlightningnode": "Lightning नोड जोड़ें",
        "addressinuse": "पता उपयोग में है",
        "minimal2": "विवरण कम से कम 2 अक्षरों का होना चाहिए",
        "minimal3": "नाम कम से कम 3 अक्षरों का होना चाहिए",
        "checkyourform": "कृपया अपना फ़ॉर्म जाँचें",
        "entertitle": "कृपया विवरण दर्ज करें",
        "latincharacters": "केवल अक्षर (A-Z), संख्याएँ और चिह्न अनुमत हैं",
        "successshare": "सफलतापूर्वक साझा किया गया!",
        // confirm
        "opencoinsettings": data.currency + " सेटिंग्स खोलें?",
        "viewpendingrequest": "लंबित अनुरोध देखें?",
        "useinstead": "'" + data.thisinputvalue + "' का उपयोग करें?",
        "generatenewaddress": "क्या आप नया " + data.currency + " पता बनाना चाहते हैं? यह कुछ वॉलेट में नहीं दिख सकता",
        // dialog
        "undefinedaddress": "अपरिभाषित पता, कृपया नया अनुरोध करें",
        "invalidaddress": "अमान्य " + data.payment + " पता",

        // SHARE REQUEST
        "share": "साझा करें",
        "sharetitlename": (data.requestname === "Bitrequest") ? "नमस्ते, मैंने '" + data.requesttitle + "' के लिए " + data.amount + " " + data.uoa + " का " + data.pagenameccparam + " Bitrequest अनुरोध बनाया है" : data.requestname + " ने '" + data.requesttitle + "' के लिए " + data.amount + " " + data.uoa + " का " + data.pagenameccparam + " Bitrequest अनुरोध भेजा है",
        "sharetitle": data.amount + " " + data.uoa + " का " + data.pagenameccparam + " भुगतान अनुरोध",
        "sharetitlechange": data.newccvalue + " " + data.newccsymbol + " का " + data.payment + " अनुरोध",

        // SETTINGS
        "accountsettings": "आपका नाम",
        "currencysettings": "स्थानीय फ़िएट मुद्रा",
        "entercurrency": "मुद्रा दर्ज करें",
        "setasdefault": "डिफ़ॉल्ट के रूप में सेट करें",
        "langsettings": "भाषा",
        "chooselanguage": "भाषा चुनें",
        "themesettings": "थीम",
        "choosetheme": "थीम चुनें",
        "security": "सुरक्षा",
        "pinsettings": "पिन लॉक",
        "bip39_passphrase": "गोपनीय वाक्यांश",
        "backupsecretphrase": "गोपनीय वाक्यांश का बैकअप लें",
        "missingkeywarning": "'<span class='adspan'>" + data.address + "</span>' के लिए " + data.seedstrtitle + " गायब है।<br/>क्या आप फिर भी इस पते का उपयोग करना चाहते हैं?",
        "emptyphrase": "कृपया अपना गोपनीय वाक्यांश दर्ज करें",
        "notinwordlist": data.missing_word + " शब्द सूची में नहीं है",
        "notbip39compatible": "गोपनीय वाक्यांश BIP39 संगत नहीं है",
        "mustbe12characters": "गोपनीय वाक्यांश 12 शब्दों का होना चाहिए",
        "cannotsendfunds": "Bitrequest फंड नहीं भेज सकता!",
        "importtosend": "फंड भेजने के लिए आपको अपने <span class='show_bip39 ref'>12 शब्दों के गोपनीय वाक्यांश</span> को एक BIP39 संगत वॉलेट में पुनर्स्थापित करना होगा:",
        "backup": "ऐप डेटा बैकअप",
        "backupwithgd": "Google Drive से बैकअप:",
        "nrchanges": "आपके ऐप में " + data.nr_changes + " बदलाव हैं। कृपया अपना डेटा बैकअप करें।",
        "changein": "बदलाव",
        "changesin": "बदलाव",
        "systembackup": "सिस्टम बैकअप",
        "downloadbu": "बैकअप डाउनलोड करें",
        "installlbu": "बैकअप इंस्टॉल करें",
        "restore": "ऐप डेटा पुनर्स्थापित करें",
        "restorewithgd": "Google Drive से पुनर्स्थापित करें:",
        "lastrestore": "अंतिम पुनर्स्थापना:",
        "lastbackup": "अंतिम बैकअप:",
        "restorefromfile": "फ़ाइल से पुनर्स्थापित करें",
        "differentsecretphrase": "चेतावनी: बैकअप में अलग गोपनीय वाक्यांश है।",
        "secretphrasefrombackup": "बैकअप का गोपनीय वाक्यांश",
        "currentsecretphrase": "वर्तमान गोपनीय वाक्यांश",
        "usesecretphrasefrombackup": "बैकअप का गोपनीय वाक्यांश उपयोग करें",
        "keepcurrentsecretphrase": "वर्तमान गोपनीय वाक्यांश रखें",
        "comparesecretphrases": "गोपनीय वाक्यांशों की तुलना करें",
        "csvexport": "CSV निर्यात",
        "includearchive": "आर्काइव शामिल करें",
        "includereceipt": "रसीद शामिल करें",
        "receipt": "रसीद",
        "advanced": "उन्नत",
        "url_shorten_settings": "URL शॉर्टनर",
        "shorturlnotfound": "अनुरोध नहीं मिला",
        "cmcapisettings": "क्रिप्टो मूल्य डेटा",
        "fiatapisettings": "फ़िएट मूल्य डेटा",
        "api_proxy": "API प्रॉक्सी",
        "updateproxy": "कृपया अपना प्रॉक्सी सर्वर अपडेट करें " + data.version + " > " + data.proxy_version,
        "addapiproxy": "API प्रॉक्सी जोड़ें",
        "controlyourkeys": "अपनी कुंजियाँ और अनुरोध सीमाएँ स्वयं प्रबंधित करें:",
        "proxystep1": "<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API प्रॉक्सी फ़ोल्डर</a> को अपने सर्वर पर होस्ट करें (PHP आवश्यक)।",
        "proxystep2": "'config.php' में अपनी API कुंजियाँ दर्ज करें।",
        "proxystep3": "नीचे अपना सर्वर पता दर्ज करें।",
        "addrpcproxy": "RPC प्रॉक्सी जोड़ें",
        "tryotherproxy": "अन्य प्रॉक्सी आज़माएँ",
        "apikeys": "API कुंजियाँ",
        "apicallfailed": "API कॉल विफल",
        "apididnotrespond": "API ने प्रतिक्रिया नहीं दी",
        "contactform": "संपर्क फ़ॉर्म",
        "shipping": "शिपिंग",
        "yourdetails": "ऑनलाइन खरीद के लिए आपका विवरण।",
        "permissions": "अनुमतियाँ",
        "teaminvite": "टीम आमंत्रण",
        "inviteteammembers": "अपनी ओर से अनुरोध करने के लिए टीम सदस्यों (कर्मचारी आदि) को आमंत्रित करें।",
        "teaminviteexplainer": "यह आपके टीम सदस्य के उपकरण पर Bitrequest इंस्टॉल करेगा, आपकी सार्वजनिक कुंजियों और प्रतिबंधित पहुँच (कैशियर) के साथ।",
        "teaminviteaccess": "आपके टीम सदस्य फंड या सेटिंग्स तक नहीं पहुँच सकते।",
        "teaminviteharetitle": data.accountname + " की ओर से Bitrequest टीम आमंत्रण",
        "teamupdate": "टीम अपडेट",
        "invitationexpiresin": "आमंत्रण समाप्त होगा",
        "installcompleted": "इंस्टॉलेशन पहले ही पूर्ण!",
        "teamup": data.account + " आपके साथ मिलकर अनुरोध बनाना चाहते हैं!",
        "teamupdata": data.account + " चाहते हैं कि आप Bitrequest को उनकी नवीनतम सार्वजनिक कुंजियों से अपडेट करें",
        "clickinstall": "इंस्टॉल पर क्लिक करने से Bitrequest आपके उपकरण पर " + data.account + " की सार्वजनिक कुंजियों और प्रतिबंधित पहुँच के साथ इंस्टॉल होगा।",
        // notifications
        "nameisrequired": "नाम आवश्यक है",
        "currencysaved": "मुद्रा सहेजी गई",
        "currencynotsupported": "मुद्रा '" + data.currency + "' समर्थित नहीं है",
        "noiosbu": "iOS ऐप डाउनलोड अभी उपलब्ध नहीं",
        "downloaded": data.file + " डाउनलोड हुआ",
        "filesize": "फ़ाइल बहुत बड़ी",
        "filetype": "फ़ाइल प्रकार '" + data.filetype + "' समर्थित नहीं है",
        "selectbackup": "बैकअप फ़ाइल चुनें",
        "unauthorized": "अनधिकृत",
        "maxattempts": "अधिकतम प्रयास पार",
        "fourdigitpin": "अपना 4 अंकों का पिन दर्ज करें",
        "wrongpin": "गलत पिन",
        "nocsvexports": "निर्यात के लिए कोई अनुरोध नहीं",
        "validateapikey": "एक मान्य API कुंजी दर्ज करें",
        "unabletopost": data.fixed_url + " से Post अनुरोध नहीं भेजा जा सका",
        "invalidapikey": "अमान्य API कुंजी",
        "apicallerror": "API कॉल त्रुटि",
        "invalidapikeyname": "अमान्य " + data.thisref + " API कुंजी",
        "addapikey": data.apisrc + " API कुंजी जोड़ें",
        "phname": "नाम",
        "phaddress": "पता",
        "phzipcode": "पिन कोड",
        "phcity": "शहर",
        "phcountry": "देश",
        "phemail": "ईमेल",
        "invalidchars": "में अमान्य अक्षर हैं",
        "pleaseverify": "कृपया अपना गोपनीय वाक्यांश सत्यापित करें।",
        "owndevice": "अपने उपकरण पर आमंत्रण इंस्टॉल नहीं कर सकते",
        "installcomplete": "इंस्टॉलेशन पूर्ण!",
        // confirm
        "includesecretphrase": "बैकअप में एन्क्रिप्टेड गोपनीय वाक्यांश शामिल करें? सुनिश्चित करें कि आप अपनी बैकअप फ़ाइलें सुरक्षित रखें!",
        "sharebu": "सिस्टम बैकअप साझा करें?",
        "installsb": "सिस्टम बैकअप इंस्टॉल करें? सभी मौजूदा ऐप डेटा बदल दिया जाएगा",
        "downloadfile": "डाउनलोड: " + data.file + "?",
        "restorefile": "पुनर्स्थापित: " + data.file + "?",
        "restorefromdevice": data.device + " उपकरण से " + data.file + " पुनर्स्थापित करें?",
        "restorewithoutsecretphrase": "गोपनीय वाक्यांश के बिना पुनर्स्थापित करें?",
        "keepexistingsecretphrase": "क्या आप अपना मौजूदा गोपनीय वाक्यांश रखना चाहते हैं?",
        "sharecsvexport": "CSV निर्यात साझा करें?",
        "disableshorturls": "क्या आप URL शॉर्टनिंग अक्षम करना चाहते हैं? इससे ऐप का कार्यप्रवाह प्रभावित हो सकता है",
        "sendinvite": "आमंत्रण भेजें",
        "updatealert": "अपडेट करें? आपकी सभी सार्वजनिक कुंजियाँ अपडेट हो जाएँगी।",
        "installalert": "इंस्टॉल करें? आपकी सभी सार्वजनिक कुंजियाँ बदल दी जाएँगी।",

        // COIN SETTINGS
        "confirmations": "पुष्टिकरण",
        "showsatoshis": "सतोशी दिखाएँ",
        "Use random address": "यादृच्छिक पता उपयोग करें",
        "Share viewkey": "Viewkey साझा करें",
        "Integrated addresses": "इंटीग्रेटेड पते",
        "Reuse address": "पता पुन: उपयोग करें",
        "blockexplorers": "Blockexplorer",
        "chooseblockexplorer": "Blockexplorer चुनें",
        "apis": "APIs",
        "addapi": data.h_hint + " RPC जोड़ें:",
        "websockets": "Websockets",
        "addwebsocket": data.h_hint + " Websocket जोड़ें:",
        "layer2": "Layer 2",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32 विस्तारित सार्वजनिक कुंजी",
        "addxpub": data.currency + " Xpub कुंजी जोड़ें",
        "xpubmatch": "ऊपर के पते मेरे " + data.currency + " वॉलेट से मेल खाते हैं।",
        "xpubkeys": "मेरे पास गोपनीय वाक्यांश / Xpriv कुंजी है",
        "Key derivations": "कुंजी व्युत्पन्न",
        "derivationpath": "व्युत्पन्न पथ",
        "soundbytes": "ध्वनि",
        "choosesoundbytes": "ध्वनि चुनें",
        "resetbutton": "रीसेट",
        // notifications
        "unabletoconnect": "कनेक्ट नहीं हो सका",
        "nodealreadyadded": "नोड पहले से जोड़ा गया",
        "removedefaultnode": "डिफ़ॉल्ट नोड नहीं हटा सकते",
        "rpcnoderemoved": "RPC नोड हटाया गया",
        "confirmmatch": "पतों का मिलान पुष्ट करें",
        "confirmpkownership": "निजी कुंजी स्वामित्व की पुष्टि करें",
        "invalidxpub": "मान्य / समर्थित " + data.currency + " Xpub कुंजी नहीं है",
        "xpubsaved": "Xpub सहेजा गया",
        "resetnotify": data.currency + " सेटिंग्स डिफ़ॉल्ट पर रीसेट",
        // confirm
        "reusewarningalert": "क्या आप नए " + data.thiscurrency + " पते बनाना चाहते हैं? ये कुछ वॉलेट में नहीं दिख सकते।",
        "reusealert": "क्या आप " + data.thiscurrency + " पते पुन: उपयोग करना चाहते हैं?",
        "confirmremovenode": "क्या आप '" + data.thisval + "' हटाना चाहते हैं?",
        "disablexpub": "Xpub पता व्युत्पन्न अक्षम करें?",
        "replacexpub": "Xpub बदलें?",
        "uselegacy": data.thiscurrency + " Legacy पते उपयोग करें?",
        "usesegwit": data.thiscurrency + " SegWit पते उपयोग करें?",
        "resetconfirm": "क्या आप " + data.currency + " सेटिंग्स रीसेट करना चाहते हैं?",
        // dialog
        "resetdialog": data.currency + " सेटिंग्स रीसेट करें?",

        // LIGHTNING
        "Lightning network": "Lightning नेटवर्क",
        "lightningnode": "Lightning नोड",
        "addnode": "नोड जोड़ें",
        "implementation": "इम्प्लीमेंटेशन",
        "tabyourboldcard": "कृपया अपना Boltcard इस उपकरण के पीछे टैप करें",
        "controlyourlnkeys": "अपना Lightning नोड और कुंजियाँ स्वयं प्रबंधित करें:",
        "lnnodestep1": "<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>प्रॉक्सी फ़ोल्डर</a> को अपने वेबसर्वर पर होस्ट करें।",
        "lnnodestep2": "'config.php' में अपने Lightning नोड का REST होस्ट और कुंजियाँ दर्ज करें।",
        "lnnodestep3": "नीचे अपना सर्वर पता दर्ज करें।",
        "enterlnapikey": "'" + data.proxy + "' अनलॉक करने के लिए प्रॉक्सी API कुंजी दर्ज करें",
        "viewinvoice": "Invoice देखें",
        "noinvoicesfound": "कोई Invoice नहीं मिला।",
        "invoiceslocked": "नोड प्रॉक्सी लॉक है, Invoice प्राप्त नहीं हो सकते।<br/>कृपया अपनी प्रॉक्सी <span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>API कुंजी</span> दर्ज करें।",
        "invoiceoffline": "नोड ऑफ़लाइन, Invoice प्राप्त नहीं हो सकते।",
        // notifications
        "nodenotfound": "नोड नहीं मिला",
        "proxynotfound": "प्रॉक्सी नहीं मिली",
        "enterserver": "कृपया सर्वर पता दर्ज करें",
        "defaultproxy": data.fixed_url + " एक डिफ़ॉल्ट प्रॉक्सी है",
        "proxyexists": "प्रॉक्सी पहले से जोड़ी गई",
        "invalidurl": "अमान्य URL",
        "selectimplementation": "इम्प्लीमेंटेशन चुनें",
        "selectlnhost": data.imp + " होस्ट चुनें",
        "selectkeyname": data.impkeyname + " चुनें",
        "entermacaroon": "कृपया 'invoice' Macaroon दर्ज करें",
        "invalidkeyformat": "अमान्य कुंजी फ़ॉर्मेट",
        "proxylocked": "वर्तमान नोड प्रॉक्सी लॉक है, कृपया API कुंजी दर्ज करें",
        "proxyoffline": "वर्तमान नोड ऑफ़लाइन है, " + data.proxy_message + " प्रॉक्सी आज़माएँ",
        "folderpermissions": "कैश में लिख नहीं सका, कृपया फ़ोल्डर अनुमतियाँ जाँचें।",
        "proxyadded": "प्रॉक्सी जोड़ी गई",
        "unabletoconnectto": data.value + " से कनेक्ट नहीं हो सका",
        "proxynameexists": data.imp + " नोड पहले से जोड़ा गया",
        "proxyinuse": data.imp + ": '" + data.name + "' इस प्रॉक्सी का उपयोग करता है, पहले हटाएँ",
        "proxyremoved": "प्रॉक्सी हटाई गई",
        "serviceremoved": "सेवा हटाई गई",
        "unknownproxy": "अज्ञात प्रॉक्सी सर्वर",
        "proxyunlocked": "प्रॉक्सी अनलॉक!",
        "proxydatamissing": "प्रॉक्सी डेटा गायब",
        "invoicecanceled": "Invoice रद्द",
        // confirm
        "enablelightning": "Lightning भुगतान सक्षम करें?",
        "disablelightning": "Lightning भुगतान अक्षम करें?",
        "disableproxy": "प्रॉक्सी " + data.set_proxy_val + " अक्षम करें?",
        "enableproxy": "प्रॉक्सी " + data.set_proxy_val + " सक्षम करें?",
        // dialog
        "unabletoconnectln": "Lightning नोड से कनेक्ट नहीं हो सका",

        // BIP39
        "disclaimer": "अस्वीकरण!",
        "cannotbespend": "आपके गोपनीय वाक्यांश से बने पतों पर प्राप्त फंड Bitrequest से खर्च नहीं किए जा सकते।<br/>फंड खर्च करने के लिए अपना गोपनीय वाक्यांश एक <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>संगत वॉलेट</a> में पुनर्स्थापित करें।",
        "compatiblewallets": "संगत वॉलेट",
        "important": "महत्वपूर्ण!",
        "abouttobecome": "आप अपना खुद का बैंक बनने वाले हैं।",
        "inthenextscreen": "अगली स्क्रीन में आपको अपना गोपनीय वाक्यांश दिखेगा।",
        "makesure": "इसे लिख लें और सुरक्षित जगह रखें!",
        "understandandok": "मैं समझता/समझती हूँ और सहमत हूँ।",
        "entersecretphrase": "अपना गोपनीय वाक्यांश दर्ज करें:",
        "writedownsecretphrase": "अपना गोपनीय वाक्यांश लिखें और सुरक्षित रखें।",
        "ifyouloseyourphrase": "अगर आप अपना वाक्यांश खो देते हैं,<br/>तो आप अपना धन खो देंगे!",
        "understand": "मैं समझता/समझती हूँ!",
        "verifycurrent": "वर्तमान गोपनीय वाक्यांश सत्यापित करें:",
        "verifybackup": "बैकअप सत्यापित करें:",
        "withgreatpower": "बड़ी शक्ति के साथ बड़ी जिम्मेदारी आती है।",
        "remember": "अपने <span id='toseed'>गोपनीय वाक्यांश</span> का बैकअप लेना न भूलें।",
        "overwritten": "अपने वर्तमान <span id='toseed'>गोपनीय वाक्यांश</span> का बैकअप लें। यह ओवरराइट हो जाएगा",
        "word": "शब्द",
        "idothislater": "मैं यह बाद में करूँगा/करूँगी",
        "ivebackeditup": "मैंने बैकअप ले लिया है!",
        "next": "अगला",
        "prev": "पिछला",
        "findmorewallets": "और वॉलेट खोजें",
        // notifications
        "alreadyhavesecretphrase": "आपके पास पहले से गोपनीय वाक्यांश है",
        "wrongsecretphrase": "गलत गोपनीय वाक्यांश",
        "consent": "जारी रखने के लिए कृपया सहमति दें।",
        "secretphrasedeleted": "गोपनीय वाक्यांश हटाया गया",
        "congratulations": "बधाई हो! अब आप अपने खुद के बैंक हैं!",
        "passphraseverified": "वाक्यांश सत्यापित",
        "backupasap": "कृपया जल्द से जल्द अपने गोपनीय वाक्यांश का बैकअप लें",
        // confirm
        "resoresecretphrase": "गोपनीय वाक्यांश पुनर्स्थापित करें",
        "areyousuredfp": "क्या आप अपना गोपनीय वाक्यांश हटाना चाहते हैं?",
        "restoresecretphrasefrombackup": "क्या आप बैकअप से गोपनीय वाक्यांश पुनर्स्थापित करना चाहते हैं? वर्तमान वाक्यांश मिटा दिया जाएगा।",
        // dialog
        "continueatownrisk": "चेतावनी! अपने जोखिम पर जारी रखें।",
        "ifyouloseyourdevice": "अगर आप अपना उपकरण खो देते हैं, ऐप अनइंस्टॉल करते हैं या ब्राउज़र डेटा हटाते हैं, तो फंड वापस पाने के लिए आपको गोपनीय वाक्यांश चाहिए!",
        "deletingyoursecretphrase": "चेतावनी! गोपनीय वाक्यांश हटाने से फंड का नुकसान हो सकता है।",
        "continuewithbackup": "केवल तभी जारी रखें जब आपके पास गोपनीय वाक्यांश का बैकअप हो।",

        // SOCKETS
        // notifications
        "youareoffline": "आप वर्तमान में ऑफ़लाइन हैं",
        "networks": "नेटवर्क",
        "acceptthepayment": "अपने Lightning ऐप में भुगतान स्वीकार करें...",
        "ndeftablimit": "बहुत तेज़ टैप किया",
        "enteramount": "कृपया राशि दर्ज करें",
        "cardmax": "अनुरोध कार्ड की अधिकतम सीमा से अधिक",
        "minamount": "न्यूनतम अनुरोध राशि " + data.min + " है",
        "waitingforpayment": "भुगतान की प्रतीक्षा",
        "websocketoffline": "नोड ऑफ़लाइन",

        // PIN PANEL
        "pleaseenter": "कृपया अपना पिन दर्ज करें",
        "createpin": "4 अंकों का पिन बनाएँ",
        "locktime": "लॉक समय",
        "resetpin": "पिन रीसेट करें",
        "enternewpin": "नया पिन दर्ज करें",
        "minute": "मिनट",
        "minutes": "मिनट",
        "never": "कभी नहीं",
        "pincodeactivated": "पिन सक्रिय",
        "pincodedisabled": "पिन अक्षम",
        "confirmyourpin": "अपना पिन पुष्ट करें",

        // LOCKSCREEN
        "unlockwithsecretphrase": "गोपनीय वाक्यांश से अनलॉक करें",
        "tomanyunlocks": "बहुत अधिक अनलॉक प्रयास",
        "enter12words": "अपने 12 शब्दों का<br/>गोपनीय वाक्यांश दर्ज करें:",
        "tryagainin": "कृपया पुनः प्रयास करें",
        "unlock": "अनलॉक",

        // BUTTONS AND PANELS
        "cancelbttn": "रद्द करें",
        "okbttn": "ठीक है",
        "show": "दिखाएँ",
        "hide": "छुपाएँ",
        "delete": "हटाएँ",
        "restorebttn": "पुनर्स्थापित",
        "showtransactions": "लेनदेन दिखाएँ",
        "sharerequestbutton": "अनुरोध साझा करें",
        "addcoinaddress": data.currency + " पता जोड़ें",
        "generatewallet": "गोपनीय वाक्यांश से वॉलेट बनाएँ।",
        "pkownership": "मेरे पास इस पते की निजी कुंजी है।",
        "nopub": "पता / Xpub",
        "update": "अपडेट",
        "install": "इंस्टॉल",
        "pay": "भुगतान",

        //DIALOGS
        "totalchanges": "आपके ऐप में " + data.total_changes + " बदलाव हैं",
        "nochanges": "आपके ऐप में 0 बदलाव हैं",
        "havewallet": "क्या आपके उपकरण पर " + data.lnd_ref + " वॉलेट है?",

        // DATES
        "sunday": "रविवार",
        "monday": "सोमवार",
        "tuesday": "मंगलवार",
        "wednesday": "बुधवार",
        "thursday": "गुरुवार",
        "friday": "शुक्रवार",
        "saturday": "शनिवार",
        "year": "वर्ष",
        "years": "वर्ष",
        "month": "महीना",
        "months": "महीने",
        "week": "सप्ताह",
        "weeks": "सप्ताह",
        "day": "दिन",
        "days": "दिन",
        "hour": "घंटा",
        "hours": "घंटे",
        "minute": "मिनट",
        "minutes": "मिनट",
        "seconds": "सेकंड",
        "and": "और",
        "expiresin": "समाप्त होगा ",
        "fileexpired": "फ़ाइल समाप्त",

        // LOADERTEXT
        "generatereceipt": "रसीद बनाई जा रही है",
        "connecttolnur": data.url + " से कनेक्ट हो रहा है",
        "loadurl": data.url + " लोड हो रहा है",
        "loading": "लोड हो रहा है...",
        "gettokeninfo": "टोकन जानकारी प्राप्त करें",
        "checklightningstatus": data.imp + " Lightning स्थिति जाँचें",
        "readingfromcache": "कैश से " + data.ccsymbol + " दर पढ़ रहा है",
        "getccrates": data.api + " से " + data.ccsymbol + " दरें प्राप्त करें",
        "getfiatrates": "फ़िएट दरें प्राप्त करें",
        "readingfiatratesfromcache": "कैश से फ़िएट दरें पढ़ रहा है",
        "fetchingfiatrates": data.fiatapi + " से फ़िएट दरें प्राप्त हो रही हैं",
        "generatelink": "लिंक बनाया जा रहा है",
        "loadingcamera": "कैमरा लोड हो रहा है",
        "generatebu": "सिस्टम बैकअप बनाएँ",
        "installationpackage": "इंस्टॉलेशन पैकेज बनाएँ",

        // RANDOM TERMS
        "address": "पता",
        "choose": "चुनें",
        "enable": "सक्षम",
        "disable": "अक्षम",
        "apikey": "API कुंजी",
        "yes": "हाँ",
        "no": "नहीं",
        "none": "कोई नहीं",
        "verified": "सत्यापित",
        "error": "त्रुटि",
        "apierror": "API त्रुटि",
        "success": "सफल",
        "warning": "चेतावनी!",
        "edit": "संपादित करें",
        "enter": "दर्ज करें",

        // CHECK INTENTS
        "proto": data.proto + ": कनेक्शन अभी उपलब्ध नहीं",
        "invalidurlscheme": "अमान्य URL स्कीम",
        "usnotsupported": "URL स्कीम '" + data.proto + ":' समर्थित नहीं है",

        // GOOGLE AUTH
        "stopgauth": "Google Drive बैकअप बंद करें।",
        "gauthsafely": "अपना ऐप डेटा सुरक्षित रूप से बैकअप करें।",
        "gauthsync": "Google Drive के साथ अपना डेटा सुरक्षित रूप से सिंक करें।",
        "signin": "साइन इन",
        "backuptogd": "Google Drive पर बैकअप करें",
        // notifications
        "ganot": "GoogleAuth उपलब्ध नहीं",
        "gdsignedin": "सफलतापूर्वक साइन इन",
        "gdsignedout": "सफलतापूर्वक साइन आउट",
        "filedeleted": "फ़ाइल हटाई गई",
        "filenotfound": "फ़ाइल नहीं मिली",
        // confirm
        "stopgdalert": "क्या आप Google Drive बैकअप बंद करना चाहते हैं?",
        "deletefile": data.file + " हटाएँ?"
    }
    return translation[id];
}
