// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"nl": {
    "lang": "Dutch",
    "obj": lang_nl(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_nl(id, data) {
    const translation = {
        "payoff": "Accepteer crypto overal",

        // PAGES
        "home": "home",
        "currencies": "cryptos",
        "requests": "betaalverzoekjes",
        "settings": "instellingen",
        "coinsettings": "coin instellingen",
        "addresses": "adressen",

        // INTRO
        "enteryourname": "Voer uw naam in",
        "iwouldliketogetpaid": "Ik wil graag betaald worden in:",
        "more": "Meer",
        "restorefrombackup": "Herstel van backup",

        // CORE
        // notifications
        "datasaved": "Data opgeslagen",
        "pinmatch": "pincode komt niet overeen",
        "xratesx": "Niet in staat om koersen op te vragen",
        "entercoinaddress": "Voer een " + data.currency + " adres in.",
        "errorvk": "Fout verificatie Viewkey",
        "invalidvk": "Ongeldige Viewkey",
        "novalidaddress": "is geen geldig " + data.currency + " adres.",
        "pickacurrency": "Kies een currency",
        "invalidlabel": "Ongeldig label",
        "noactivecurrencies": "Geen active currencies",
        "addressremoved": "Address verwijderd",
        "movedtoarchive": "Verplaatst naar archief",
        "requestrestored": "Betaalverzoek hersteld",
        "requestdeleted": "Request verwijderd",
        "requestsaved": "Betaalverzoek opgeslagen",
        "requiredfields": "Voeg de verpichte velden in",
        "requiredfield": "is een verplicht veld",
        "nofetchincoice": "Niet in staat om invoices op te halen.",
        "copy": "Kopieer",
        "copied": "gekopieerd naar klembord",
        "xcopy": "Niet gekopieerd!",
        "cashiernotallowed": "Niet toegestaan in cashier mode",
        "decodeqr": "Niet in staat om qr te decoderen",
        "invalidformat": "Ongeldig formaat",
        "invalidmacaroon": "Ongeldig macaroon formaat",
        "recentrequests": "Recente verzoeken",
        "encodeyoraddress": "Codeer je adres op bitrequest.io/qr",
        // confirm
        "openurl": "Open " + data.url + "?",
        "showrequestsfor": "Toon betaalverzoeken voor " + data.address + "?",
        "areyousure": "Weet je het zeker?",
        "openinvoice": "Open invoice: " + data.hash + "?",
        "sharefile": "Deel " + data.filename + "?",
        // dialog
        "nofetchtokeninfo": "Niet in staat om token info op te halen.",
        "archiverequest": "Archiveer betaalverzoek?",
        "unarchiverequest": "Zet betaalverzoek terug?",
        "failedtofetchrequest": "Kan request niet ophalen",
        "downloadwallet": "Download " + data.currency + " wallet",

        // ADD ADDRESS
        "alreadyexists": "address bestaat al",
        "addaddress": "Voeg adres toe",
        "adderc20token": "Voeg erc20 toe",
        "erc20placeholder": "Kies erc20 token",
        "enteraddress": "Voer adres in",
        "noaddressyet": "Ik heb nog geen " + data.currency + " adres",

        // ADDRESS INFO
        "showrequests": "Toon verzoeken",
        "newrequest": "Nieuw verzoek",
        "addressinfo": "Adres info",
        "editlabel": "Bewerk label",
        "removeaddress": "Verwijder adres",
        "recentpayments": "Recente betalingen",
        "privatekey": "Private key",
        "secretviewkey": "Secret view key",
        "secretspendkey": "Secret spend key",

        // REQUEST INFO
        "currency": "Crypto",
        "from": "Verzender",
        "title": "Omschrijving",
        "amount": "Bedrag",
        "status": "Status",
        "Waiting for payment": "In afwachting",
        "paid": "Betaald",
        "insufficient": "Onvoldoende",
        "new": "Nieuw",
        "pending": "In behandeling",
        "expired": "verlopen",
        "type": "Type",
        "created": "Aangemaakt op",
        "firstviewed": "Voor het eerst bekeken",
        "sendon": "Verzoek verstuurd op",
        "paidon": "Betaald op",
        "amountreceived": "Ontvangen bedrag",
        "fiatvalue": "Fiat waarde",
        "fiatvalueon": "Fiat waarde op",
        "receivingaddress": "Ontvangst adres",
        "fallbackaddress": "Onchain adres",
        "paymentid": "Payment ID",
        "integratedaddress": "Geintegreerd adres",
        "network": "Netwerk",
        "incoming": "Inkomend",
        "outgoing": "Uitgaand",
        "point of sale": "Verkooppunt (POS)",
        "online purchase": "Online aankoop",
        "transactions": "Transacties",
        "viewon": "Bekijk op",
        "source": "Bron",
        "deleterequest": "Verwijder request",

        // REQUEST PANEL
        "sharerequest": "Betaalverzoekje",
        "openwallet": "Open wallet",
        "whatsyourname": "Naam:",
        "whatsitfor": "Omschrijving:",
        "forexample": "bv",
        "send": "Verstuur",
        "to": "naar",
        "nodetection": "Geen betaling gedetecteerd",
        "lookuppayment": "<a href='" + data.bu_url + "' target='_blank' class='ref check_recent'>Kijk voor recente inkomende " + data.currency + " betalingen op " + data.blockexplorer + " <span class='icon-new-tab'></a>",
        "dontshowagain": "Toon deze melding niet meer",
        "dismiss": "negeer",
        "activateintegrated": "Activate geïntegreerde adressen",
        "pendingrequest": "Betaling in behandeling",
        "paymentsent": "Betaling verstuurd",
        "paymentreceived": "Betaling ontvangen",
        "txbroadcasted": "Transactie verzonden",
        "insufficientamount": "Onvoldoende bedrag",
        "txexpired": "Betaalverzoek verlopen",
        "viewdetails": "Bekijk details",
        "showqr": "Toon qr-code",
        "waitingfor": "Wachtend op",
        "unconfirmedtx": "Onbevestigde transactie",
        "amountshort": "te kort",
        "sharelocktitle": "Betaalverzoekje op dit adres is tijdelijk niet mogelijk.",
        "sharelockttext": "Dit adres heeft een <span id='view_pending_tx' data-requestid='" + data.pending_requestid + "'>betaalverzoek in behandeling</span>.",
        "waitforconfirm": "Wacht aub tot de transactie is bevestigd zodat u dit adres opnieuw kunt gebruiken.",
        "pickanotheraddress": "Kies een ander adres:",
        // ** request suggestion placeholders ** //
        "lunch": "Lunch",
        "festivaltickets": "Festival kaartjes",
        "coffee": "Koffie",
        "present": "Kado",
        "snowboarding": "Snowboarding",
        "movietheater": "Bioscoop",
        "shopping": "Winkelen",
        "videogame": "Video game",
        "drinks": "Drankjes",
        "concerttickets": "Concert kaartjes",
        "camping": "Kamperen",
        "taxi": "Taxi",
        "zoo": "Dierentuin",
        // notifications
        "failedhistoric": "Kan " + data.ccsymbol + " historische prijs data niet ophalen",
        "closingsockets": "Verbinding aan het verbreken...",
        "nowriteaccess": "LNurl proxy toegang geweigerd, controleer uw folder permissies",
        "notmonitored": "Dit adres wordt niet gemonitoord",
        "lnoffline": "Lightning node is offline",
        "addlightningnode": "Voeg lightning node toe",
        "addressinuse": "Adres in gebruik",
        "minimal2": "Omschrijving moet minimaal 2 karakters bevatten",
        "minimal3": "Naam moet minimaal 3 karakters bevatten",
        "checkyourform": "Controleer uw formulier",
        "entertitle": "Voeg een omschrijving toe",
        "successshare": "Succesvol gedeeld!",
        // confirm
        "opencoinsettings": "Open " + data.currency + " instellingen?",
        "viewpendingrequest": "Bekijk uitgaand verzoek?",
        "useinstead": "Gebruik '" + data.thisinputvalue + "' in de plaats?",
        "generatenewaddress": "Weet je zeker dat je een nieuw " + data.currency + " adres wilt aanmaken? Het kan zijn dat deze niet wordt ondersteund door sommige wallets",
        // dialog
        "undefinedaddress": "Ongeldig adres, vraag om een nieuw betaalverzoek",
        "invalidaddress": "Ongeldig " + data.payment + " adres",

        // SHARE REQUEST
        "share": "deel",
        "sharetitlename": data.requestname + " heeft een " + data.pagenameccparam + " betaalverzoek van " + data.amount + " " + data.uoa + " gestuurd voor '" + data.requesttitle + "'",
        "sharetitle": data.pagenameccparam + " betaalverzoek van " + data.amount + " " + data.uoa,
        "sharetitlechange": data.payment + " betaalverzoek voor " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "Naam",
        "currencysettings": "Lokale Fiat valuta",
        "entercurrency": "Kies valuta",
        "setasdefault": "Stel in als standaard",
        "langsettings": "Taal",
        "chooselanguage": "Kies een taal",
        "security": "Beveiliging",
        "pinsettings": "Pincode vergrendeling",
        "bip39_passphrase": "Geheime zin",
        "backupsecretphrase": "Backup geheime zin",
        "missingkeywarning": data.seedstrtitle + " voor '<span class='adspan'>" + data.address + "</span>' ontbreekt.<br/>Weet je zeker dat je dit adres wilt gebruiken?",
        "emptyphrase": "Voer uw geheime zin in",
        "notinwordlist": data.missing_word + " staat niet in de bip39 woordenlijst",
        "notbip39compatible": "Geheime zin voldoet niet aan de Bip39 standaard",
        "mustbe12characters": "Geheime zin moet 12 woorden bevatten",
        "cannotsendfunds": "Bitrequest kan helaas geen crypto verturen!",
        "importtosend": "Om crypto te versturen zul je je <span class='show_bip39 ref'>12 woordige geheime zin</span> moeten importeren in een bip39 compatible wallet:",
        "backup": "Backup App data",
        "backupwithgd": "Backup met Google Drive:",
        "nrchanges": "Je hebt " + data.nr_changes + " aanpassingen in je app. Maak een backup van je app data.",
        "changein": "aanpassing in",
        "changesin": "aanpassingen in",
        "systembackup": "Systeem Backup",
        "downloadbu": "download backup",
        "installlbu": "installeer backup",
        "restore": "Herstel App data",
        "restorewithgd": "Herstel van Google Drive:",
        "lastrestore": "Laatste herstel:",
        "lastbackup": "Laatste backup:",
        "restorefromfile": "Herstel met bestand",
        "differentsecretphrase": "Waarschuwing. Backup bevat een andere geheime zin.",
        "secretphrasefrombackup": "Geheime zin uit backup",
        "currentsecretphrase": "Huidige geheime zin",
        "usesecretphrasefrombackup": "Gebruik geheime zin uit backup",
        "keepcurrentsecretphrase": "Behoud huidige geheime zin",
        "comparesecretphrases": "Vergelijk",
        "csvexport": "Exporteer CSV bestand",
        "includearchive": "Includeer archief",
        "includereceipt": "Includeer afschrift",
        "receipt": "Afschrift",
        "advanced": "Geavanceerd",
        "url_shorten_settings": "URL inkorter",
        "shorturlnotfound": "Verzoek verlopen of niet gevonden",
        "cmcapisettings": "Cryptocurrency prijs data",
        "fiatapisettings": "FIAT prijs data",
        "api_proxy": "API Proxy",
        "updateproxy": "Update uw proxy server " + data.version + " > " + data.proxy_version,
        "addapiproxy": "Voeg API proxy toe",
        "controlyourkeys": "Beheer je eigen API sleutels en verzoek limieten:",
        "proxystep1": "Host de <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API proxy folder</a> op je server (php vereist).",
        "proxystep2": "Vul je API sleutels in 'config.php'.",
        "proxystep3": "Voer je server adres hieronder in.",
        "addrpcproxy": "Voeg RPC proxy toe",
        "tryotherproxy": "Probeer andere proxy",
        "apikeys": "API sleutels",
        "apicallfailed": "Api call mislukt",
        "apididnotrespond": "Api reageert niet",
        "contactform": "Contactformulier",
        "shipping": "verzenden",
        "yourdetails": "Uw details voor online aankopen.",
        "permissions": "Bevoegdheden",
        "teaminvite": "Team uitnodiging",
        "inviteteammembers": "Nodig teamgenoten uit (personeel, vrienden etc.) om betaalverzoeken voor jou te maken.",
        "teaminviteexplainer": "Bitrequest zal worden geïnstalleerd op het apparaat van je teamgenoot met jou publieke sleutels en beperkte toegang (cashier).",
        "teaminviteaccess": "Je teamgenoten hebben geen toegang tot jou cryptos en kunnen geen aanpassingen maken.",
        "teaminviteharetitle": "Bitrequest Team uitnodiging van " + data.accountname,
        "teamupdate": "Team update",
        "invitationexpiresin": "Uitnodiging verloopt over",
        "installcompleted": "Installatie reeds uitgevoerd!",
        "teamup": data.account + " wil samen met jou crypto betalingen ontvangen!",
        "teamupdata": data.account + " wil dat je bitrequest update met nieuwe publieke sleutels",
        "clickinstall": "Door op 'installeren' te klikken zal bitrequest op jou apparaat worden geïnstalleerd met " + data.account + "'s publieke sleutels en beperkte toegang.",
        // notifications
        "nameisrequired": "Naam is verplicht",
        "currencysaved": "Valuta opgeslagen",
        "currencynotsupported": data.currency + "' wordt niet ondersteund",
        "noiosbu": "Downloads voor IOS App zijn momenteel niet beschikbaar",
        "downloaded": "Downloaded: " + data.file,
        "filesize": "Bestand te groot",
        "filetype": "Bestandstype '" + data.filetype + "' niet ondersteund",
        "selectbackup": "Selecteer een Backup bestand",
        "unauthorized": "Ongeautoriseerd",
        "maxattempts": "Maximaal aantal pogingen overschreden",
        "fourdigitpin": "Voer uw 4 cijferige pincode in",
        "wrongpin": "Verkeerde pincode",
        "nocsvexports": "Geen betaalverzoeken om te exporteren",
        "validateapikey": "Voer een geldige API sleutel in",
        "unabletopost": "Niet in staat om Post verzoeken te sturen vanaf " + data.fixed_url,
        "invalidapikey": "Ongeldige API sleutel",
        "apicallerror": "Fout bij het aanroepen van API",
        "invalidapikeyname": "Ongeldige " + data.thisref + " API sleutel",
        "addapikey": "Gebruik " + data.apisrc + " Api sleutel",
        "phname": "Naam",
        "phaddress": "Adres",
        "phzipcode": "Postcode",
        "phcity": "Woonplaats",
        "phcountry": "Land",
        "phemail": "email",
        "invalidchars": "is ongeldig",
        "pleaseverify": "Verifieer alstublieft uw geheime zin.",
        "owndevice": "Uitnodiging kan niet worden geïnstalleerd op je eigen apparaat",
        "installcomplete": "Installatie compleet!",
        // confirm
        "includesecretphrase": "Backup je versleutelde geheime zin? Zorg er voor dat je je backup file niet kwijt raakt!",
        "sharebu": "Deel systeem backup?",
        "installsb": "INSTALLEER SYSTEEM BACKUP? AL JE HUIDIGE DATA ZAL WORDEN VEVANGEN",
        "downloadfile": "Download: " + data.file + "?",
        "restorefile": "Herstel: " + data.file + "?",
        "restorefromdevice": "Herstel " + data.file + " van " + data.device + " apparaat?",
        "restorewithoutsecretphrase": "Herstel zonder geheime zin?",
        "keepexistingsecretphrase": "Weet je zeker dat je je huidige geheime zin wilt behouden?",
        "sharecsvexport": "Deel csv bestand?",
        "disableshorturls": "Weet je zeker dat je URL inkorters wilt uischakelen? Dit kan invloed hebben op de workflow van je app.",
        "sendinvite": "Stuur uitnodiging",
        "updatealert": "Update? Al je huidige publieke sleutels zullen worden geupdate.",
        "installalert": "Installeren? Al je huidige publieke sleutels zullen worden vervangen.",

        // COIN SETTINGS
        "confirmations": "Bevestigingen",
        "showsatoshis": "Toon satoshis",
        "Use random address": "Gebruik willekeurig adres",
        "Share viewkey": "Deel viewkey",
        "Integrated addresses": "Geintegreerde adressen",
        "Reuse address": "Hergebruik adressen",
        "blockexplorers": "Blockexplorers",
        "chooseblockexplorer": "Kies Blockexplorer",
        "apis": "APIs",
        "addapi": "Voeg " + data.h_hint + " RPC toe:",
        "websockets": "Websockets",
        "addwebsocket": "Voeg " + data.h_hint + " websocket toe:",
        "layer2": "Layer 2",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32 Extended public key",
        "addxpub": "Voeg " + data.currency + " Xpub sleutel toe",
        "xpubmatch": "De bovenstaande adressen komen overeen met mijn " + data.currency + " wallet.",
        "xpubkeys": "Ik ben in het bezit van de geheime zin / Xpriv sleutel.",
        "Key derivations": "Key derivations",
        "derivationpath": "Derivation path",
        "resetbutton": "reset",
        // notifications
        "unabletoconnect": "Niet in staat om te verbinden",
        "nodealreadyadded": "Node reeds toegevoegd",
        "removedefaultnode": "Standaard node kan niet verwijderd worden",
        "rpcnoderemoved": "RPC node verwijderd",
        "confirmmatch": "Bevestig dat de adressen overeenkomen.",
        "confirmpkownership": "Bevestig dat u in bezit bent van de private key.",
        "invalidxpub": "Ongeldige / niet ondersteunde " + data.currency + " Xpub sleutel.",
        "xpubsaved": "Xpub opgeslagen",
        "resetnotify": data.currency + " instellingen hersteld naar standaard",
        // confirm
        "reusewarningalert": "Weet je zeker dat je nieuwe adressen wilt genereren voor " + data.thiscurrency + ". Mogelijk zijn deze niet zichtbaar in sommige wallets.",
        "reusealert": "Weet je zeker dat je adressen wilt hergebruiken voor " + data.thiscurrency + "?",
        "confirmremovenode": "Weet je zeker dat je '" + data.thisval + "' wilt verwijderen?",
        "disablexpub": "Deactiveer Xpub adressen?",
        "replacexpub": "Vervang Xpub?",
        "uselegacy": "Gebruik " + data.thiscurrency + " Legacy adressen?",
        "usesegwit": "Gebruik " + data.thiscurrency + " SegWit adressen?",
        "resetconfirm": "Weet je zeker dat je de " + data.currency + " instellingen wilt herstellen?",
        // dialog
        "resetdialog": "Herstel " + data.currency + " instellingen?",

        // LIGHTNING
        "Lightning network": "Lightning netwerk",
        "lightningnode": "lightning node",
        "addnode": "Voeg node toe",
        "implementation": "Implementatie",
        "tabyourboldcard": "Houd uw Boltcard tegen de achterkant van dit apparaat",
        "controlyourlnkeys": "Beheer je eigen lightning node en sleutels:",
        "lnnodestep1": "Host de <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>proxy folder</a> op je server.",
        "lnnodestep2": "Vul je lightning node's REST host en sleutels in 'config.php'.",
        "lnnodestep3": "Voer je server adres hieronder in.",
        "enterlnapikey": "Voer API sleutel in om '" + data.proxy + "' te ontgrendelen",
        "viewinvoice": "Bekijk invoice",
        "noinvoicesfound": "Geen invoices gevonden.",
        "invoiceslocked": "Node proxy beveiligd, Niet in staat om invoices op te halen.<br/>Voer uw <span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>API sleutel</span> in.",
        "invoiceoffline": "Node offline, niet in staat om invoices op te halen.",
        // notifications
        "nodenotfound": "Node niet gevonden",
        "proxynotfound": "Proxy niet gevonden",
        "enterserver": "Voer uw serveradres in",
        "defaultproxy": data.fixed_url + " is een standaard proxy",
        "proxyexists": "Proxy is al toegevoegd",
        "invalidurl": "Ongeldige url",
        "selectimplementation": "Kies implementatie",
        "selectlnhost": "Selecteer " + data.imp + " Host",
        "selectkeyname": "Selecteer " + data.impkeyname,
        "entermacaroon": "Voer uw 'invoice macaroon' in",
        "invalidkeyformat": "Ongeldig sleutel formaat",
        "proxylocked": "Huidige proxy is beveiligd, voer uw API sleutel in",
        "proxyoffline": "Huidige node is offline, probeer " + data.proxy_message + " proxy",
        "folderpermissions": "Niet in staat om naar cache te schrijven, controleer uw folder permissies.",
        "proxyadded": "Proxy toegevoegd",
        "unabletoconnectto": "Kan geen verbinding maken met " + data.value,
        "proxynameexists": data.imp + " reeds toegevoegd",
        "proxyinuse": data.imp + ": '" + data.name + "' gebruikt deze proxy, verwijder deze eerst",
        "proxyremoved": "Proxy verwijderd",
        "serviceremoved": "Service verwijderd",
        "unknownproxy": "Onbekende proxy server",
        "proxyunlocked": "Proxy ontgrendeld!",
        "proxydatamissing": "Proxy data ontbreekt",
        "invoicecanceled": "Invoice geanulleerd",
        // confirm
        "enablelightning": "Schakel lightning betalingen in?",
        "disablelightning": "Schakel lightning betalingen uit?",
        "disableproxy": "Schakel proxy " + data.set_proxy_val + " uit?",
        "enableproxy": "Schakel proxy " + data.set_proxy_val + " in?",
        // dialog
        "unabletoconnectln": "Kan geen verbinding aken met de lightning node",

        // BIP39
        "disclaimer": "Disclaimer!",
        "cannotbespend": "Ontvangen bedragen naar adressen die zijn gegenereerd vanuit je geheime zin kunnen niet worden verstuurd met bitrequest.<br/>Om je crypto te versturen zul je je geheime zin moeten invoeren in een <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>ondersteunde wallet.</a>",
        "compatiblewallets": "Ondersteunde wallets",
        "important": "Belangrijk!",
        "abouttobecome": "Je staat op het punt om je eigen bank te worden.",
        "inthenextscreen": "In het volgende scherm, zul je je geheime zin zien.",
        "makesure": "Schrijf deze op en bewaar het op n veilige plek.",
        "understandandok": "Ik begrijp het en ga akkoord.",
        "entersecretphrase": "Voer uw geheime zin in:",
        "writedownsecretphrase": "Schrijf uw geheime zin op en bewaar het op een veilige plek.",
        "ifyouloseyourphrase": "Als je geheime zin kwijt raakt,<br/>ben je je geld kwijt!",
        "understand": "Ik begrijp het!",
        "verifycurrent": "Verifieer uw huidige geheime zin",
        "verifybackup": "Verifieer Backup:",
        "withgreatpower": "Met grote macht komt grote verantwoordelijkheid.",
        "remember": "Vergeet niet een backup te maken van uw <span id='toseed'>Geheime zin</span>.",
        "overwritten": "Zorg ervoor dat u een backup heeft van uw huidige <span id='toseed'>Geheime zin</span>. hij zal worden overschreven.",
        "word": "woord",
        "idothislater": "Ik doe dit later",
        "ivebackeditup": "Ik heb een backup gemaakt!",
        "next": "volgende",
        "prev": "vorige",
        "findmorewallets": "Zoek meer wallets",
        // notifications
        "alreadyhavesecretphrase": "Je hebt al een geheime zin",
        "wrongsecretphrase": "verkeerde geheime zin",
        "consent": "Stem in om door te gaan.",
        "secretphrasedeleted": "Geheime zin verwijderd",
        "congratulations": "Gefeliciteerd. Je bent nu je eigen bank!",
        "passphraseverified": "Geheime zin geverifieerd",
        "backupasap": "Maak zsm een backup van je geheime zin!",
        // confirm
        "resoresecretphrase": "Herstel geheime zin",
        "areyousuredfp": "Weet je zeker dat je je geheime zin wilt verwijderen?",
        "restoresecretphrasefrombackup": "Weet je zeker dat je de geheime zin uit je backup wilt gebruiken? Je huidige geheime zin zal worden verwijderd.",
        // dialog
        "continueatownrisk": "Waarschuwing! Ga verder op eigen risico.",
        "ifyouloseyourdevice": "In het geval je de applicatie / browserdata verwijderd, je telefoon of laptop kwijtraakt heb je je geheime zin nodig om toegang te krijgen tot je crypto valuta!",
        "deletingyoursecretphrase": "Waarschuwing! Door het verwijderen van je geheime zin zonder backup zul je geen toegang meer hebben tot je crypto valuta.",
        "continuewithbackup": "Ga alleen verder als je een backup hebt van je 12 woordige geheime zin.",

        // SOCKETS
        // notifications
        "youareoffline": "Je bent momenteel offline",
        "networks": "netwerken",
        "acceptthepayment": "Accepteer de betaling in je lightning app...",
        "ndeftablimit": "Te vaak aangeraakt",
        "enteramount": "Vul bedrag in",
        "cardmax": "Bedrag is hoger dan de Boltcard limiet",
        "minamount": "Minimumale verzoek bedrag is " + data.min,
        "waitingforpayment": "In afwachting van betaling",
        "websocketoffline": "websocket offline",

        // PIN PANEL
        "pleaseenter": "Toets uw pincode in",
        "createpin": "Kies een 4 cijferige pincode",
        "locktime": "Vergrendel tijd",
        "resetpin": "Herstel pin",
        "minute": "minuut",
        "minutes": "minuten",
        "never": "nooit",
        "pincodeactivated": "Pincode geactiveerd",
        "pincodedisabled": "Pincode gedeactiveerd",
        "confirmyourpin": "Bevestig uw pincode",

        // LOCKSCREEN
        "unlockwithsecretphrase": "Ontgrendel met geheime zin",
        "tomanyunlocks": "Te veel ontgrendel pogingen",
        "enter12words": "Voeg je 12 woordige<br/>geheime zin in:",
        "tryagainin": "Probeer opnieuw over",
        "unlock": "Ontgrendel",

        // BUTTONS AND PANELS
        "cancelbttn": "annuleer",
        "okbttn": "ok",
        "show": "Toon",
        "hide": "Verberg",
        "delete": "Verwijder",
        "restorebttn": "herstel",
        "showtransactions": "Toon transacties",
        "sharerequestbutton": "Deel verzoek",
        "addcoinaddress": "Voeg " + data.currency + " adres toe",
        "generatewallet": "Maak een wallet aan op basis van een geheime zin.",
        "pkownership": "Ik ben in het bezit van de private key van dit adres.",
        "nopub": "Adres / Xpub",
        "update": "update",
        "install": "installeren",
        "pay": "betaal",

        //DIALOGS
        "totalchanges": "Je hebt " + data.total_changes + " aanpassingen in je app",
        "nochanges": "Je hebt 0 aanpassingen in je app",
        "havewallet": "Heb je een " + data.lnd_ref + " wallet op dit apparaat?",

        // DATES
        "sunday": "Zondag",
        "monday": "Maandag",
        "tuesday": "Dinsdag",
        "wednesday": "Woensdag",
        "thursday": "Donderdag",
        "friday": "Vrijdag",
        "saturday": "Zaterdag",
        "year": "jaar",
        "years": "jaar",
        "month": "maand",
        "months": "maanden",
        "week": "week",
        "weeks": "weken",
        "day": "dag",
        "days": "dagen",
        "hour": "uur",
        "hours": "uur",
        "minute": "minuut",
        "minutes": "minuten",
        "seconds": "seconden",
        "and": "en",
        "expiresin": "Vervalt over ",
        "fileexpired": "Bestand verlopen",

        // LOADERTEXT
        "generatereceipt": "Genereer afschrift",
        "connecttolnur": "Verbinden met " + data.url,
        "loadurl": data.url + " aan het laden...",
        "loading": "Laden...",
        "gettokeninfo": "Haal token informatie op",
        "checklightningstatus": "Controleer " + data.imp + " lightning status",
        "readingfromcache": "Haal " + data.ccsymbol + " op uit cache",
        "getccrates": "Haal " + data.ccsymbol + " koers op van " + data.api,
        "getfiatrates": "Haal fiat koersen op",
        "readingfiatratesfromcache": "Haal fiat koersen op uit cache",
        "fetchingfiatrates": "Haal fiat koersen op van " + data.fiatapi,
        "generatelink": "Genereer betaallink",
        "loadingcamera": "Camera aan het laden",
        "generatebu": "Genereer systeem backup",
        "installationpackage": "Genereer installatie pakket",
        "closingrequest": "Verzoek aan het afsluitn",
        "scanningforincoming": "scannen naar inkomende transacties",

        // RANDOM TERMS
        "address": "adres",
        "choose": "Kies",
        "enable": "Activeer",
        "disable": "Deactiveer",
        "apikey": "API sleutel",
        "yes": "ja",
        "no": "nee",
        "verified": "geverifieerd",
        "error": "fout",
        "apierror": "api error",
        "success": "Success",
        "warning": "Waarschuwing!",
        "edit": "Bewerk",
        "enter": "Voeg toe",

        // CHECK INTENTS
        "proto": data.proto + ": connect niet beschikbaar op het moment",
        "invalidurlscheme": "Ongeldig URL schema",
        "usnotsupported": "URL schema '" + data.proto + ":' niet ondesteund",

        // GOOGLE AUTH
        "stopgauth": "Annuleer Google Drive Backup.",
        "gauthsafely": "backup je appdata veilig.",
        "gauthsync": "synchroniseer je data veilig met Google Drive.",
        "signin": "Meld aan",
        "backuptogd": "Back up naar Google Drive",
        // notifications
        "ganot": "GoogleAuth niet beschikbaar",
        "gdsignedin": "Succesvol aangemeld",
        "gdsignedout": "Succesvol afgemeld",
        "filedeleted": "Bestand verwijderd",
        "filenotfound": "Bestand niet gevonden",
        // confirm
        "stopgdalert": "Weet je zeker dat je wilt stoppen met Google Drive Backup",
        "deletefile": "Verwijder" + " " + data.file + "?"
    }
    return translation[id];
}