// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"de": {
    "lang": "German",
    "obj": lang_de(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_de(id, data) {
    const translation = {
        "payoff": "Akzeptiere Krypto überall",

        // PAGES
        "home": "Home",
        "currencies": "Währungen",
        "requests": "Anfragen",
        "settings": "Einstellungen",
        "coinsettings": "Coin-Einstellungen",
        "addresses": "Adressen",

        // INTRO
        "enteryourname": "Bitte geben Sie Ihren Namen ein",
        "more": "Mehr",
        "restorefrombackup": "Aus Backup wiederherstellen",

        // CORE
        // notifications
        "datasaved": "Daten gespeichert",
        "pinmatch": "PIN stimmt nicht überein",
        "xratesx": "Wechselkurs konnte nicht abgerufen werden",
        "entercoinaddress": "Geben Sie eine " + data.currency + "-Adresse ein.",
        "label": "Label (optional)",
        "errorvk": "Fehler bei Viewkey-Überprüfung",
        "invalidvk": "Ungültiger Viewkey",
        "continuevk": "Möchten Sie wirklich ohne Viewkey fortfahren? Ohne Viewkey können Transaktionen nicht überwacht werden.",
        "novalidaddress": "ist KEINE gültige " + data.currency + "-Adresse.",
        "pickacurrency": "Währung auswählen",
        "invalidlabel": "Ungültiges Label",
        "noactivecurrencies": "Keine aktiven Währungen",
        "addressremoved": "Adresse entfernt",
        "movedtoarchive": "Ins Archiv verschoben",
        "requestrestored": "Anfrage wiederhergestellt",
        "requestdeleted": "Anfrage gelöscht",
        "requestsaved": "Anfrage gespeichert",
        "requiredfields": "Bitte füllen Sie die Pflichtfelder aus",
        "requiredfield": "ist ein Pflichtfeld",
        "requestinginvoice": "Invoice wird angefordert...",
        "nofetchincoice": "Invoice konnte nicht abgerufen werden.",
        "copy": "Kopieren",
        "copied": "in Zwischenablage kopiert",
        "xcopy": "Kopieren fehlgeschlagen",
        "cashiernotallowed": "Im Kassierer-Modus nicht erlaubt",
        "decodeqr": "QR-Code konnte nicht dekodiert werden",
        "invalidformat": "Ungültiges Format",
        "invalidmacaroon": "Ungültiges Macaroon-Format",
        "recentrequests": "Letzte Anfragen",
        "encodeyoraddress": "Kodiere deine Adresse auf bitrequest.io/qr",
        // confirm
        "openurl": data.url + " öffnen?",
        "showrequestsfor": "Anfragen für " + data.address + " anzeigen?",
        "areyousure": "Sind Sie sicher?",
        "openinvoice": "Invoice öffnen: " + data.hash + "?",
        "sharefile": data.filename + " teilen?",
        // dialog
        "nofetchtokeninfo": "Token-Daten konnten nicht abgerufen werden.",
        "archiverequest": "Anfrage archivieren?",
        "unarchiverequest": "Anfrage wiederherstellen?",
        "failedtofetchrequest": "Anfrage konnte nicht abgerufen werden",
        "downloadwallet": data.currency + "-Wallet herunterladen",

        // ADD ADDRESS
        "alreadyexists": "Adresse existiert bereits",
        "addaddress": "Adresse hinzufügen",
        "adderc20token": "ERC20-Token hinzufügen",
        "erc20placeholder": "ERC20-Token auswählen",
        "enteraddress": "Adresse eingeben",
        "noaddressyet": "Ich habe noch keine " + data.currency + "-Adresse",

        // ADDRESS INFO
        "showrequests": "Anfragen anzeigen",
        "newrequest": "Neue Anfrage",
        "addressinfo": "Adressinfo",
        "editlabel": "Label bearbeiten",
        "removeaddress": "Adresse entfernen",
        "recentpayments": "Letzte Zahlungen",
        "privatekey": "Privater Schlüssel",
        "secretviewkey": "Geheimer View-Key",
        "secretspendkey": "Geheimer Spend-Key",

        // REQUEST INFO
        "currency": "Währung",
        "from": "Von",
        "title": "Beschreibung",
        "amount": "Betrag",
        "status": "Status",
        "Waiting for payment": "Warte auf Zahlung",
        "paid": "Bezahlt",
        "received": "Empfangen",
        "insufficient": "Unzureichend",
        "new": "Neu",
        "pending": "Ausstehend",
        "canceled": "Storniert",
        "expired": "Abgelaufen",
        "type": "Typ",
        "created": "Erstellt",
        "firstviewed": "Zuerst angezeigt",
        "sendon": "Anfrage gesendet am",
        "paidon": "Bezahlt am",
        "amountreceived": "Empfangener Betrag",
        "amountpaid": "Bezahlter Betrag",
        "fiatvalue": "Fiat-Wert",
        "fiatvalueon": "Fiat-Wert am",
        "receivingaddress": "Empfangsadresse",
        "fallbackaddress": "Fallback-Adresse",
        "paymentid": "Payment-ID",
        "integratedaddress": "Integrierte Adresse",
        "network": "Netzwerk",
        "incoming": "Eingehend",
        "outgoing": "Ausgehend",
        "point of sale": "Kassensystem",
        "online purchase": "Online-Kauf",
        "transactions": "Transaktionen",
        "viewon": "Ansehen auf",
        "source": "Quelle",
        "deleterequest": "Anfrage löschen",

        // REQUEST PANEL
        "sharerequest": "Anfrage teilen",
        "openwallet": "Wallet öffnen",
        "whatsyourname": "Wie ist Ihr Name?",
        "whatsitfor": "Wofür ist es?",
        "forexample": "z.B.",
        "send": "Senden",
        "to": "an",
        "nodetection": "Keine Zahlung erkannt",
        "lookuppayment": "Nach kürzlichen eingehenden " + data.currency + "-Zahlungen auf " + data.blockexplorer + " suchen",
        "dontshowagain": "Nicht erneut anzeigen",
        "dismiss": "Schließen",
        "activateintegrated": "Integrierte Adressen aktivieren",
        "pendingrequest": "Ausstehende Anfrage",
        "paymentsent": "Zahlung gesendet",
        "paymentreceived": "Zahlung empfangen",
        "txbroadcasted": "Transaktion gesendet",
        "insufficientamount": "Unzureichender Betrag",
        "txexpired": "Anfrage abgelaufen",
        "viewdetails": "Details anzeigen",
        "showqr": "QR-Code anzeigen",
        "waitingfor": "Warte auf",
        "unconfirmedtx": "Unbestätigte Transaktion",
        "amountshort": "zu wenig",
        "sharelocktitle": "Anfrage kann vorübergehend nicht geteilt werden.",
        "sharelockttext": "Diese Adresse hat eine <span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>ausstehende geteilte Anfrage</span>.",
        "waitforconfirm": "Bitte warten Sie auf die Bestätigung der Transaktion, bevor Sie die Adresse erneut verwenden.",
        "pickanotheraddress": "Andere Adresse wählen:",
        // ** request suggestion placeholders ** //
        "lunch": "Mittagessen",
        "festivaltickets": "Festivaltickets",
        "coffee": "Kaffee",
        "present": "Geschenk",
        "snowboarding": "Snowboarden",
        "movietheater": "Kino",
        "shopping": "Einkaufen",
        "videogame": "Videospiel",
        "drinks": "Getränke",
        "concerttickets": "Konzerttickets",
        "camping": "Camping",
        "taxi": "Taxi",
        "zoo": "Zoo",
        // notifications
        "failedhistoric": "Historische " + data.ccsymbol + "-Preisdaten konnten nicht abgerufen werden",
        "closingsockets": "Verbindungen werden geschlossen...",
        "nowriteaccess": "LNurl-Proxy Zugriff verweigert, Ordnerberechtigungen prüfen",
        "notmonitored": "Diese Adresse wird nicht überwacht",
        "lnoffline": "Lightning-Node ist offline",
        "addlightningnode": "Lightning-Node hinzufügen",
        "addressinuse": "Adresse wird verwendet",
        "minimal2": "Beschreibung muss mindestens 2 Zeichen haben",
        "minimal3": "Name muss mindestens 3 Zeichen haben",
        "checkyourform": "Bitte überprüfen Sie Ihr Formular",
        "entertitle": "Bitte geben Sie eine Beschreibung ein",
        "successshare": "Erfolgreich geteilt!",
        // confirm
        "opencoinsettings": data.currency + "-Einstellungen öffnen?",
        "viewpendingrequest": "Ausstehende Anfrage anzeigen?",
        "useinstead": "Stattdessen '" + data.thisinputvalue + "' verwenden?",
        "generatenewaddress": "Möchten Sie wirklich eine neue " + data.currency + "-Adresse generieren? Sie wird möglicherweise nicht in allen Wallets angezeigt",
        // dialog
        "undefinedaddress": "Undefinierte Adresse, bitte fordern Sie eine neue Anfrage an",
        "invalidaddress": "Ungültige " + data.payment + "-Adresse",

        // SHARE REQUEST
        "share": "Teilen",
        "sharetitlename": (data.requestname === "Bitrequest") ? "Hallo, ich habe eine " + data.pagenameccparam + " Bitrequest-Anfrage über " + data.amount + " " + data.uoa + " für '" + data.requesttitle + "' erstellt" : data.requestname + " hat eine " + data.pagenameccparam + " Bitrequest-Anfrage über " + data.amount + " " + data.uoa + " für '" + data.requesttitle + "' gesendet",
        "sharetitle": data.pagenameccparam + " Zahlungsanfrage über " + data.amount + " " + data.uoa,
        "sharetitlechange": data.payment + "-Anfrage über " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "Ihr Name",
        "currencysettings": "Lokale Fiat-Währung",
        "entercurrency": "Währung eingeben",
        "setasdefault": "Als Standard festlegen",
        "langsettings": "Sprache",
        "chooselanguage": "Sprache auswählen",
        "themesettings": "Design",
        "choosetheme": "Design auswählen",
        "security": "Sicherheit",
        "pinsettings": "PIN-Sperre",
        "bip39_passphrase": "Geheimphrase",
        "backupsecretphrase": "Geheimphrase sichern",
        "missingkeywarning": data.seedstrtitle + " für '<span class='adspan'>" + data.address + "</span>' fehlt.<br/>Möchten Sie diese Adresse trotzdem verwenden?",
        "emptyphrase": "Bitte geben Sie Ihre Geheimphrase ein",
        "notinwordlist": data.missing_word + " nicht in der Wortliste",
        "notbip39compatible": "Geheimphrase nicht BIP39-kompatibel",
        "mustbe12characters": "Geheimphrase muss 12 Wörter lang sein",
        "cannotsendfunds": "Bitrequest kann keine Guthaben senden!",
        "importtosend": "Um Guthaben zu senden, müssen Sie Ihre <span class='show_bip39 ref'>12-Wort-Geheimphrase</span> in einem BIP39-kompatiblen Wallet wiederherstellen:",
        "backup": "App-Daten sichern",
        "backupwithgd": "Sichern mit Google Drive:",
        "nrchanges": "Sie haben " + data.nr_changes + " Änderungen in Ihrer App. Bitte sichern Sie Ihre Daten.",
        "changein": "Änderung in",
        "changesin": "Änderungen in",
        "systembackup": "System-Backup",
        "downloadbu": "Backup herunterladen",
        "installlbu": "Backup installieren",
        "restore": "App-Daten wiederherstellen",
        "restorewithgd": "Wiederherstellen von Google Drive:",
        "lastrestore": "Letzte Wiederherstellung:",
        "lastbackup": "Letztes Backup:",
        "restorefromfile": "Aus Datei wiederherstellen",
        "differentsecretphrase": "Warnung: Backup enthält eine andere Geheimphrase.",
        "secretphrasefrombackup": "Geheimphrase aus Backup",
        "currentsecretphrase": "Aktuelle Geheimphrase",
        "usesecretphrasefrombackup": "Geheimphrase aus Backup verwenden",
        "keepcurrentsecretphrase": "Aktuelle Geheimphrase behalten",
        "comparesecretphrases": "Geheimphrasen vergleichen",
        "csvexport": "CSV exportieren",
        "includearchive": "Archiv einschließen",
        "includereceipt": "Beleg einschließen",
        "receipt": "Beleg",
        "advanced": "Erweitert",
        "url_shorten_settings": "URL-Kürzer",
        "shorturlnotfound": "Anfrage nicht gefunden",
        "cmcapisettings": "Krypto-Preisdaten",
        "fiatapisettings": "Fiat-Preisdaten",
        "api_proxy": "API-Proxy",
        "updateproxy": "Bitte aktualisieren Sie Ihren Proxy-Server " + data.version + " > " + data.proxy_version,
        "addapiproxy": "API-Proxy hinzufügen",
        "controlyourkeys": "Verwalten Sie Ihre eigenen Schlüssel und Anfragelimits:",
        "proxystep1": "Hosten Sie den <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API-Proxy-Ordner</a> auf Ihrem Server (PHP erforderlich).",
        "proxystep2": "Tragen Sie Ihre API-Schlüssel in 'config.php' ein.",
        "proxystep3": "Geben Sie Ihre Serveradresse unten ein.",
        "addrpcproxy": "RPC-Proxy hinzufügen",
        "tryotherproxy": "Anderen Proxy versuchen",
        "apikeys": "API-Schlüssel",
        "apicallfailed": "API-Aufruf fehlgeschlagen",
        "apididnotrespond": "API hat nicht geantwortet",
        "contactform": "Kontaktformular",
        "shipping": "Versand",
        "yourdetails": "Ihre Daten für Online-Käufe.",
        "permissions": "Berechtigungen",
        "teaminvite": "Team-Einladung",
        "inviteteammembers": "Laden Sie Teammitglieder (Mitarbeiter etc.) ein, um in Ihrem Namen Anfragen zu stellen.",
        "teaminviteexplainer": "Bitrequest wird auf dem Gerät Ihres Teammitglieds installiert, mit Ihren öffentlichen Schlüsseln und eingeschränktem Zugang (Kassierer).",
        "teaminviteaccess": "Ihre Teammitglieder haben keinen Zugriff auf Guthaben oder Einstellungen.",
        "teaminviteharetitle": "Bitrequest Team-Einladung von " + data.accountname,
        "teamupdate": "Team-Update",
        "invitationexpiresin": "Einladung läuft ab in",
        "installcompleted": "Installation bereits abgeschlossen!",
        "teamup": data.account + " möchte mit Ihnen zusammenarbeiten und gemeinsam Anfragen stellen!",
        "teamupdata": data.account + " möchte, dass Sie Bitrequest mit seinen neuesten öffentlichen Schlüsseln aktualisieren",
        "clickinstall": "Durch Klicken auf Installieren wird Bitrequest auf Ihrem Gerät mit den öffentlichen Schlüsseln von " + data.account + " und eingeschränktem Zugang installiert.",
        // notifications
        "nameisrequired": "Name ist erforderlich",
        "currencysaved": "Währung gespeichert",
        "currencynotsupported": "Währung '" + data.currency + "' nicht unterstützt",
        "noiosbu": "Downloads für iOS-App derzeit nicht verfügbar",
        "downloaded": data.file + " heruntergeladen",
        "filesize": "Datei zu groß",
        "filetype": "Dateityp '" + data.filetype + "' nicht unterstützt",
        "selectbackup": "Backup-Datei auswählen",
        "unauthorized": "Nicht autorisiert",
        "maxattempts": "Maximale Versuche überschritten",
        "fourdigitpin": "Geben Sie Ihre 4-stellige PIN ein",
        "wrongpin": "Falsche PIN",
        "nocsvexports": "Keine Anfragen zum Exportieren",
        "validateapikey": "Geben Sie einen gültigen API-Schlüssel ein",
        "unabletopost": "Post-Anfrage von " + data.fixed_url + " konnte nicht gesendet werden",
        "invalidapikey": "Ungültiger API-Schlüssel",
        "apicallerror": "API-Aufruffehler",
        "invalidapikeyname": "Ungültiger " + data.thisref + " API-Schlüssel",
        "addapikey": data.apisrc + " API-Schlüssel hinzufügen",
        "phname": "Name",
        "phaddress": "Adresse",
        "phzipcode": "PLZ",
        "phcity": "Stadt",
        "phcountry": "Land",
        "phemail": "E-Mail",
        "invalidchars": "enthält ungültige Zeichen",
        "pleaseverify": "Bitte überprüfen Sie Ihre Geheimphrase.",
        "owndevice": "Einladung kann nicht auf eigenem Gerät installiert werden",
        "installcomplete": "Installation abgeschlossen!",
        // confirm
        "includesecretphrase": "Verschlüsselte Geheimphrase in Backup einschließen? Stellen Sie sicher, dass Sie Ihre Backup-Dateien sicher aufbewahren!",
        "sharebu": "System-Backup teilen?",
        "installsb": "SYSTEM-BACKUP INSTALLIEREN? ALLE AKTUELLEN APP-DATEN WERDEN ERSETZT",
        "downloadfile": "Herunterladen: " + data.file + "?",
        "restorefile": "Wiederherstellen: " + data.file + "?",
        "restorefromdevice": data.file + " von " + data.device + "-Gerät wiederherstellen?",
        "restorewithoutsecretphrase": "Ohne Geheimphrase wiederherstellen?",
        "keepexistingsecretphrase": "Möchten Sie wirklich Ihre bestehende Geheimphrase behalten?",
        "sharecsvexport": "CSV-Export teilen?",
        "disableshorturls": "Möchten Sie URL-Kürzung wirklich deaktivieren? Dies kann den Workflow der App beeinträchtigen",
        "sendinvite": "Einladung senden",
        "updatealert": "Aktualisieren? Alle Ihre öffentlichen Schlüssel werden aktualisiert.",
        "installalert": "Installieren? Alle Ihre öffentlichen Schlüssel werden ersetzt.",

        // COIN SETTINGS
        "confirmations": "Bestätigungen",
        "showsatoshis": "Satoshis anzeigen",
        "Use random address": "Zufällige Adresse verwenden",
        "Share viewkey": "Viewkey teilen",
        "Integrated addresses": "Integrierte Adressen",
        "Reuse address": "Adresse wiederverwenden",
        "blockexplorers": "Blockexplorer",
        "chooseblockexplorer": "Blockexplorer auswählen",
        "apis": "APIs",
        "addapi": data.h_hint + " RPC hinzufügen:",
        "websockets": "Websockets",
        "addwebsocket": data.h_hint + " Websocket hinzufügen:",
        "layer2": "Layer 2",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32 Erweiterter öffentlicher Schlüssel",
        "addxpub": data.currency + " Xpub-Schlüssel hinzufügen",
        "xpubmatch": "Die obigen Adressen stimmen mit denen in meinem " + data.currency + "-Wallet überein.",
        "xpubkeys": "Ich besitze die Geheimphrase / den Xpriv-Schlüssel",
        "Key derivations": "Schlüsselableitungen",
        "derivationpath": "Ableitungspfad",
        "soundbytes": "Soundbytes",
        "choosesoundbytes": "Soundbyte auswählen",
        "resetbutton": "Zurücksetzen",
        // notifications
        "unabletoconnect": "Verbindung fehlgeschlagen",
        "nodealreadyadded": "Node bereits hinzugefügt",
        "removedefaultnode": "Standard-Node kann nicht entfernt werden",
        "rpcnoderemoved": "RPC-Node entfernt",
        "confirmmatch": "Bestätigen Sie die Übereinstimmung der Adressen",
        "confirmpkownership": "Bestätigen Sie den Besitz des privaten Schlüssels",
        "invalidxpub": "KEIN gültiger / unterstützter " + data.currency + " Xpub-Schlüssel",
        "xpubsaved": "Xpub gespeichert",
        "resetnotify": data.currency + "-Einstellungen auf Standard zurückgesetzt",
        // confirm
        "reusewarningalert": "Möchten Sie wirklich neue " + data.thiscurrency + "-Adressen generieren? Sie werden möglicherweise nicht in allen Wallets angezeigt.",
        "reusealert": "Möchten Sie wirklich " + data.thiscurrency + "-Adressen wiederverwenden?",
        "confirmremovenode": "Möchten Sie '" + data.thisval + "' wirklich entfernen?",
        "disablexpub": "Xpub-Adressableitung deaktivieren?",
        "replacexpub": "Xpub ersetzen?",
        "uselegacy": data.thiscurrency + " Legacy-Adressen verwenden?",
        "usesegwit": data.thiscurrency + " SegWit-Adressen verwenden?",
        "resetconfirm": "Möchten Sie die " + data.currency + "-Einstellungen wirklich zurücksetzen?",
        // dialog
        "resetdialog": data.currency + "-Einstellungen zurücksetzen?",

        // LIGHTNING
        "Lightning network": "Lightning-Netzwerk",
        "lightningnode": "Lightning-Node",
        "addnode": "Node hinzufügen",
        "implementation": "Implementierung",
        "tabyourboldcard": "Bitte halten Sie Ihre Boltcard an die Rückseite dieses Geräts",
        "controlyourlnkeys": "Verwalten Sie Ihre eigene Lightning-Node und Schlüssel:",
        "lnnodestep1": "Hosten Sie den <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>Proxy-Ordner</a> auf Ihrem Webserver.",
        "lnnodestep2": "Tragen Sie den REST-Host und die Schlüssel Ihrer Lightning-Node in 'config.php' ein.",
        "lnnodestep3": "Geben Sie Ihre Serveradresse unten ein.",
        "enterlnapikey": "Proxy-API-Schlüssel eingeben, um '" + data.proxy + "' freizuschalten",
        "viewinvoice": "Invoice anzeigen",
        "noinvoicesfound": "Keine Invoices gefunden.",
        "invoiceslocked": "Node-Proxy gesperrt, Invoices können nicht abgerufen werden.<br/>Bitte geben Sie Ihren Proxy-<span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>API-Schlüssel</span> ein.",
        "invoiceoffline": "Node offline, Invoices können nicht abgerufen werden.",
        // notifications
        "nodenotfound": "Node nicht gefunden",
        "proxynotfound": "Proxy nicht gefunden",
        "enterserver": "Bitte Serveradresse eingeben",
        "defaultproxy": data.fixed_url + " ist ein Standard-Proxy",
        "proxyexists": "Proxy bereits hinzugefügt",
        "invalidurl": "Ungültige URL",
        "selectimplementation": "Implementierung auswählen",
        "selectlnhost": data.imp + "-Host auswählen",
        "selectkeyname": data.impkeyname + " auswählen",
        "entermacaroon": "Bitte 'invoice'-Macaroon eingeben",
        "invalidkeyformat": "Ungültiges Schlüsselformat",
        "proxylocked": "Aktueller Node-Proxy ist gesperrt, bitte API-Schlüssel eingeben",
        "proxyoffline": "Aktueller Node ist offline, " + data.proxy_message + " Proxy versuchen",
        "folderpermissions": "Schreiben in Cache nicht möglich, bitte Ordnerberechtigungen prüfen.",
        "proxyadded": "Proxy hinzugefügt",
        "unabletoconnectto": "Verbindung zu " + data.value + " nicht möglich",
        "proxynameexists": data.imp + "-Node bereits hinzugefügt",
        "proxyinuse": data.imp + ": '" + data.name + "' verwendet diesen Proxy, zuerst entfernen",
        "proxyremoved": "Proxy entfernt",
        "serviceremoved": "Service entfernt",
        "unknownproxy": "Unbekannter Proxy-Server",
        "proxyunlocked": "Proxy freigeschaltet!",
        "proxydatamissing": "Proxy-Daten fehlen",
        "invoicecanceled": "Invoice storniert",
        // confirm
        "enablelightning": "Lightning-Zahlungen aktivieren?",
        "disablelightning": "Lightning-Zahlungen deaktivieren?",
        "disableproxy": "Proxy " + data.set_proxy_val + " deaktivieren?",
        "enableproxy": "Proxy " + data.set_proxy_val + " aktivieren?",
        // dialog
        "unabletoconnectln": "Verbindung mit Lightning-Node nicht möglich",

        // BIP39
        "disclaimer": "Haftungsausschluss!",
        "cannotbespend": "Guthaben, die über Adressen aus Ihrer Geheimphrase empfangen wurden, können nicht über Bitrequest ausgegeben werden.<br/>Um Ihr Guthaben auszugeben, müssen Sie Ihre Geheimphrase in einem <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>kompatiblen Wallet</a> wiederherstellen.",
        "compatiblewallets": "Kompatible Wallets",
        "important": "Wichtig!",
        "abouttobecome": "Sie werden gleich Ihre eigene Bank.",
        "inthenextscreen": "Im nächsten Bildschirm sehen Sie Ihre Geheimphrase.",
        "makesure": "Schreiben Sie sie auf und bewahren Sie sie sicher auf!",
        "understandandok": "Ich verstehe und bin damit einverstanden.",
        "entersecretphrase": "Geben Sie Ihre Geheimphrase ein:",
        "writedownsecretphrase": "Schreiben Sie Ihre Geheimphrase auf und bewahren Sie sie sicher auf.",
        "ifyouloseyourphrase": "Wenn Sie Ihre Phrase verlieren,<br/>verlieren Sie Ihr Geld!",
        "understand": "Ich verstehe!",
        "verifycurrent": "Aktuelle Geheimphrase überprüfen:",
        "verifybackup": "Backup überprüfen:",
        "withgreatpower": "Mit großer Macht kommt große Verantwortung.",
        "remember": "Denken Sie daran, Ihre <span id='toseed'>Geheimphrase</span> zu sichern.",
        "overwritten": "Sichern Sie Ihre aktuelle <span id='toseed'>Geheimphrase</span>. Sie wird überschrieben",
        "word": "Wort",
        "idothislater": "Das mache ich später",
        "ivebackeditup": "Ich habe sie gesichert!",
        "next": "Weiter",
        "prev": "Zurück",
        "findmorewallets": "Weitere Wallets finden",
        // notifications
        "alreadyhavesecretphrase": "Sie haben bereits eine Geheimphrase",
        "wrongsecretphrase": "Falsche Geheimphrase",
        "consent": "Bitte stimmen Sie zu, um fortzufahren.",
        "secretphrasedeleted": "Geheimphrase gelöscht",
        "congratulations": "Herzlichen Glückwunsch. Sie sind jetzt Ihre eigene Bank!",
        "passphraseverified": "Passphrase verifiziert",
        "backupasap": "Bitte sichern Sie Ihre Geheimphrase so schnell wie möglich",
        // confirm
        "resoresecretphrase": "Geheimphrase wiederherstellen",
        "areyousuredfp": "Möchten Sie Ihre Geheimphrase wirklich löschen?",
        "restoresecretphrasefrombackup": "Möchten Sie Ihre Geheimphrase wirklich aus dem Backup wiederherstellen? Ihre aktuelle Geheimphrase wird gelöscht.",
        // dialog
        "continueatownrisk": "Warnung! Fortfahren auf eigene Gefahr.",
        "ifyouloseyourdevice": "Wenn Sie Ihr Gerät verlieren, Ihre App deinstallieren oder Ihre Browserdaten löschen, brauchen Sie Ihre Geheimphrase, um Ihr Guthaben wiederherzustellen!",
        "deletingyoursecretphrase": "Warnung! Das Löschen Ihrer Geheimphrase kann zum Verlust von Guthaben führen.",
        "continuewithbackup": "Fahren Sie nur fort, wenn Sie ein Backup Ihrer Geheimphrase haben.",

        // SOCKETS
        // notifications
        "youareoffline": "Sie sind derzeit offline",
        "networks": "Netzwerke",
        "acceptthepayment": "Akzeptieren Sie die Zahlung in Ihrer Lightning-App...",
        "ndeftablimit": "Zu schnell getippt",
        "enteramount": "Bitte Betrag eingeben",
        "cardmax": "Anfrage überschreitet Kartenlimit",
        "minamount": "Mindestanfragebetrag ist " + data.min,
        "waitingforpayment": "Warte auf Zahlung",
        "websocketoffline": "Node offline",

        // PIN PANEL
        "pleaseenter": "Bitte geben Sie Ihre PIN ein",
        "createpin": "Erstellen Sie eine 4-stellige PIN",
        "locktime": "Sperrzeit",
        "resetpin": "PIN zurücksetzen",
        "enternewpin": "Neue PIN eingeben",
        "minute": "Minute",
        "minutes": "Minuten",
        "never": "Nie",
        "pincodeactivated": "PIN aktiviert",
        "pincodedisabled": "PIN deaktiviert",
        "confirmyourpin": "Bestätigen Sie Ihre PIN",

        // LOCKSCREEN
        "unlockwithsecretphrase": "Mit Geheimphrase entsperren",
        "tomanyunlocks": "Zu viele Entsperrversuche",
        "enter12words": "Geben Sie Ihre 12-Wort-<br/>Geheimphrase ein:",
        "tryagainin": "Bitte versuchen Sie es erneut in",
        "unlock": "Entsperren",

        // BUTTONS AND PANELS
        "cancelbttn": "Abbrechen",
        "okbttn": "OK",
        "show": "Anzeigen",
        "hide": "Verbergen",
        "delete": "Löschen",
        "restorebttn": "Wiederherstellen",
        "showtransactions": "Transaktionen anzeigen",
        "sharerequestbutton": "Anfrage teilen",
        "addcoinaddress": data.currency + "-Adresse hinzufügen",
        "generatewallet": "Wallet aus Geheimphrase erstellen.",
        "pkownership": "Ich besitze den privaten Schlüssel dieser Adresse.",
        "nopub": "Adresse / Xpub",
        "update": "Aktualisieren",
        "install": "Installieren",
        "pay": "Bezahlen",

        //DIALOGS
        "totalchanges": "Sie haben " + data.total_changes + " Änderungen in Ihrer App",
        "nochanges": "Sie haben 0 Änderungen in Ihrer App",
        "havewallet": "Haben Sie ein " + data.lnd_ref + "-Wallet auf diesem Gerät?",

        // DATES
        "sunday": "Sonntag",
        "monday": "Montag",
        "tuesday": "Dienstag",
        "wednesday": "Mittwoch",
        "thursday": "Donnerstag",
        "friday": "Freitag",
        "saturday": "Samstag",
        "year": "Jahr",
        "years": "Jahre",
        "month": "Monat",
        "months": "Monate",
        "week": "Woche",
        "weeks": "Wochen",
        "day": "Tag",
        "days": "Tage",
        "hour": "Stunde",
        "hours": "Stunden",
        "minute": "Minute",
        "minutes": "Minuten",
        "seconds": "Sekunden",
        "and": "und",
        "expiresin": "Läuft ab in ",
        "fileexpired": "Datei abgelaufen",

        // LOADERTEXT
        "generatereceipt": "Beleg wird erstellt",
        "connecttolnur": "Verbinde mit " + data.url,
        "loadurl": "Lade " + data.url,
        "loading": "Laden...",
        "gettokeninfo": "Token-Info abrufen",
        "checklightningstatus": data.imp + " Lightning-Status prüfen",
        "readingfromcache": "Lese " + data.ccsymbol + "-Kurs aus Cache",
        "getccrates": data.ccsymbol + "-Kurse von " + data.api + " abrufen",
        "getfiatrates": "Fiat-Kurse abrufen",
        "readingfiatratesfromcache": "Lese Fiat-Kurse aus Cache",
        "fetchingfiatrates": "Fiat-Kurse von " + data.fiatapi + " abrufen",
        "generatelink": "Link wird erstellt",
        "loadingcamera": "Kamera wird geladen",
        "generatebu": "System-Backup erstellen",
        "installationpackage": "Installationspaket erstellen",

        // RANDOM TERMS
        "address": "Adresse",
        "choose": "Auswählen",
        "enable": "Aktivieren",
        "disable": "Deaktivieren",
        "apikey": "API-Schlüssel",
        "yes": "Ja",
        "no": "Nein",
        "none": "Keine",
        "verified": "Verifiziert",
        "error": "Fehler",
        "apierror": "API-Fehler",
        "success": "Erfolgreich",
        "warning": "Warnung!",
        "edit": "Bearbeiten",
        "enter": "Eingeben",

        // CHECK INTENTS
        "proto": data.proto + ": Verbindung derzeit nicht verfügbar",
        "invalidurlscheme": "Ungültiges URL-Schema",
        "usnotsupported": "URL-Schema '" + data.proto + ":' wird nicht unterstützt",

        // GOOGLE AUTH
        "stopgauth": "Google Drive Backup beenden.",
        "gauthsafely": "Sichern Sie Ihre App-Daten.",
        "gauthsync": "Synchronisieren Sie Ihre Daten sicher mit Google Drive.",
        "signin": "Anmelden",
        "backuptogd": "Auf Google Drive sichern",
        // notifications
        "ganot": "GoogleAuth nicht verfügbar",
        "gdsignedin": "Erfolgreich angemeldet",
        "gdsignedout": "Erfolgreich abgemeldet",
        "filedeleted": "Datei gelöscht",
        "filenotfound": "Datei nicht gefunden",
        // confirm
        "stopgdalert": "Möchten Sie Google Drive Backup wirklich beenden?",
        "deletefile": data.file + " löschen?"
    }
    return translation[id];
}
