// 1. Copy the file assets_js_bitrequest_lang_en.js and replace the filename with your countrycode suffix.
// Example assets_js_bitrequest_lang_en.js --> assets_js_bitrequest_lang_nl.js

// 2. Add the scripttag with your new file to index.html

// 3. Replace the functionname 'lang_en' below with your countrycode.
// Example lang_en(id, data) -> lang_nl(id, data)

// 4. Add your language object with the right countrycode / countryname and functionname to the translate() function in assets_js_bitrequest_lang_controller.js
// Example:

/* 
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
}
-->
"en": {
    "lang": "English",
    "obj": lang_en(id, data)
},
"zh-cn": {
    "lang": "Chinese (Simplified)",
    "obj": lang_zh_cn(id, data)
}
*/

// 4. Translate the function object below.
// Leave the object keys unchanged, translate the object value, don't translate variables!! (You can rearrange variables for your language format).
// Try to keep stringlength the same.
// Blanks default to english.
// Submit a pull request. (Please test if everything is working).

function lang_zh_cn(id, data) {
    const translation = {
        "payoff": "随时随地接受加密货币",

        // PAGES
        "home": "首页",
        "currencies": "币种",
        "requests": "收款请求",
        "settings": "设置",
        "coinsettings": "币种设置",
        "addresses": "地址",

        // INTRO
        "enteryourname": "请输入您的姓名",
        "more": "更多",
        "restorefrombackup": "从备份恢复",

        // CORE
        // notifications
        "datasaved": "数据已保存",
        "pinmatch": "PIN码不匹配",
        "xratesx": "无法获取汇率",
        "entercoinaddress": "请输入" + data.currency + "地址。",
        "label": "标签（可选）",
        "errorvk": "Viewkey验证出错",
        "invalidvk": "无效的Viewkey",
        "continuevk": "确定要在没有viewkey的情况下继续吗？没有viewkey将无法监控交易。",
        "novalidaddress": "不是有效的" + data.currency + "地址。",
        "pickacurrency": "选择币种",
        "invalidlabel": "无效的标签",
        "noactivecurrencies": "没有活跃的币种",
        "addressremoved": "地址已移除",
        "movedtoarchive": "已移至存档",
        "requestrestored": "请求已恢复",
        "requestdeleted": "请求已删除",
        "requestsaved": "请求已保存",
        "requiredfields": "请填写必填项",
        "requiredfield": "是必填项",
        "requestinginvoice": "正在请求Invoice...",
        "nofetchincoice": "无法获取Invoice。",
        "copy": "复制",
        "copied": "已复制到剪贴板",
        "xcopy": "复制失败",
        "cashiernotallowed": "收银员模式下不允许此操作",
        "decodeqr": "无法解码二维码",
        "invalidformat": "无效的格式",
        "invalidmacaroon": "无效的Macaroon格式",
        "recentrequests": "最近的请求",
        "encodeyoraddress": "在bitrequest.io/qr编码您的地址",
        // confirm
        "openurl": "打开" + data.url + "？",
        "showrequestsfor": "显示" + data.address + "的请求？",
        "areyousure": "您确定吗？",
        "openinvoice": "打开Invoice：" + data.hash + "？",
        "sharefile": "分享" + data.filename + "？",
        // dialog
        "nofetchtokeninfo": "无法获取代币数据。",
        "archiverequest": "存档请求？",
        "unarchiverequest": "取消存档？",
        "failedtofetchrequest": "无法获取请求",
        "downloadwallet": "下载" + data.currency + "钱包",

        // ADD ADDRESS
        "alreadyexists": "地址已存在",
        "addaddress": "添加地址",
        "adderc20token": "添加ERC20代币",
        "erc20placeholder": "选择ERC20代币",
        "enteraddress": "输入地址",
        "noaddressyet": "我还没有" + data.currency + "地址",

        // ADDRESS INFO
        "showrequests": "显示请求",
        "newrequest": "新建请求",
        "addressinfo": "地址信息",
        "editlabel": "编辑标签",
        "removeaddress": "移除地址",
        "recentpayments": "最近的付款",
        "privatekey": "私钥",
        "secretviewkey": "秘密查看密钥",
        "secretspendkey": "秘密支出密钥",

        // REQUEST INFO
        "currency": "币种",
        "from": "来自",
        "title": "描述",
        "amount": "金额",
        "status": "状态",
        "Waiting for payment": "等待付款",
        "paid": "已支付",
        "received": "已收到",
        "insufficient": "金额不足",
        "new": "新建",
        "pending": "待处理",
        "canceled": "已取消",
        "expired": "已过期",
        "type": "类型",
        "created": "创建时间",
        "firstviewed": "首次查看",
        "sendon": "请求发送于",
        "paidon": "支付于",
        "amountreceived": "收到金额",
        "amountpaid": "支付金额",
        "fiatvalue": "法币价值",
        "fiatvalueon": "法币价值于",
        "receivingaddress": "收款地址",
        "fallbackaddress": "备用地址",
        "paymentid": "Payment ID",
        "integratedaddress": "集成地址",
        "network": "网络",
        "incoming": "收入",
        "outgoing": "支出",
        "point of sale": "收银终端",
        "online purchase": "在线购买",
        "transactions": "交易",
        "viewon": "查看于",
        "source": "来源",
        "deleterequest": "删除请求",

        // REQUEST PANEL
        "sharerequest": "分享请求",
        "openwallet": "打开钱包",
        "whatsyourname": "您的姓名？",
        "whatsitfor": "用途是什么？",
        "forexample": "例如",
        "send": "发送",
        "to": "至",
        "nodetection": "未检测到付款",
        "lookuppayment": "在" + data.blockexplorer + "上查找最近的" + data.currency + "收入",
        "dontshowagain": "不再显示",
        "dismiss": "关闭",
        "activateintegrated": "激活集成地址",
        "pendingrequest": "待处理请求",
        "paymentsent": "付款已发送",
        "paymentreceived": "付款已收到",
        "txbroadcasted": "交易已广播",
        "insufficientamount": "金额不足",
        "txexpired": "请求已过期",
        "viewdetails": "查看详情",
        "showqr": "显示二维码",
        "waitingfor": "等待",
        "unconfirmedtx": "未确认交易",
        "amountshort": "不足",
        "sharelocktitle": "暂时无法分享请求。",
        "sharelockttext": "此地址有一个<span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>待处理的已分享请求</span>。",
        "waitforconfirm": "请等待交易确认后再重复使用此地址。",
        "pickanotheraddress": "选择其他地址：",
        // ** request suggestion placeholders ** //
        "lunch": "午餐",
        "festivaltickets": "音乐节门票",
        "coffee": "咖啡",
        "present": "礼物",
        "snowboarding": "滑雪",
        "movietheater": "电影院",
        "shopping": "购物",
        "videogame": "电子游戏",
        "drinks": "饮品",
        "concerttickets": "演唱会门票",
        "camping": "露营",
        "taxi": "出租车",
        "zoo": "动物园",
        // notifications
        "failedhistoric": "无法获取" + data.ccsymbol + "历史价格数据",
        "closingsockets": "正在关闭连接...",
        "nowriteaccess": "LNurl代理访问被拒绝，请检查文件夹权限",
        "notmonitored": "此地址未被监控",
        "lnoffline": "Lightning节点离线",
        "addlightningnode": "添加Lightning节点",
        "addressinuse": "地址使用中",
        "minimal2": "描述至少需要2个字符",
        "minimal3": "姓名至少需要3个字符",
        "checkyourform": "请检查您的表单",
        "entertitle": "请输入描述",
        "latincharacters": "仅允许输入字母 (A-Z)、数字和符号",
        "successshare": "分享成功！",
        // confirm
        "opencoinsettings": "打开" + data.currency + "设置？",
        "viewpendingrequest": "查看待处理请求？",
        "useinstead": "改用'" + data.thisinputvalue + "'？",
        "generatenewaddress": "确定要生成新的" + data.currency + "地址吗？部分钱包可能无法显示",
        // dialog
        "undefinedaddress": "地址未定义，请重新发送请求",
        "invalidaddress": "无效的" + data.payment + "地址",

        // SHARE REQUEST
        "share": "分享",
        "sharetitlename": (data.requestname === "Bitrequest") ? "您好，我创建了一个" + data.pagenameccparam + " Bitrequest收款请求，金额为" + data.amount + " " + data.uoa + "，用途：'" + data.requesttitle + "'" : data.requestname + "发送了一个" + data.pagenameccparam + " Bitrequest收款请求，金额为" + data.amount + " " + data.uoa + "，用途：'" + data.requesttitle + "'",
        "sharetitle": data.pagenameccparam + "收款请求，金额" + data.amount + " " + data.uoa,
        "sharetitlechange": data.payment + "请求，金额" + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "您的姓名",
        "currencysettings": "本地法币",
        "entercurrency": "输入货币",
        "setasdefault": "设为默认",
        "langsettings": "语言",
        "chooselanguage": "选择语言",
        "themesettings": "主题",
        "choosetheme": "选择主题",
        "security": "安全",
        "pinsettings": "PIN锁",
        "bip39_passphrase": "助记词",
        "backupsecretphrase": "备份助记词",
        "missingkeywarning": "'<span class='adspan'>" + data.address + "</span>'的" + data.seedstrtitle + "缺失。<br/>确定要使用此地址吗？",
        "emptyphrase": "请输入您的助记词",
        "notinwordlist": data.missing_word + "不在词库中",
        "notbip39compatible": "助记词不兼容BIP39",
        "mustbe12characters": "助记词必须为12个单词",
        "cannotsendfunds": "Bitrequest无法发送资金！",
        "importtosend": "如需发送资金，请在兼容BIP39的钱包中恢复您的<span class='show_bip39 ref'>12个助记词</span>：",
        "backup": "备份应用数据",
        "backupwithgd": "通过Google Drive备份：",
        "nrchanges": "您的应用有" + data.nr_changes + "项更改，请备份您的数据。",
        "changein": "项更改于",
        "changesin": "项更改于",
        "systembackup": "系统备份",
        "downloadbu": "下载备份",
        "installlbu": "安装备份",
        "restore": "恢复应用数据",
        "restorewithgd": "从Google Drive恢复：",
        "lastrestore": "上次恢复：",
        "lastbackup": "上次备份：",
        "restorefromfile": "从文件恢复",
        "differentsecretphrase": "警告：备份包含不同的助记词。",
        "secretphrasefrombackup": "备份中的助记词",
        "currentsecretphrase": "当前助记词",
        "usesecretphrasefrombackup": "使用备份中的助记词",
        "keepcurrentsecretphrase": "保留当前助记词",
        "comparesecretphrases": "比较助记词",
        "csvexport": "导出CSV",
        "includearchive": "包含存档",
        "includereceipt": "包含收据",
        "receipt": "收据",
        "advanced": "高级",
        "url_shorten_settings": "短链接",
        "shorturlnotfound": "请求未找到",
        "cmcapisettings": "加密货币价格数据",
        "fiatapisettings": "法币价格数据",
        "api_proxy": "API代理",
        "updateproxy": "请更新您的代理服务器 " + data.version + " > " + data.proxy_version,
        "addapiproxy": "添加API代理",
        "controlyourkeys": "管理您自己的密钥和请求限制：",
        "proxystep1": "将<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API代理文件夹</a>托管在您的服务器上（需要PHP）。",
        "proxystep2": "在'config.php'中输入您的API密钥。",
        "proxystep3": "在下方输入您的服务器地址。",
        "addrpcproxy": "添加RPC代理",
        "tryotherproxy": "尝试其他代理",
        "apikeys": "API密钥",
        "apicallfailed": "API调用失败",
        "apididnotrespond": "API未响应",
        "contactform": "联系表单",
        "shipping": "收货信息",
        "yourdetails": "您的在线购物信息。",
        "permissions": "权限",
        "teaminvite": "团队邀请",
        "inviteteammembers": "邀请团队成员（员工等）代您创建收款请求。",
        "teaminviteexplainer": "这将在团队成员的设备上安装Bitrequest，预装您的公钥并限制访问权限（收银员）。",
        "teaminviteaccess": "您的团队成员无法访问资金或更改设置。",
        "teaminviteharetitle": "来自" + data.accountname + "的Bitrequest团队邀请",
        "teamupdate": "团队更新",
        "invitationexpiresin": "邀请过期时间",
        "installcompleted": "安装已完成！",
        "teamup": data.account + "邀请您一起协作并共同创建收款请求！",
        "teamupdata": data.account + "希望您使用最新的公钥更新Bitrequest",
        "clickinstall": "点击安装后，Bitrequest将使用" + data.account + "的公钥和受限访问权限安装到您的设备上。",
        // notifications
        "nameisrequired": "姓名为必填项",
        "currencysaved": "货币已保存",
        "currencynotsupported": "不支持货币'" + data.currency + "'",
        "noiosbu": "iOS应用下载暂不可用",
        "downloaded": data.file + "已下载",
        "filesize": "文件过大",
        "filetype": "不支持文件类型'" + data.filetype + "'",
        "selectbackup": "选择备份文件",
        "unauthorized": "未授权",
        "maxattempts": "超过最大尝试次数",
        "fourdigitpin": "请输入4位PIN码",
        "wrongpin": "PIN码错误",
        "nocsvexports": "没有可导出的请求",
        "validateapikey": "请输入有效的API密钥",
        "unabletopost": "无法从" + data.fixed_url + "发送Post请求",
        "invalidapikey": "无效的API密钥",
        "apicallerror": "API调用错误",
        "invalidapikeyname": "无效的" + data.thisref + " API密钥",
        "addapikey": "添加" + data.apisrc + " API密钥",
        "phname": "姓名",
        "phaddress": "地址",
        "phzipcode": "邮编",
        "phcity": "城市",
        "phcountry": "国家",
        "phemail": "邮箱",
        "invalidchars": "包含无效字符",
        "pleaseverify": "请验证您的助记词。",
        "owndevice": "无法在自己的设备上安装邀请",
        "installcomplete": "安装完成！",
        // confirm
        "includesecretphrase": "在备份中包含加密的助记词吗？请确保妥善保管备份文件！",
        "sharebu": "分享系统备份？",
        "installsb": "安装系统备份？所有当前应用数据将被替换",
        "downloadfile": "下载：" + data.file + "？",
        "restorefile": "恢复：" + data.file + "？",
        "restorefromdevice": "从" + data.device + "设备恢复" + data.file + "？",
        "restorewithoutsecretphrase": "不含助记词恢复？",
        "keepexistingsecretphrase": "确定要保留现有助记词吗？",
        "sharecsvexport": "分享CSV导出？",
        "disableshorturls": "确定要禁用短链接吗？这可能影响应用的工作流程",
        "sendinvite": "发送邀请",
        "updatealert": "更新？您所有的公钥将被更新。",
        "installalert": "安装？您所有的公钥将被替换。",

        // COIN SETTINGS
        "confirmations": "确认数",
        "showsatoshis": "显示聪",
        "Use random address": "使用随机地址",
        "Share viewkey": "分享Viewkey",
        "Integrated addresses": "集成地址",
        "Reuse address": "重复使用地址",
        "blockexplorers": "区块浏览器",
        "chooseblockexplorer": "选择区块浏览器",
        "apis": "APIs",
        "addapi": "添加" + data.h_hint + " RPC：",
        "websockets": "Websockets",
        "addwebsocket": "添加" + data.h_hint + " Websocket：",
        "layer2": "二层网络",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32扩展公钥",
        "addxpub": "添加" + data.currency + " Xpub密钥",
        "xpubmatch": "以上地址与我的" + data.currency + "钱包中的地址一致。",
        "xpubkeys": "我拥有助记词 / Xpriv密钥",
        "Key derivations": "密钥派生",
        "derivationpath": "派生路径",
        "soundbytes": "提示音",
        "choosesoundbytes": "选择提示音",
        "resetbutton": "重置",
        // notifications
        "unabletoconnect": "无法连接",
        "nodealreadyadded": "节点已添加",
        "removedefaultnode": "无法移除默认节点",
        "rpcnoderemoved": "RPC节点已移除",
        "confirmmatch": "确认地址匹配",
        "confirmpkownership": "确认私钥所有权",
        "invalidxpub": "不是有效/支持的" + data.currency + " Xpub密钥",
        "xpubsaved": "Xpub已保存",
        "resetnotify": data.currency + "设置已恢复默认",
        // confirm
        "reusewarningalert": "确定要生成新的" + data.thiscurrency + "地址吗？部分钱包可能无法显示。",
        "reusealert": "确定要重复使用" + data.thiscurrency + "地址吗？",
        "confirmremovenode": "确定要移除'" + data.thisval + "'吗？",
        "disablexpub": "禁用Xpub地址派生？",
        "replacexpub": "替换Xpub？",
        "uselegacy": "使用" + data.thiscurrency + " Legacy地址？",
        "usesegwit": "使用" + data.thiscurrency + " SegWit地址？",
        "resetconfirm": "确定要重置" + data.currency + "设置吗？",
        // dialog
        "resetdialog": "重置" + data.currency + "设置？",

        // LIGHTNING
        "Lightning network": "Lightning网络",
        "lightningnode": "Lightning节点",
        "addnode": "添加节点",
        "implementation": "实现方式",
        "tabyourboldcard": "请将Boltcard贴近设备背面",
        "controlyourlnkeys": "管理您自己的Lightning节点和密钥：",
        "lnnodestep1": "将<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>代理文件夹</a>托管在您的Web服务器上。",
        "lnnodestep2": "在'config.php'中输入您的Lightning节点的REST主机和密钥。",
        "lnnodestep3": "在下方输入您的服务器地址。",
        "enterlnapikey": "输入代理API密钥以解锁'" + data.proxy + "'",
        "viewinvoice": "查看Invoice",
        "noinvoicesfound": "未找到Invoice。",
        "invoiceslocked": "节点代理已锁定，无法获取Invoice。<br/>请输入您的代理<span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>API密钥</span>。",
        "invoiceoffline": "节点离线，无法获取Invoice。",
        // notifications
        "nodenotfound": "未找到节点",
        "proxynotfound": "未找到代理",
        "enterserver": "请输入服务器地址",
        "defaultproxy": data.fixed_url + "是默认代理",
        "proxyexists": "代理已添加",
        "invalidurl": "无效的URL",
        "selectimplementation": "选择实现方式",
        "selectlnhost": "选择" + data.imp + "主机",
        "selectkeyname": "选择" + data.impkeyname,
        "entermacaroon": "请输入'invoice' Macaroon",
        "invalidkeyformat": "无效的密钥格式",
        "proxylocked": "当前节点代理已锁定，请输入API密钥",
        "proxyoffline": "当前节点离线，请尝试" + data.proxy_message + "代理",
        "folderpermissions": "无法写入缓存，请检查文件夹权限。",
        "proxyadded": "代理已添加",
        "unabletoconnectto": "无法连接到" + data.value,
        "proxynameexists": data.imp + "节点已添加",
        "proxyinuse": data.imp + "：'" + data.name + "'正在使用此代理，请先移除",
        "proxyremoved": "代理已移除",
        "serviceremoved": "服务已移除",
        "unknownproxy": "未知的代理服务器",
        "proxyunlocked": "代理已解锁！",
        "proxydatamissing": "代理数据缺失",
        "invoicecanceled": "Invoice已取消",
        // confirm
        "enablelightning": "启用Lightning支付？",
        "disablelightning": "禁用Lightning支付？",
        "disableproxy": "禁用代理" + data.set_proxy_val + "？",
        "enableproxy": "启用代理" + data.set_proxy_val + "？",
        // dialog
        "unabletoconnectln": "无法连接Lightning节点",

        // BIP39
        "disclaimer": "免责声明！",
        "cannotbespend": "通过助记词生成的地址所收到的资金无法通过Bitrequest支出。<br/>如需使用资金，请在<a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>兼容的钱包</a>中恢复助记词。",
        "compatiblewallets": "兼容的钱包",
        "important": "重要！",
        "abouttobecome": "您即将成为自己的银行。",
        "inthenextscreen": "在下一个页面中，您将看到您的助记词。",
        "makesure": "请务必抄写下来并妥善保管！",
        "understandandok": "我理解并同意。",
        "entersecretphrase": "输入您的助记词：",
        "writedownsecretphrase": "抄写您的助记词并妥善保管。",
        "ifyouloseyourphrase": "如果您丢失了助记词，<br/>您将失去您的资金！",
        "understand": "我明白了！",
        "verifycurrent": "验证当前助记词：",
        "verifybackup": "验证备份：",
        "withgreatpower": "能力越大，责任越大。",
        "remember": "请记得备份您的<span id='toseed'>助记词</span>。",
        "overwritten": "请先备份您当前的<span id='toseed'>助记词</span>，它将被覆盖",
        "word": "单词",
        "idothislater": "稍后再说",
        "ivebackeditup": "我已备份！",
        "next": "下一步",
        "prev": "上一步",
        "findmorewallets": "查找更多钱包",
        // notifications
        "alreadyhavesecretphrase": "您已有助记词",
        "wrongsecretphrase": "助记词错误",
        "consent": "请同意后继续。",
        "secretphrasedeleted": "助记词已删除",
        "congratulations": "恭喜！您现在是自己的银行了！",
        "passphraseverified": "助记词已验证",
        "backupasap": "请尽快备份您的助记词",
        // confirm
        "resoresecretphrase": "恢复助记词",
        "areyousuredfp": "确定要删除助记词吗？",
        "restoresecretphrasefrombackup": "确定要从备份恢复助记词吗？当前助记词将被删除。",
        // dialog
        "continueatownrisk": "警告！继续操作风险自负。",
        "ifyouloseyourdevice": "如果您丢失设备、卸载应用或清除浏览器数据，您需要助记词来恢复资金！",
        "deletingyoursecretphrase": "警告！删除助记词可能导致资金丢失。",
        "continuewithbackup": "仅在您已备份助记词的情况下继续。",

        // SOCKETS
        // notifications
        "youareoffline": "您当前处于离线状态",
        "networks": "网络",
        "acceptthepayment": "请在Lightning应用中接受付款...",
        "ndeftablimit": "操作过快",
        "enteramount": "请输入金额",
        "cardmax": "请求超过卡片限额",
        "minamount": "最低请求金额为" + data.min,
        "waitingforpayment": "等待付款",
        "websocketoffline": "节点离线",

        // PIN PANEL
        "pleaseenter": "请输入PIN码",
        "createpin": "创建4位PIN码",
        "locktime": "锁定时间",
        "resetpin": "重置PIN",
        "enternewpin": "输入新PIN码",
        "minute": "分钟",
        "minutes": "分钟",
        "never": "从不",
        "pincodeactivated": "PIN码已激活",
        "pincodedisabled": "PIN码已禁用",
        "confirmyourpin": "确认您的PIN码",

        // LOCKSCREEN
        "unlockwithsecretphrase": "使用助记词解锁",
        "tomanyunlocks": "解锁尝试次数过多",
        "enter12words": "输入您的12个<br/>助记词：",
        "tryagainin": "请稍后再试",
        "unlock": "解锁",

        // BUTTONS AND PANELS
        "cancelbttn": "取消",
        "okbttn": "确定",
        "show": "显示",
        "hide": "隐藏",
        "delete": "删除",
        "restorebttn": "恢复",
        "showtransactions": "显示交易",
        "sharerequestbutton": "分享请求",
        "addcoinaddress": "添加" + data.currency + "地址",
        "generatewallet": "从助记词创建钱包。",
        "pkownership": "我拥有此地址的私钥。",
        "nopub": "地址 / Xpub",
        "update": "更新",
        "install": "安装",
        "pay": "支付",

        //DIALOGS
        "totalchanges": "您的应用有" + data.total_changes + "项更改",
        "nochanges": "您的应用有0项更改",
        "havewallet": "您的设备上有" + data.lnd_ref + "钱包吗？",

        // DATES
        "sunday": "星期日",
        "monday": "星期一",
        "tuesday": "星期二",
        "wednesday": "星期三",
        "thursday": "星期四",
        "friday": "星期五",
        "saturday": "星期六",
        "year": "年",
        "years": "年",
        "month": "月",
        "months": "个月",
        "week": "周",
        "weeks": "周",
        "day": "天",
        "days": "天",
        "hour": "小时",
        "hours": "小时",
        "minute": "分钟",
        "minutes": "分钟",
        "seconds": "秒",
        "and": "和",
        "expiresin": "过期时间：",
        "fileexpired": "文件已过期",

        // LOADERTEXT
        "generatereceipt": "生成收据",
        "connecttolnur": "正在连接" + data.url,
        "loadurl": "正在加载" + data.url,
        "loading": "加载中...",
        "gettokeninfo": "获取代币信息",
        "checklightningstatus": "检查" + data.imp + " Lightning状态",
        "readingfromcache": "从缓存读取" + data.ccsymbol + "汇率",
        "getccrates": "从" + data.api + "获取" + data.ccsymbol + "汇率",
        "getfiatrates": "获取法币汇率",
        "readingfiatratesfromcache": "从缓存读取法币汇率",
        "fetchingfiatrates": "从" + data.fiatapi + "获取法币汇率",
        "generatelink": "正在生成链接",
        "loadingcamera": "正在加载相机",
        "generatebu": "生成系统备份",
        "installationpackage": "生成安装包",

        // RANDOM TERMS
        "address": "地址",
        "choose": "选择",
        "enable": "启用",
        "disable": "禁用",
        "apikey": "API密钥",
        "yes": "是",
        "no": "否",
        "none": "无",
        "verified": "已验证",
        "error": "错误",
        "apierror": "API错误",
        "success": "成功",
        "warning": "警告！",
        "edit": "编辑",
        "enter": "输入",

        // CHECK INTENTS
        "proto": data.proto + "：连接暂不可用",
        "invalidurlscheme": "无效的URL方案",
        "usnotsupported": "不支持URL方案'" + data.proto + ":'",

        // GOOGLE AUTH
        "stopgauth": "停止使用Google Drive备份。",
        "gauthsafely": "安全备份您的应用数据。",
        "gauthsync": "使用Google Drive安全同步您的数据。",
        "signin": "登录",
        "backuptogd": "备份到Google Drive",
        // notifications
        "ganot": "GoogleAuth不可用",
        "gdsignedin": "登录成功",
        "gdsignedout": "退出成功",
        "filedeleted": "文件已删除",
        "filenotfound": "文件未找到",
        // confirm
        "stopgdalert": "确定要停止使用Google Drive备份吗？",
        "deletefile": "删除" + data.file + "？"
    }
    return translation[id];
}
