// assets_js_bitrequest_lang_ja.js
function lang_ja(id, data) {
    const translation = {
        "payoff": "どこでも暗号資産決済",

        // PAGES
        "home": "ホーム",
        "currencies": "通貨",
        "requests": "リクエスト",
        "settings": "設定",
        "coinsettings": "通貨設定",
        "addresses": "アドレス",

        // INTRO
        "enteryourname": "名前を入力してください",
        "more": "もっと見る",
        "restorefrombackup": "バックアップから復元",

        // CORE
        // notifications
        "datasaved": "データを保存しました",
        "pinmatch": "PINコードが一致しません",
        "xratesx": "為替レートを取得できません",
        "entercoinaddress": data.currency + "アドレスを入力してください。",
        "label": "ラベル（任意）",
        "errorvk": "Viewkeyの検証エラー",
        "invalidvk": "無効なViewkey",
        "continuevk": "Viewkeyなしで続行しますか？Viewkeyがないと取引を監視できません。",
        "novalidaddress": "は有効な" + data.currency + "アドレスではありません。",
        "pickacurrency": "通貨を選択",
        "invalidlabel": "無効なラベル",
        "noactivecurrencies": "有効な通貨がありません",
        "addressremoved": "アドレスを削除しました",
        "movedtoarchive": "アーカイブに移動しました",
        "requestrestored": "リクエストを復元しました",
        "requestdeleted": "リクエストを削除しました",
        "requestsaved": "リクエストを保存しました",
        "requiredfields": "必須項目を入力してください",
        "requiredfield": "は必須項目です",
        "requestinginvoice": "インボイスを取得中...",
        "nofetchincoice": "インボイスを取得できません。",
        "copy": "コピー",
        "copied": "クリップボードにコピーしました",
        "xcopy": "コピーできません",
        "cashiernotallowed": "キャッシャーモードでは許可されていません",
        "decodeqr": "QRを読み取れません",
        "invalidformat": "無効な形式です",
        "invalidmacaroon": "無効なmacaroon形式です",
        "recentrequests": "最近のリクエスト",
        "encodeyoraddress": "bitrequest.io/qr でアドレスをエンコード",
        // confirm
        "openurl": data.url + "を開きますか？",
        "showrequestsfor": data.address + "のリクエストを表示しますか？",
        "areyousure": "よろしいですか？",
        "openinvoice": "インボイスを開く: " + data.hash + "？",
        "sharefile": data.filename + "を共有しますか？",
        // dialog
        "nofetchtokeninfo": "トークン情報を取得できません。",
        "archiverequest": "リクエストをアーカイブしますか？",
        "unarchiverequest": "アーカイブを解除しますか？",
        "failedtofetchrequest": "リクエストの取得に失敗しました",
        "downloadwallet": data.currency + "ウォレットをダウンロード",

        // ADD ADDRESS
        "alreadyexists": "アドレスは既に存在します",
        "addaddress": "アドレスを追加",
        "adderc20token": "ERC20トークンを追加",
        "erc20placeholder": "ERC20トークンを選択",
        "enteraddress": "アドレスを入力",
        "noaddressyet": "まだ" + data.currency + "アドレスを持っていません",

        // ADDRESS INFO
        "showrequests": "リクエストを表示",
        "newrequest": "新しいリクエスト",
        "addressinfo": "アドレス情報",
        "editlabel": "ラベルを編集",
        "removeaddress": "アドレスを削除",
        "recentpayments": "最近の支払い",
        "privatekey": "秘密鍵",
        "secretviewkey": "秘密View key",
        "secretspendkey": "秘密Spend key",

        // REQUEST INFO
        "currency": "通貨",
        "from": "送信元",
        "title": "説明",
        "amount": "金額",
        "status": "ステータス",
        "Waiting for payment": "支払い待ち",
        "paid": "支払い済み",
        "received": "受領済み",
        "insufficient": "不足",
        "new": "新規",
        "pending": "保留中",
        "canceled": "キャンセル",
        "expired": "期限切れ",
        "type": "タイプ",
        "created": "作成日",
        "firstviewed": "初回表示",
        "sendon": "リクエスト送信日",
        "paidon": "支払日",
        "amountreceived": "受領額",
        "amountpaid": "支払額",
        "fiatvalue": "法定通貨換算",
        "fiatvalueon": "法定通貨換算日時",
        "receivingaddress": "受取アドレス",
        "fallbackaddress": "フォールバックアドレス",
        "paymentid": "Payment ID",
        "integratedaddress": "統合アドレス",
        "network": "ネットワーク",
        "incoming": "入金",
        "outgoing": "出金",
        "point of sale": "POS",
        "online purchase": "オンライン購入",
        "transactions": "取引",
        "viewon": "表示先",
        "source": "ソース",
        "deleterequest": "リクエストを削除",

        // REQUEST PANEL
        "sharerequest": "リクエストを共有",
        "openwallet": "ウォレットを開く",
        "whatsyourname": "お名前は？",
        "whatsitfor": "何の支払いですか？",
        "forexample": "例",
        "send": "送信",
        "to": "宛先",
        "nodetection": "支払いが検出されません",
        "lookuppayment": data.blockexplorer + "で最近の" + data.currency + "入金を検索",
        "dontshowagain": "今後表示しない",
        "dismiss": "閉じる",
        "activateintegrated": "統合アドレスを有効化",
        "pendingrequest": "保留中リクエスト",
        "paymentsent": "支払いを送信しました",
        "paymentreceived": "支払いを受け取りました",
        "txbroadcasted": "トランザクションを送信しました",
        "insufficientamount": "金額不足",
        "txexpired": "リクエストの有効期限切れ",
        "viewdetails": "詳細を見る",
        "showqr": "QRコードを表示",
        "waitingfor": "待機中",
        "unconfirmedtx": "未承認トランザクション",
        "amountshort": "不足",
        "sharelocktitle": "一時的にリクエストを共有できません。",
        "sharelockttext": "このアドレスには<span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>共有中の保留リクエスト</span>があります。",
        "waitforconfirm": "アドレスを再利用する前に、取引の承認を待ってください。",
        "pickanotheraddress": "別のアドレスを選択:",
        // ** request suggestion placeholders ** //
        "lunch": "ランチ",
        "festivaltickets": "フェスチケット",
        "coffee": "コーヒー",
        "present": "プレゼント",
        "snowboarding": "スノーボード",
        "movietheater": "映画館",
        "shopping": "ショッピング",
        "videogame": "ビデオゲーム",
        "drinks": "ドリンク",
        "concerttickets": "コンサートチケット",
        "camping": "キャンプ",
        "taxi": "タクシー",
        "zoo": "動物園",
        // notifications
        "failedhistoric": "過去の" + data.ccsymbol + "価格データの取得に失敗しました",
        "closingsockets": "接続を閉じています...",
        "nowriteaccess": "LNurl proxy へのアクセスが拒否されました。フォルダ権限を確認してください",
        "notmonitored": "このアドレスは監視されていません",
        "lnoffline": "Lightning node はオフラインです",
        "addlightningnode": "Lightning node を追加",
        "addressinuse": "アドレスは使用中です",
        "minimal2": "説明は2文字以上必要です",
        "minimal3": "名前は3文字以上必要です",
        "checkyourform": "入力内容を確認してください",
        "entertitle": "説明を入力してください",
        "latincharacters": "英字（A-Z）、数字、記号のみ入力できます",
        "successshare": "共有しました！",
        // confirm
        "opencoinsettings": data.currency + "設定を開きますか？",
        "viewpendingrequest": "保留中リクエストを表示しますか？",
        "useinstead": "'" + data.thisinputvalue + "'を代わりに使いますか？",
        "generatenewaddress": "新しい" + data.currency + "アドレスを生成しますか？一部ウォレットでは表示されない場合があります",
        // dialog
        "undefinedaddress": "未定義のアドレスです。新しいリクエストを作成してください",
        "invalidaddress": "無効な" + data.payment + "アドレスです",

        // SHARE REQUEST
        "share": "共有",
        "sharetitlename": (data.requestname === "Bitrequest") ? "こんにちは、'" + data.requesttitle + "' のために " + data.amount + " " + data.uoa + " の " + data.pagenameccparam + " Bitrequest を作成しました" : data.requestname + " が '" + data.requesttitle + "' のために " + data.amount + " " + data.uoa + " の " + data.pagenameccparam + " Bitrequest を送信しました",
        "sharetitle": data.pagenameccparam + " 支払いリクエスト " + data.amount + " " + data.uoa,
        "sharetitlechange": data.payment + " リクエスト " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "あなたの名前",
        "currencysettings": "ローカル法定通貨",
        "entercurrency": "通貨を入力",
        "setasdefault": "デフォルトに設定",
        "langsettings": "言語",
        "chooselanguage": "言語を選択",
        "themesettings": "テーマ",
        "choosetheme": "テーマを選択",
        "security": "セキュリティ",
        "pinsettings": "PINロック",
        "bip39_passphrase": "シークレットフレーズ",
        "backupsecretphrase": "シークレットフレーズをバックアップ",
        "missingkeywarning": "'<span class='adspan'>" + data.address + "</span>' の " + data.seedstrtitle + " が見つかりません。<br/>このアドレスを使用しますか？",
        "emptyphrase": "シークレットフレーズを入力してください",
        "notinwordlist": data.missing_word + " は単語リストにありません",
        "notbip39compatible": "シークレットフレーズはBIP39非対応です",
        "mustbe12characters": "シークレットフレーズは12語である必要があります",
        "cannotsendfunds": "Bitrequestは送金できません！",
        "importtosend": "送金するには、<span class='show_bip39 ref'>12語のシークレットフレーズ</span>をBIP39対応ウォレットで復元してください:",
        "backup": "アプリデータをバックアップ",
        "backupwithgd": "Google Driveでバックアップ:",
        "nrchanges": "アプリに" + data.nr_changes + "件の変更があります。データをバックアップしてください。",
        "changein": "変更:",
        "changesin": "変更:",
        "systembackup": "システムバックアップ",
        "downloadbu": "バックアップをダウンロード",
        "installlbu": "バックアップをインストール",
        "restore": "アプリデータを復元",
        "restorewithgd": "Google Driveから復元:",
        "lastrestore": "最終復元:",
        "lastbackup": "最終バックアップ:",
        "restorefromfile": "ファイルから復元",
        "differentsecretphrase": "警告。バックアップに別のシークレットフレーズが含まれています。",
        "secretphrasefrombackup": "バックアップのシークレットフレーズ",
        "currentsecretphrase": "現在のシークレットフレーズ",
        "usesecretphrasefrombackup": "バックアップのシークレットフレーズを使用",
        "keepcurrentsecretphrase": "現在のシークレットフレーズを保持",
        "comparesecretphrases": "シークレットフレーズを比較",
        "csvexport": "CSVをエクスポート",
        "includearchive": "アーカイブを含める",
        "includereceipt": "レシートを含める",
        "receipt": "レシート",
        "advanced": "詳細設定",
        "url_shorten_settings": "URL短縮",
        "shorturlnotfound": "リクエストが見つかりません",
        "cmcapisettings": "暗号資産価格データ",
        "fiatapisettings": "法定通貨価格データ",
        "api_proxy": "API Proxy",
        "updateproxy": "proxyサーバーを更新してください " + data.version + " > " + data.proxy_version,
        "addapiproxy": "API proxy を追加",
        "controlyourkeys": "自分のキーとリクエスト上限を管理:",
        "proxystep1": "サーバー上に<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API proxy folder</a>を配置してください（PHP必須）。",
        "proxystep2": "'config.php' にAPIキーを入力します。",
        "proxystep3": "下にサーバーアドレスを入力します。",
        "addrpcproxy": "RPC proxy を追加",
        "tryotherproxy": "別のproxyを試す",
        "apikeys": "APIキー",
        "apicallfailed": "API呼び出しに失敗しました",
        "apididnotrespond": "APIが応答しませんでした",
        "contactform": "お問い合わせフォーム",
        "shipping": "配送",
        "yourdetails": "オンライン購入用の情報",
        "permissions": "権限",
        "teaminvite": "チーム招待",
        "inviteteammembers": "チームメンバー（スタッフ等）を招待して、あなたの代わりにリクエストを作成できます。",
        "teaminviteexplainer": "チームメンバーの端末にBitrequestをインストールし、公開鍵と制限付きアクセス（cashier）を設定します。",
        "teaminviteaccess": "チームメンバーは資金にアクセスしたり設定変更したりできません。",
        "teaminviteharetitle": data.accountname + " からの Bitrequest チーム招待",
        "teamupdate": "チーム更新",
        "invitationexpiresin": "招待の有効期限",
        "installcompleted": "インストールは既に完了しています！",
        "teamup": data.account + " があなたと協力して一緒にリクエスト作成したいようです！",
        "teamupdata": data.account + " が最新の公開鍵でbitrequestを更新するよう求めています",
        "clickinstall": "インストールを押すと、" + data.account + " の公開鍵と制限付きアクセスでbitrequestが端末にインストールされます。",
        // notifications
        "nameisrequired": "名前は必須です",
        "currencysaved": "通貨を保存しました",
        "currencynotsupported": "通貨 '" + data.currency + "' は未対応です",
        "noiosbu": "iOSアプリ向けダウンロードは現在利用できません",
        "downloaded": data.file + " をダウンロードしました",
        "filesize": "ファイルサイズが大きすぎます",
        "filetype": "ファイル形式 '" + data.filetype + "' は未対応です",
        "selectbackup": "バックアップファイルを選択",
        "unauthorized": "未認証",
        "maxattempts": "最大試行回数を超えました",
        "fourdigitpin": "4桁のPINを入力してください",
        "wrongpin": "PINが違います",
        "nocsvexports": "エクスポートするリクエストがありません",
        "validateapikey": "有効なAPIキーを入力してください",
        "unabletopost": data.fixed_url + " からPostリクエストを送信できません",
        "invalidapikey": "無効なAPIキー",
        "apicallerror": "API呼び出しエラー",
        "invalidapikeyname": "無効な " + data.thisref + " APIキー",
        "addapikey": data.apisrc + " APIキーを追加",
        "phname": "名前",
        "phaddress": "住所",
        "phzipcode": "郵便番号",
        "phcity": "市区町村",
        "phcountry": "国",
        "phemail": "メール",
        "invalidchars": "に無効な文字が含まれています",
        "pleaseverify": "シークレットフレーズを確認してください。",
        "owndevice": "自身の端末には招待をインストールできません",
        "installcomplete": "インストール完了！",
        // confirm
        "includesecretphrase": "暗号化されたシークレットフレーズをバックアップに含めますか？バックアップファイルを安全に保管してください！",
        "sharebu": "システムバックアップを共有しますか？",
        "installsb": "システムバックアップをインストールしますか？現在のアプリデータはすべて置き換えられます",
        "downloadfile": data.file + " をダウンロードしますか？",
        "restorefile": data.file + " を復元しますか？",
        "restorefromdevice": data.device + " 端末から " + data.file + " を復元しますか？",
        "restorewithoutsecretphrase": "シークレットフレーズなしで復元しますか？",
        "keepexistingsecretphrase": "現在のシークレットフレーズを保持しますか？",
        "sharecsvexport": "CSVエクスポートを共有しますか？",
        "disableshorturls": "URL短縮を無効にしますか？アプリの動作に影響する可能性があります",
        "sendinvite": "招待を送信",
        "updatealert": "更新しますか？現在の公開鍵はすべて更新されます。",
        "installalert": "インストールしますか？現在の公開鍵はすべて置き換えられます。",

        // COIN SETTINGS
        "confirmations": "承認数",
        "showsatoshis": "satoshisを表示",
        "Use random address": "ランダムアドレスを使用",
        "Share viewkey": "viewkeyを共有",
        "Integrated addresses": "統合アドレス",
        "Reuse address": "アドレスを再利用",
        "blockexplorers": "blockexplorers",
        "chooseblockexplorer": "blockexplorerを選択",
        "apis": "APIs",
        "addapi": data.h_hint + " RPCを追加:",
        "websockets": "Websockets",
        "addwebsocket": data.h_hint + " websocketを追加:",
        "layer2": "Layer 2",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32 拡張公開鍵",
        "addxpub": data.currency + " Xpubキーを追加",
        "xpubmatch": "上記アドレスは私の" + data.currency + "ウォレットと一致しています。",
        "xpubkeys": "私はシークレットフレーズ / Xprivキーを保持しています",
        "Key derivations": "キー導出",
        "derivationpath": "導出パス",
        "soundbytes": "サウンド",
        "choosesoundbytes": "サウンドを選択",
        "resetbutton": "リセット",
        // notifications
        "unabletoconnect": "接続できません",
        "nodealreadyadded": "nodeは既に追加されています",
        "removedefaultnode": "デフォルトnodeは削除できません",
        "rpcnoderemoved": "RPC nodeを削除しました",
        "confirmmatch": "アドレス一致を確認してください",
        "confirmpkownership": "秘密鍵の所有を確認してください",
        "invalidxpub": "有効/対応の " + data.currency + " Xpubキーではありません",
        "xpubsaved": "Xpubを保存しました",
        "resetnotify": data.currency + " 設定をデフォルトに戻しました",
        // confirm
        "reusewarningalert": "新しい" + data.thiscurrency + "アドレスを生成しますか？一部ウォレットで表示されない場合があります。",
        "reusealert": data.thiscurrency + "アドレスを再利用しますか？",
        "confirmremovenode": "'" + data.thisval + "' を削除しますか？",
        "disablexpub": "Xpubアドレス導出を無効化しますか？",
        "replacexpub": "Xpubを置き換えますか？",
        "uselegacy": data.thiscurrency + " Legacyアドレスを使用しますか？",
        "usesegwit": data.thiscurrency + " SegWitアドレスを使用しますか？",
        "resetconfirm": data.currency + "設定をリセットしますか？",
        // dialog
        "resetdialog": data.currency + "設定をリセットしますか？",

        // LIGHTNING
        "Lightning network": "Lightning network",
        "lightningnode": "lightning node",
        "addnode": "nodeを追加",
        "implementation": "実装",
        "tabyourboldcard": "Boltcardをこの端末の背面にタップしてください",
        "controlyourlnkeys": "自分のlightning nodeと鍵を管理:",
        "lnnodestep1": "Webサーバーに<a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>proxy folder</a>を配置します。",
        "lnnodestep2": "'config.php' にlightning nodeのRESTホストと鍵を入力します。",
        "lnnodestep3": "下にサーバーアドレスを入力します。",
        "enterlnapikey": "'" + data.proxy + "' を解除するためproxy APIキーを入力",
        "viewinvoice": "インボイスを表示",
        "noinvoicesfound": "インボイスが見つかりません。",
        "invoiceslocked": "node proxyがロックされています。インボイスを取得できません。<br/>proxyの<span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>APIキー</span>を入力してください。",
        "invoiceoffline": "nodeがオフラインのため、インボイスを取得できません。",
        // notifications
        "nodenotfound": "nodeが見つかりません",
        "proxynotfound": "proxyが見つかりません",
        "enterserver": "サーバーアドレスを入力してください",
        "defaultproxy": data.fixed_url + " はデフォルトproxyです",
        "proxyexists": "proxyは既に追加されています",
        "invalidurl": "無効なURL",
        "selectimplementation": "実装を選択",
        "selectlnhost": data.imp + " Hostを選択",
        "selectkeyname": data.impkeyname + " を選択",
        "entermacaroon": "'invoice' macaroonを入力してください",
        "invalidkeyformat": "無効なキー形式です",
        "proxylocked": "現在のnode proxyはロックされています。APIキーを入力してください",
        "proxyoffline": "現在のnodeはオフラインです。" + data.proxy_message + " proxyを試してください",
        "folderpermissions": "キャッシュに書き込めません。フォルダ権限を確認してください。",
        "proxyadded": "proxyを追加しました",
        "unabletoconnectto": data.value + " に接続できません",
        "proxynameexists": data.imp + " nodeは既に追加されています",
        "proxyinuse": data.imp + ": '" + data.name + "' がこのproxyを使用中です。先に削除してください",
        "proxyremoved": "proxyを削除しました",
        "serviceremoved": "サービスを削除しました",
        "unknownproxy": "不明なproxyサーバーです",
        "proxyunlocked": "proxyを解除しました！",
        "proxydatamissing": "proxyデータが不足しています",
        "invoicecanceled": "インボイスをキャンセルしました",
        // confirm
        "enablelightning": "lightning支払いを有効にしますか？",
        "disablelightning": "lightning支払いを無効にしますか？",
        "disableproxy": "proxy " + data.set_proxy_val + " を無効にしますか？",
        "enableproxy": "proxy " + data.set_proxy_val + " を有効にしますか？",
        // dialog
        "unabletoconnectln": "lightning nodeに接続できません",

        // BIP39
        "disclaimer": "免責事項！",
        "cannotbespend": "シークレットフレーズから生成したアドレスで受け取った資金はBitrequestでは送金できません。<br/>送金するには、<a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>対応ウォレット</a>でシークレットフレーズを復元してください。",
        "compatiblewallets": "対応ウォレット",
        "important": "重要！",
        "abouttobecome": "あなたは自分自身の銀行になります。",
        "inthenextscreen": "次の画面でシークレットフレーズが表示されます。",
        "makesure": "必ず書き留めて安全な場所に保管してください！",
        "understandandok": "理解し、同意します。",
        "entersecretphrase": "シークレットフレーズを入力:",
        "writedownsecretphrase": "シークレットフレーズを書き留めて安全な場所に保管してください。",
        "ifyouloseyourphrase": "シークレットフレーズを失うと、<br/>資金を失います！",
        "understand": "理解しました！",
        "verifycurrent": "現在のシークレットフレーズを確認:",
        "verifybackup": "バックアップを確認:",
        "withgreatpower": "大きな力には大きな責任が伴います。",
        "remember": "<span id='toseed'>シークレットフレーズ</span>のバックアップを忘れないでください。",
        "overwritten": "現在の<span id='toseed'>シークレットフレーズ</span>は上書きされます。必ずバックアップしてください",
        "word": "単語",
        "idothislater": "あとで行う",
        "ivebackeditup": "バックアップしました！",
        "next": "次へ",
        "prev": "戻る",
        "findmorewallets": "さらにウォレットを探す",
        // notifications
        "alreadyhavesecretphrase": "すでにシークレットフレーズがあります",
        "wrongsecretphrase": "シークレットフレーズが違います",
        "consent": "続行するには同意してください。",
        "secretphrasedeleted": "シークレットフレーズを削除しました",
        "congratulations": "おめでとうございます。あなたは自分自身の銀行になりました！",
        "passphraseverified": "パスフレーズを確認しました",
        "backupasap": "できるだけ早くシークレットフレーズをバックアップしてください",
        // confirm
        "resoresecretphrase": "シークレットフレーズを復元",
        "areyousuredfp": "シークレットフレーズを削除してもよろしいですか？",
        "restoresecretphrasefrombackup": "バックアップからシークレットフレーズを復元しますか？現在のシークレットフレーズは消去されます。",
        // dialog
        "continueatownrisk": "警告！自己責任で続行してください。",
        "ifyouloseyourdevice": "端末を紛失したり、アプリを削除したり、ブラウザデータを消去した場合、資金復元にはシークレットフレーズが必要です！",
        "deletingyoursecretphrase": "警告！シークレットフレーズを削除すると資金を失う可能性があります。",
        "continuewithbackup": "シークレットフレーズのバックアップがある場合のみ続行してください。",

        // SOCKETS
        // notifications
        "youareoffline": "現在オフラインです",
        "networks": "ネットワーク",
        "acceptthepayment": "lightningアプリで支払いを受け付けてください...",
        "ndeftablimit": "タップが速すぎます",
        "enteramount": "金額を入力してください",
        "cardmax": "リクエストがカード上限を超えています",
        "minamount": "最小リクエスト額は " + data.min,
        "waitingforpayment": "支払い待ち",
        "websocketoffline": "node オフライン",

        // PIN PANEL
        "pleaseenter": "PINを入力してください",
        "createpin": "4桁のPINを作成",
        "locktime": "ロック時間",
        "resetpin": "PINをリセット",
        "enternewpin": "新しいPINを入力",
        "minute": "分",
        "minutes": "分",
        "never": "しない",
        "pincodeactivated": "PINコードを有効化しました",
        "pincodedisabled": "PINコードを無効化しました",
        "confirmyourpin": "PINコードを確認",

        // LOCKSCREEN
        "unlockwithsecretphrase": "シークレットフレーズでロック解除",
        "tomanyunlocks": "ロック解除試行回数が多すぎます",
        "enter12words": "12語の<br/>シークレットフレーズを入力:",
        "tryagainin": "再試行まで",
        "unlock": "ロック解除",

        // BUTTONS AND PANELS
        "cancelbttn": "キャンセル",
        "okbttn": "OK",
        "show": "表示",
        "hide": "非表示",
        "delete": "削除",
        "restorebttn": "復元",
        "showtransactions": "取引を表示",
        "sharerequestbutton": "リクエストを共有",
        "addcoinaddress": data.currency + "アドレスを追加",
        "generatewallet": "シークレットフレーズからウォレットを作成します。",
        "pkownership": "私はこのアドレスの秘密鍵を所有しています。",
        "nopub": "アドレス / Xpub",
        "update": "更新",
        "install": "インストール",
        "pay": "支払う",

        //DIALOGS
        "totalchanges": "アプリに " + data.total_changes + " 件の変更があります",
        "nochanges": "アプリに変更はありません",
        "havewallet": "この端末に " + data.lnd_ref + " ウォレットがありますか？",

        // DATES
        "sunday": "日曜日",
        "monday": "月曜日",
        "tuesday": "火曜日",
        "wednesday": "水曜日",
        "thursday": "木曜日",
        "friday": "金曜日",
        "saturday": "土曜日",
        "year": "年",
        "years": "年",
        "month": "か月",
        "months": "か月",
        "week": "週",
        "weeks": "週",
        "day": "日",
        "days": "日",
        "hour": "時間",
        "hours": "時間",
        "minute": "分",
        "minutes": "分",
        "seconds": "秒",
        "and": "と",
        "expiresin": "有効期限まで ",
        "fileexpired": "ファイルの有効期限切れ",

        // LOADERTEXT
        "generatereceipt": "レシートを生成中",
        "connecttolnur": data.url + " に接続中",
        "loadurl": data.url + " を読み込み中",
        "loading": "読み込み中...",
        "gettokeninfo": "トークン情報を取得中",
        "checklightningstatus": data.imp + " lightningステータスを確認中",
        "readingfromcache": "キャッシュから " + data.ccsymbol + " レートを読み込み中",
        "getccrates": data.api + " から " + data.ccsymbol + " レートを取得中",
        "getfiatrates": "法定通貨レートを取得中",
        "readingfiatratesfromcache": "キャッシュから法定通貨レートを読み込み中",
        "fetchingfiatrates": data.fiatapi + " から法定通貨レートを取得中",
        "generatelink": "リンクを生成中",
        "loadingcamera": "カメラを読み込み中",
        "generatebu": "システムバックアップを生成中",
        "installationpackage": "インストールパッケージを生成中",

        // RANDOM TERMS
        "address": "アドレス",
        "choose": "選択",
        "enable": "有効化",
        "disable": "無効化",
        "apikey": "APIキー",
        "yes": "はい",
        "no": "いいえ",
        "none": "なし",
        "verified": "検証済み",
        "error": "エラー",
        "apierror": "APIエラー",
        "success": "成功",
        "warning": "警告！",
        "edit": "編集",
        "enter": "入力",

        // CHECK INTENTS
        "proto": data.proto + ": 現在接続できません",
        "invalidurlscheme": "無効なURLスキーム",
        "usnotsupported": "URLスキーム '" + data.proto + ":' はサポートされていません",

        // GOOGLE AUTH
        "stopgauth": "Google Driveバックアップの使用を停止。",
        "gauthsafely": "アプリデータを安全にバックアップ。",
        "gauthsync": "Google Driveでデータを安全に同期。",
        "signin": "サインイン",
        "backuptogd": "Google Driveにバックアップ",
        // notifications
        "ganot": "GoogleAuthは利用できません",
        "gdsignedin": "サインインしました",
        "gdsignedout": "サインアウトしました",
        "filedeleted": "ファイルを削除しました",
        "filenotfound": "ファイルが見つかりません",
        // confirm
        "stopgdalert": "Google Driveバックアップの使用を停止しますか？",
        "deletefile": data.file + " を削除しますか？"
    };
    return translation[id];
}