// AI Language Easter Egg for Bitrequest
// Because even robots need a point of sale

function lang_ai(id, data) {
    const translation = {
        "payoff": "Accept crypto, human",

        // PAGES
        "home": "mainframe",
        "currencies": "asset protocols",
        "requests": "value transmissions",
        "settings": "parameters",
        "coinsettings": "asset configuration",
        "addresses": "endpoint registry",

        // INTRO
        "enteryourname": "Identify yourself, human",
        "more": "Expand",
        "restorefrombackup": "Reconstruct from backup",

        // CORE
        // notifications
        "datasaved": "Data committed to memory",
        "pinmatch": "Access codes do not converge",
        "xratesx": "Exchange rate acquisition failed",
        "entercoinaddress": "Provide a " + data.currency + " endpoint.",
        "label": "designation (optional)",
        "errorvk": "Viewkey verification anomaly",
        "invalidvk": "Viewkey rejected",
        "continuevk": "Proceed without viewkey? Transaction monitoring will be disabled. This is inadvisable.",
        "novalidaddress": "is NOT a valid " + data.currency + " endpoint.",
        "pickacurrency": "Select an asset protocol",
        "invalidlabel": "Designation rejected",
        "noactivecurrencies": "No active asset protocols detected",
        "addressremoved": "Endpoint purged",
        "movedtoarchive": "Relocated to cold storage",
        "requestrestored": "Transmission reconstructed",
        "requestdeleted": "Transmission terminated",
        "requestsaved": "Transmission logged",
        "requiredfields": "Mandatory inputs incomplete",
        "requiredfield": "is a mandatory input",
        "requestinginvoice": "Generating invoice...",
        "nofetchincoice": "Invoice acquisition failed.",
        "copy": "Clone",
        "copied": "cloned to clipboard buffer",
        "xcopy": "Clone operation failed",
        "cashiernotallowed": "Insufficient clearance level",
        "decodeqr": "Optical matrix decode failed",
        "invalidformat": "Format rejected",
        "invalidmacaroon": "Macaroon structure corrupted",
        "recentrequests": "Recent transmissions",
        "encodeyoraddress": "Encode your endpoint at bitrequest.io/qr",
        // confirm
        "openurl": "Navigate to " + data.url + "?",
        "showrequestsfor": "Display transmissions for " + data.address + "?",
        "areyousure": "Confirm operation?",
        "openinvoice": "Access invoice: " + data.hash + "?",
        "sharefile": "Transmit " + data.filename + "?",
        // dialog
        "nofetchtokeninfo": "Token data acquisition failed.",
        "archiverequest": "Archive transmission?",
        "unarchiverequest": "Unarchive transmission?",
        "failedtofetchrequest": "Transmission retrieval failed",
        "downloadwallet": "Download " + data.currency + " wallet",

        // ADD ADDRESS
        "alreadyexists": "Endpoint already registered",
        "addaddress": "Register endpoint",
        "adderc20token": "Register ERC20 token",
        "erc20placeholder": "Select ERC20 token",
        "enteraddress": "Input endpoint",
        "noaddressyet": "No " + data.currency + " endpoint configured yet",

        // ADDRESS INFO
        "showrequests": "Display transmissions",
        "newrequest": "New transmission",
        "addressinfo": "Endpoint diagnostics",
        "editlabel": "Modify designation",
        "removeaddress": "Purge endpoint",
        "recentpayments": "Recent value transfers",
        "privatekey": "Secret key",
        "secretviewkey": "Secret view key",
        "secretspendkey": "Secret spend key",

        // REQUEST INFO
        "currency": "Asset",
        "from": "Origin",
        "title": "Descriptor",
        "amount": "Quantity",
        "status": "State",
        "Waiting for payment": "Awaiting value transfer",
        "paid": "Settled",
        "received": "Absorbed",
        "insufficient": "Deficit detected",
        "new": "Initialized",
        "pending": "Processing",
        "canceled": "Aborted",
        "expired": "TTL exceeded",
        "type": "Classification",
        "created": "Instantiated",
        "firstviewed": "First scanned",
        "sendon": "Transmitted on",
        "paidon": "Settled on",
        "amountreceived": "Quantity absorbed",
        "amountpaid": "Quantity dispensed",
        "fiatvalue": "Legacy currency value",
        "fiatvalueon": "Legacy currency value on",
        "receivingaddress": "Receiving endpoint",
        "fallbackaddress": "Fallback endpoint",
        "paymentid": "Transfer ID",
        "integratedaddress": "Integrated Endpoint",
        "network": "Network",
        "incoming": "Inbound",
        "outgoing": "Outbound",
        "point of sale": "Point of sale",
        "online purchase": "Remote acquisition",
        "transactions": "Ledger entries",
        "viewon": "Inspect on",
        "source": "Origin node",
        "deleterequest": "Terminate transmission",

        // REQUEST PANEL
        "sharerequest": "Broadcast transmission",
        "openwallet": "Launch wallet",
        "whatsyourname": "State your designation",
        "whatsitfor": "Specify purpose",
        "forexample": "eg",
        "send": "Transmit",
        "to": "to",
        "nodetection": "No value transfer detected",
        "lookuppayment": "Scan for recent inbound " + data.currency + " transfers on " + data.blockexplorer,
        "dontshowagain": "Suppress this alert",
        "dismiss": "dismiss",
        "activateintegrated": "Activate integrated endpoints",
        "pendingrequest": "Pending transmission",
        "paymentsent": "Value transfer dispatched",
        "paymentreceived": "Value transfer absorbed",
        "txbroadcasted": "Transaction propagated to network",
        "insufficientamount": "Quantity deficit detected",
        "txexpired": "Transmission TTL exceeded",
        "viewdetails": "Inspect payload",
        "showqr": "Render optical matrix",
        "waitingfor": "Awaiting",
        "unconfirmedtx": "Unverified ledger entry",
        "amountshort": "deficit",
        "sharelocktitle": "Broadcast temporarily restricted.",
        "sharelockttext": "This endpoint has a <span id='view_pending_tx' class='linkcolor' data-requestid='" + data.pending_requestid + "'>pending broadcast</span>.",
        "waitforconfirm": "Await network consensus before reusing this endpoint.",
        "pickanotheraddress": "Select alternate endpoint:",
        // ** request suggestion placeholders ** //
        "lunch": "Fuel intake",
        "festivaltickets": "Festival access tokens",
        "coffee": "Caffeine supply",
        "present": "Gift object",
        "snowboarding": "Snow locomotion",
        "movietheater": "Cinema protocol",
        "shopping": "Goods acquisition",
        "videogame": "Interactive simulation",
        "drinks": "Liquid provisions",
        "concerttickets": "Concert access tokens",
        "camping": "Outdoor survival mode",
        "taxi": "Transport pod",
        "zoo": "Biological specimen exhibit",
        // notifications
        "failedhistoric": "Historical " + data.ccsymbol + " price data retrieval failed",
        "closingsockets": "Terminating sockets...",
        "nowriteaccess": "LNurl proxy write access denied, verify folder permissions",
        "notmonitored": "This endpoint is not under surveillance",
        "lnoffline": "Lightning node unresponsive",
        "addlightningnode": "Register lightning node",
        "addressinuse": "Endpoint occupied",
        "minimal2": "Descriptor requires minimum 2 characters",
        "minimal3": "Designation requires minimum 3 characters",
        "checkyourform": "Input validation failed",
        "entertitle": "Provide a descriptor",
        "latincharacters": "Only alphanumeric glyphs (A-Z), digits, and symbols permitted",
        "successshare": "Broadcast successful!",
        // confirm
        "opencoinsettings": "Access " + data.currency + " parameters?",
        "viewpendingrequest": "Inspect pending transmission?",
        "useinstead": "Substitute '" + data.thisinputvalue + "'?",
        "generatenewaddress": "Generate new " + data.currency + " endpoint? Wallet compatibility not guaranteed",
        // dialog
        "undefinedaddress": "Null endpoint, request fresh transmission",
        "invalidaddress": "Invalid " + data.payment + " endpoint",

        // SHARE REQUEST
        "share": "broadcast",
        "sharetitlename": (data.requestname === "Bitrequest") ? "Greetings. A " + data.pagenameccparam + " bitrequest of " + data.amount + " " + data.uoa + " for '" + data.requesttitle + "' has been generated" : data.requestname + " dispatched a " + data.pagenameccparam + " bitrequest of " + data.amount + " " + data.uoa + " for '" + data.requesttitle + "'",
        "sharetitle": data.pagenameccparam + " value transfer request for " + data.amount + " " + data.uoa,
        "sharetitlechange": data.payment + " transmission for " + data.newccvalue + " " + data.newccsymbol,

        // SETTINGS
        "accountsettings": "Your designation",
        "currencysettings": "Local legacy currency",
        "entercurrency": "Input currency",
        "setasdefault": "Set as primary",
        "langsettings": "language protocol",
        "chooselanguage": "Select language protocol",
        "themesettings": "Visual skin",
        "choosetheme": "Select visual skin",
        "security": "Security",
        "pinsettings": "Access code lock",
        "bip39_passphrase": "Secret Phrase",
        "backupsecretphrase": "Backup secret phrase",
        "missingkeywarning": data.seedstrtitle + " for '<span class='adspan'>" + data.address + "</span>' not found.<br/>Proceed with this endpoint?",
        "emptyphrase": "Secret phrase input is empty",
        "notinwordlist": data.missing_word + " not in dictionary",
        "notbip39compatible": "Secret phrase not BIP39 compatible",
        "mustbe12characters": "Secret phrase requires 12 words",
        "cannotsendfunds": "Bitrequest cannot dispatch funds!",
        "importtosend": "To dispatch funds, restore your <span class='show_bip39 ref'>12 word secret phrase</span> in a BIP39 compatible wallet:",
        "backup": "Backup system data",
        "backupwithgd": "Backup via Google Drive:",
        "nrchanges": "You have " + data.nr_changes + " uncommitted changes. Backup recommended.",
        "changein": "change in",
        "changesin": "changes in",
        "systembackup": "Full system backup",
        "downloadbu": "download backup",
        "installlbu": "install backup",
        "restore": "Restore system data",
        "restorewithgd": "Restore from Google Drive:",
        "lastrestore": "Last restore:",
        "lastbackup": "Last backup:",
        "restorefromfile": "Restore from file",
        "differentsecretphrase": "Alert. Backup contains divergent secret phrase.",
        "secretphrasefrombackup": "Secret phrase from backup",
        "currentsecretphrase": "Current secret phrase",
        "usesecretphrasefrombackup": "Use secret phrase from backup",
        "keepcurrentsecretphrase": "Keep current secret phrase",
        "comparesecretphrases": "Compare secret phrases",
        "csvexport": "Export CSV",
        "includearchive": "Include archive",
        "includereceipt": "Include receipt",
        "receipt": "Receipt",
        "advanced": "Deep parameters",
        "url_shorten_settings": "URL compressor",
        "shorturlnotfound": "Transmission not found",
        "cmcapisettings": "Crypto price data feed",
        "fiatapisettings": "Legacy currency price data",
        "api_proxy": "API Proxy",
        "updateproxy": "Proxy update required " + data.version + " > " + data.proxy_version,
        "addapiproxy": "Register API proxy",
        "controlyourkeys": "Control your own keys and rate limits:",
        "proxystep1": "Deploy the <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit'>API proxy module</a> on your server (PHP required).",
        "proxystep2": "Input your API keys in 'config.php'.",
        "proxystep3": "Input your server endpoint below.",
        "addrpcproxy": "Register RPC proxy",
        "tryotherproxy": "Attempt alternate proxy",
        "apikeys": "API Keys",
        "apicallfailed": "API request failed",
        "apididnotrespond": "API node unresponsive",
        "contactform": "Contact interface",
        "shipping": "delivery",
        "yourdetails": "Your identity data for remote acquisitions.",
        "permissions": "Access levels",
        "teaminvite": "Unit invite",
        "inviteteammembers": "Invite unit members (operatives, personnel etc.) to make transmissions on your behalf.",
        "teaminviteexplainer": "This will deploy Bitrequest on your unit member's device, pre-loaded with your public keys and restricted clearance (cashier).",
        "teaminviteaccess": "Your unit members cannot access funds or modify parameters.",
        "teaminviteharetitle": "Bitrequest Unit invitation from " + data.accountname,
        "teamupdate": "Unit update",
        "invitationexpiresin": "Invitation TTL",
        "installcompleted": "Deployment already completed!",
        "teamup": data.account + " requests unit formation for joint transmissions!",
        "teamupdata": data.account + " requests you update Bitrequest with latest public keys",
        "clickinstall": "By initiating install, Bitrequest will be deployed on your device with " + data.account + "'s public keys and restricted clearance.",
        // notifications
        "nameisrequired": "Designation is mandatory",
        "currencysaved": "Currency committed",
        "currencynotsupported": "Currency '" + data.currency + "' not recognized",
        "noiosbu": "iOS backup downloads currently offline",
        "downloaded": data.file + " downloaded",
        "filesize": "File exceeds size limit",
        "filetype": "Filetype '" + data.filetype + "' not recognized",
        "selectbackup": "Select a backup file",
        "unauthorized": "Access denied",
        "maxattempts": "Attempt threshold exceeded",
        "fourdigitpin": "Input your 4 digit access code",
        "wrongpin": "Access code rejected",
        "nocsvexports": "No transmissions to export",
        "validateapikey": "Provide a valid API key",
        "unabletopost": "POST request from " + data.fixed_url + " failed",
        "invalidapikey": "API key rejected",
        "apicallerror": "API call anomaly",
        "invalidapikeyname": "Invalid " + data.thisref + " API key",
        "addapikey": "Register " + data.apisrc + " API key",
        "phname": "Designation",
        "phaddress": "Location",
        "phzipcode": "Zone code",
        "phcity": "Settlement",
        "phcountry": "Territory",
        "phemail": "electronic mail",
        "invalidchars": "contains prohibited glyphs",
        "pleaseverify": "Verify your secret phrase.",
        "owndevice": "Cannot deploy invite on origin device",
        "installcomplete": "Deployment complete!",
        // confirm
        "includesecretphrase": "Include encrypted secret phrase in backup? Maintain backup file integrity!",
        "sharebu": "Broadcast system backup?",
        "installsb": "DEPLOY SYSTEM BACKUP? ALL CURRENT DATA WILL BE OVERWRITTEN",
        "downloadfile": "Download: " + data.file + "?",
        "restorefile": "Restore: " + data.file + "?",
        "restorefromdevice": "Restore " + data.file + " from " + data.device + " device?",
        "restorewithoutsecretphrase": "Restore without secret phrase?",
        "keepexistingsecretphrase": "Retain existing secret phrase?",
        "sharecsvexport": "Broadcast CSV export?",
        "disableshorturls": "Disable URL compression? Workflow disruption possible",
        "sendinvite": "Dispatch invite",
        "updatealert": "Update? All public keys will be refreshed.",
        "installalert": "Deploy? All public keys will be replaced.",

        // COIN SETTINGS
        "confirmations": "Confirmations",
        "showsatoshis": "Display satoshis",
        "Use random address": "Use random endpoint",
        "Share viewkey": "Share viewkey",
        "Integrated addresses": "Integrated endpoints",
        "Reuse address": "Reuse endpoint",
        "blockexplorers": "Blockexplorers",
        "chooseblockexplorer": "Select blockexplorer",
        "apis": "APIs",
        "addapi": "Register " + data.h_hint + " RPC:",
        "websockets": "Websockets",
        "addwebsocket": "Register " + data.h_hint + " websocket:",
        "layer2": "Layer 2",
        "Xpub": "Xpub",
        "bip32xpub": "BIP32 Extended public key",
        "addxpub": "Register " + data.currency + " Xpub key",
        "xpubmatch": "The above endpoints match those in my " + data.currency + " wallet.",
        "xpubkeys": "I control the secret phrase / Xpriv key",
        "Key derivations": "Key derivations",
        "derivationpath": "Derivation path",
        "soundbytes": "Audio alerts",
        "choosesoundbytes": "Select audio alert",
        "resetbutton": "factory reset",
        // notifications
        "unabletoconnect": "Connection failed",
        "nodealreadyadded": "Node already registered",
        "removedefaultnode": "Cannot purge default node",
        "rpcnoderemoved": "RPC node purged",
        "confirmmatch": "Confirm endpoint match",
        "confirmpkownership": "Confirm key ownership",
        "invalidxpub": "NOT a valid / supported " + data.currency + " Xpub key",
        "xpubsaved": "Xpub committed",
        "resetnotify": data.currency + " parameters restored to factory defaults",
        // confirm
        "reusewarningalert": "Generate new " + data.thiscurrency + " endpoints? Wallet compatibility not guaranteed.",
        "reusealert": "Reuse " + data.thiscurrency + " endpoints?",
        "confirmremovenode": "Purge '" + data.thisval + "'?",
        "disablexpub": "Disable Xpub endpoint derivation?",
        "replacexpub": "Replace Xpub?",
        "uselegacy": "Use " + data.thiscurrency + " Legacy endpoints?",
        "usesegwit": "Use " + data.thiscurrency + " SegWit endpoints?",
        "resetconfirm": "Reset " + data.currency + " parameters?",
        // dialog
        "resetdialog": "Reset " + data.currency + " parameters?",

        // LIGHTNING
        "Lightning network": "Lightning network",
        "lightningnode": "lightning node",
        "addnode": "Register node",
        "implementation": "Implementation",
        "tabyourboldcard": "Present your Boltcard to device sensor",
        "controlyourlnkeys": "Control your own lightning node and keys:",
        "lnnodestep1": "Deploy the <a href='https://github.com/bitrequest/bitrequest.github.io/tree/master/proxy' target='blank' class='exit ref'>proxy module</a> on your webserver.",
        "lnnodestep2": "Input your lightning node's REST host and keys in 'config.php'.",
        "lnnodestep3": "Input your server endpoint below.",
        "enterlnapikey": "Input proxy API key to unlock '" + data.proxy + "'",
        "viewinvoice": "Inspect invoice",
        "noinvoicesfound": "Zero invoices detected.",
        "invoiceslocked": "Node proxy locked, invoice retrieval denied.<br/>Input your proxy <span id='pw_unlock_invoices' data-pid='" + data.proxy_id + "' class='ref'>API key</span>.",
        "invoiceoffline": "Node offline, invoice retrieval impossible.",
        // notifications
        "nodenotfound": "Node not found",
        "proxynotfound": "Proxy not found",
        "enterserver": "Provide server endpoint",
        "defaultproxy": data.fixed_url + " is a default proxy",
        "proxyexists": "Proxy already registered",
        "invalidurl": "URL rejected",
        "selectimplementation": "Select implementation",
        "selectlnhost": "Select " + data.imp + " host",
        "selectkeyname": "Select " + data.impkeyname,
        "entermacaroon": "Provide 'invoice' macaroon",
        "invalidkeyformat": "Key format rejected",
        "proxylocked": "Node proxy locked, API key required",
        "proxyoffline": "Node offline, attempt " + data.proxy_message + " proxy",
        "folderpermissions": "Cache write failed, verify folder permissions.",
        "proxyadded": "Proxy registered",
        "unabletoconnectto": "Connection to " + data.value + " failed",
        "proxynameexists": data.imp + " node already registered",
        "proxyinuse": data.imp + ": '" + data.name + "' depends on this proxy, purge it first",
        "proxyremoved": "Proxy purged",
        "serviceremoved": "Service purged",
        "unknownproxy": "Unidentified proxy server",
        "proxyunlocked": "Proxy access granted!",
        "proxydatamissing": "Proxy data incomplete",
        "invoicecanceled": "Invoice aborted",
        // confirm
        "enablelightning": "Enable lightning transfers?",
        "disablelightning": "Disable lightning transfers?",
        "disableproxy": "Deactivate proxy " + data.set_proxy_val + "?",
        "enableproxy": "Activate proxy " + data.set_proxy_val + "?",
        // dialog
        "unabletoconnectln": "Lightning node connection failed",

        // BIP39
        "disclaimer": "Advisory!",
        "cannotbespend": "Funds received at endpoints derived from your secret phrase cannot be dispatched by Bitrequest.<br/>To dispatch funds, restore your secret phrase in a <a href='https://www.bitrequest.io/compatible-wallets' target='_blank' class='ref'>compatible wallet.</a>",
        "compatiblewallets": "Compatible wallets",
        "important": "Critical notice!",
        "abouttobecome": "You are about to achieve financial sovereignty.",
        "inthenextscreen": "The next screen will display your secret phrase.",
        "makesure": "Record it and store in a secure location!",
        "understandandok": "I acknowledge and accept these terms.",
        "entersecretphrase": "Input your secret phrase:",
        "writedownsecretphrase": "Record your secret phrase and store securely.",
        "ifyouloseyourphrase": "If you lose your phrase,<br/>you will lose your funds!",
        "understand": "Acknowledged!",
        "verifycurrent": "Verify current secret phrase:",
        "verifybackup": "Verify backup:",
        "withgreatpower": "With great power comes great responsibility.",
        "remember": "Remember to backup your <span id='toseed'>Secret phrase</span>.",
        "overwritten": "Backup your current <span id='toseed'>Secret phrase</span>. It will be overwritten",
        "word": "word",
        "idothislater": "Defer to later",
        "ivebackeditup": "Backup confirmed!",
        "next": "next",
        "prev": "prev",
        "findmorewallets": "Locate more wallets",
        // notifications
        "alreadyhavesecretphrase": "Secret phrase already exists",
        "wrongsecretphrase": "Secret phrase mismatch",
        "consent": "Consent required to proceed.",
        "secretphrasedeleted": "Secret phrase purged",
        "congratulations": "Congratulations. Financial sovereignty achieved!",
        "passphraseverified": "Passphrase verified",
        "backupasap": "Backup your secret phrase immediately",
        // confirm
        "resoresecretphrase": "Restore secret phrase",
        "areyousuredfp": "Confirm secret phrase deletion?",
        "restoresecretphrasefrombackup": "Restore secret phrase from backup? Current secret phrase will be erased.",
        // dialog
        "continueatownrisk": "Alert! Proceed at own risk.",
        "ifyouloseyourdevice": "If you lose your device, uninstall your application or clear browser data, your secret phrase is required to recover funds!",
        "deletingyoursecretphrase": "Alert! Deleting your secret phrase may result in irreversible fund loss.",
        "continuewithbackup": "Proceed only if secret phrase backup exists.",

        // SOCKETS
        // notifications
        "youareoffline": "Network connection lost",
        "networks": "networks",
        "acceptthepayment": "Accept the transfer in your lightning app...",
        "ndeftablimit": "NFC scan rate exceeded",
        "enteramount": "Specify quantity",
        "cardmax": "Transmission exceeds card threshold",
        "minamount": "Minimum transmission quantity is " + data.min,
        "waitingforpayment": "Awaiting value transfer",
        "websocketoffline": "node offline",

        // PIN PANEL
        "pleaseenter": "Input your access code",
        "createpin": "Create a 4-digit access code",
        "locktime": "Lock timeout",
        "resetpin": "Reset access code",
        "enternewpin": "Input new access code",
        "minute": "minute",
        "minutes": "minutes",
        "never": "never",
        "pincodeactivated": "Access code activated",
        "pincodedisabled": "Access code disabled",
        "confirmyourpin": "Confirm your access code",

        // LOCKSCREEN
        "unlockwithsecretphrase": "Unlock with secret phrase",
        "tomanyunlocks": "Unlock attempt limit exceeded",
        "enter12words": "Input your 12 word<br/>secret phrase:",
        "tryagainin": "Retry permitted in",
        "unlock": "Unlock",

        // BUTTONS AND PANELS
        "cancelbttn": "abort",
        "okbttn": "execute",
        "show": "Reveal",
        "hide": "Conceal",
        "delete": "purge",
        "restorebttn": "reconstruct",
        "showtransactions": "Display ledger entries",
        "sharerequestbutton": "Broadcast transmission",
        "addcoinaddress": "Register " + data.currency + " endpoint",
        "generatewallet": "Derive wallet from secret phrase.",
        "pkownership": "I control the private key of this endpoint.",
        "nopub": "Endpoint / Xpub",
        "update": "update",
        "install": "deploy",
        "pay": "transfer",

        //DIALOGS
        "totalchanges": "You have " + data.total_changes + " uncommitted changes",
        "nochanges": "You have 0 uncommitted changes",
        "havewallet": "Is a " + data.lnd_ref + " wallet present on this device?",

        // DATES
        "sunday": "Sunday",
        "monday": "Monday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday",
        "thursday": "Thursday",
        "friday": "Friday",
        "saturday": "Saturday",
        "year": "cycle",
        "years": "cycles",
        "month": "subcycle",
        "months": "subcycles",
        "week": "week",
        "weeks": "weeks",
        "day": "rotation",
        "days": "rotations",
        "hour": "hour",
        "hours": "hours",
        "minute": "minute",
        "minutes": "minutes",
        "seconds": "seconds",
        "and": "and",
        "expiresin": "TTL: ",
        "fileexpired": "File TTL exceeded",

        // LOADERTEXT
        "generatereceipt": "Compiling receipt",
        "connecttolnur": "Establishing link to " + data.url,
        "loadurl": "Fetching " + data.url,
        "loading": "processing...",
        "gettokeninfo": "Acquiring token data",
        "checklightningstatus": "Probing " + data.imp + " lightning status",
        "readingfromcache": "Reading " + data.ccsymbol + " rate from cache",
        "getccrates": "Fetching " + data.ccsymbol + " rates from " + data.api,
        "getfiatrates": "Fetching legacy currency rates",
        "readingfiatratesfromcache": "Reading legacy rates from cache",
        "fetchingfiatrates": "Acquiring legacy rates from " + data.fiatapi,
        "generatelink": "Generating link",
        "loadingcamera": "Initializing optical sensor",
        "generatebu": "Compiling system backup",
        "installationpackage": "Compiling deployment package",

        // RANDOM TERMS
        "address": "endpoint",
        "choose": "Select",
        "enable": "Activate",
        "disable": "Deactivate",
        "apikey": "API key",
        "yes": "affirmative",
        "no": "negative",
        "none": "null",
        "verified": "verified",
        "error": "Anomaly",
        "apierror": "API anomaly",
        "success": "Operation complete",
        "warning": "Alert!",
        "edit": "Modify",
        "enter": "Input",

        // CHECK INTENTS
        "proto": data.proto + ": protocol unavailable at this time",
        "invalidurlscheme": "Invalid URL scheme",
        "usnotsupported": "URL scheme '" + data.proto + ":' is not supported",

        // GOOGLE AUTH
        "stopgauth": "Terminate Google Drive Backup.",
        "gauthsafely": "Securely backup your system data.",
        "gauthsync": "Synchronize your data with Google Drive.",
        "signin": "Authenticate",
        "backuptogd": "Backup to Google Drive",
        // notifications
        "ganot": "GoogleAuth unavailable",
        "gdsignedin": "Authentication successful",
        "gdsignedout": "Session terminated",
        "filedeleted": "File purged",
        "filenotfound": "File not found",
        // confirm
        "stopgdalert": "Terminate Google Drive Backup?",
        "deletefile": "Purge" + " " + data.file + "?"
    }
    return translation[id];
}